// Code generated by "stringer -type=TransportType,AuthRequirement,MetadataDiscovery,OAuthDiscovery,OAuthRegistration,OAuthFlow,OAuthTokenStatus,AuthType -linecomment -output=parameters_string.gen.go"; DO NOT EDIT.

package mcpmock

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TransportSSE-0]
	_ = x[TransportHTTP-1]
}

const _TransportType_name = "ssehttp"

var _TransportType_index = [...]uint8{0, 3, 7}

func (i TransportType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_TransportType_index)-1 {
		return "TransportType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TransportType_name[_TransportType_index[idx]:_TransportType_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AuthNone-0]
	_ = x[AuthOptional-1]
	_ = x[AuthRequired-2]
	_ = x[AuthNoHeader-3]
}

const _AuthRequirement_name = "noneoptionalrequiredno_header"

var _AuthRequirement_index = [...]uint8{0, 4, 12, 20, 29}

func (i AuthRequirement) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_AuthRequirement_index)-1 {
		return "AuthRequirement(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AuthRequirement_name[_AuthRequirement_index[idx]:_AuthRequirement_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MetadataDiscoveryNone-0]
	_ = x[MetadataDiscoveryRoot-1]
	_ = x[MetadataDiscoveryPathSpecific-2]
	_ = x[MetadataDiscoveryPathExplicit-3]
}

const _MetadataDiscovery_name = "nonerootpath_specificpath_explicit"

var _MetadataDiscovery_index = [...]uint8{0, 4, 8, 21, 34}

func (i MetadataDiscovery) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_MetadataDiscovery_index)-1 {
		return "MetadataDiscovery(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MetadataDiscovery_name[_MetadataDiscovery_index[idx]:_MetadataDiscovery_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OAuthDiscoveryNone-0]
	_ = x[OAuthDiscoveryAuthOnly-1]
	_ = x[OAuthDiscoveryFull-2]
}

const _OAuthDiscovery_name = "noneauth_onlyfull"

var _OAuthDiscovery_index = [...]uint8{0, 4, 13, 17}

func (i OAuthDiscovery) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_OAuthDiscovery_index)-1 {
		return "OAuthDiscovery(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OAuthDiscovery_name[_OAuthDiscovery_index[idx]:_OAuthDiscovery_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OAuthRegistrationNotSupported-0]
	_ = x[OAuthRegistrationSupported-1]
}

const _OAuthRegistration_name = "not_supportedsupported"

var _OAuthRegistration_index = [...]uint8{0, 13, 22}

func (i OAuthRegistration) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_OAuthRegistration_index)-1 {
		return "OAuthRegistration(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OAuthRegistration_name[_OAuthRegistration_index[idx]:_OAuthRegistration_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OAuthFlowReturnsURL-0]
	_ = x[OAuthFlowAuthLinkError-1]
	_ = x[OAuthFlowInstantlyReturnsToken-2]
}

const _OAuthFlow_name = "returns_urlauth_link_errorinstantly_returns_token"

var _OAuthFlow_index = [...]uint8{0, 11, 26, 49}

func (i OAuthFlow) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_OAuthFlow_index)-1 {
		return "OAuthFlow(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OAuthFlow_name[_OAuthFlow_index[idx]:_OAuthFlow_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TokenValid-0]
	_ = x[TokenExpiredRefreshValid-1]
	_ = x[TokenExpiredRefreshExpired-2]
}

const _OAuthTokenStatus_name = "validexpired_refresh_validexpired_refresh_expired"

var _OAuthTokenStatus_index = [...]uint8{0, 5, 26, 49}

func (i OAuthTokenStatus) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_OAuthTokenStatus_index)-1 {
		return "OAuthTokenStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OAuthTokenStatus_name[_OAuthTokenStatus_index[idx]:_OAuthTokenStatus_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AuthTypeNone-0]
	_ = x[AuthTypeBearer-1]
	_ = x[AuthTypeRandomized-2]
}

const _AuthType_name = "nonebearerrandomized"

var _AuthType_index = [...]uint8{0, 4, 10, 20}

func (i AuthType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_AuthType_index)-1 {
		return "AuthType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AuthType_name[_AuthType_index[idx]:_AuthType_index[idx+1]]
}
