version: 3

allow:
  deepScan: true

excludeFiles:
  - ".*_test.go"
  - "main.go"

  # contrib should have each goarchlint rule
  - "contrib/.*"

components:
  aggregates: { in: "internal/domains/cynosure/aggregates/**" }
  primitives: { in: "internal/domains/cynosure/primitives/**" }
  entities: { in: "internal/domains/cynosure/entities/**" }
  ports: { in: "internal/domains/cynosure/ports/**" }
  usecases: { in: "internal/domains/cynosure/usecases/**" }

  adapters.gemini: { in: "internal/adapters/gemini/**" }
  adapters.mcp: { in: "internal/adapters/mcp/**" }
  adapters.mocks: { in: "internal/adapters/mocks/**" }
  adapters.oauth: { in: "internal/adapters/oauth/**" }
  adapters.ory: { in: "internal/adapters/ory/**" }
  adapters.sql: { in: "internal/adapters/sql/**" }
  adapters.inmemory: { in: "internal/adapters/inmemory/**" }

  controllers.a2a: { in: "internal/controllers/a2a/**" }
  controllers.admin: { in: "internal/controllers/admin/**" }
  controllers.mcp: { in: "internal/controllers/mcp/**" }
  controllers.oauth: { in: "internal/controllers/oauth/**" }
  controllers.telegram: { in: "internal/controllers/telegram/**" }

  cmds.cynosure: { in: "cmd/cynosure/**" }

  logs: { in: "internal/logs/**" }

  apps.cynosure: { in: "internal/apps/cynosure/**" }

vendors:
  uuid: { in: github.com/google/uuid }
  oauth: { in: golang.org/x/oauth2 }
  otel:
    in:
      - go.opentelemetry.io/otel/trace
      - go.opentelemetry.io/otel/trace/noop
      - go.opentelemetry.io/otel/log
      - go.opentelemetry.io/otel/log/noop
      - go.opentelemetry.io/otel/sdk/resource
      - go.opentelemetry.io/otel/semconv/*
      - go.opentelemetry.io/otel/sdk/trace
      - go.opentelemetry.io/contrib/bridges/otelslog
  cose:
    in:
      - github.com/ldclabs/cose/**
  network.grpc:
    in:
      - buf.build/go/protovalidate
      - contrib/grpcutils
      - google.golang.org/grpc
      - google.golang.org/grpc/reflection
      - go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc

  debug_tools:
    in:
      - github.com/k0kubun/pp/v3

  mockery:
    in:
      - github.com/stretchr/testify/mock

  apis.gemini:
    in:
      - google.golang.org/genai

  apis.zep:
    in:
      - github.com/getzep/zep-go/v2
      - github.com/getzep/zep-go/v2/client
      - github.com/getzep/zep-go/v2/option

  apis.a2a:
    in:
      - google.golang.org/a2a/**
      - google.golang.org/grpc/**
      - google.golang.org/protobuf/**

  apis.telegram:
    in:
      - github.com/quenbyako/cynosure/contrib/telegram-proto/**
      - github.com/quenbyako/cynosure/contrib/telegram-bot-api/**

  apis.wire:
    in:
      - github.com/goforj/wire/**

  apis.admin:
    in:
      - github.com/quenbyako/cynosure/contrib/agent-proto/**

  apis.oauth:
    in:
      - github.com/quenbyako/cynosure/contrib/oauth-openapi/gen/go

  apis.core:
    in:
      - github.com/quenbyako/core
      - github.com/quenbyako/core/**

  apis.mcp:
    in:
      - github.com/modelcontextprotocol/go-sdk/**

commonVendors:
  - uuid
  - oauth
  - otel
  - cose
  - debug_tools

deps:
  primitives: { mayDependOn: [ primitives ] }

  entities:
    mayDependOn:
      - primitives

  ports:
    mayDependOn:
      - primitives
      - entities

  aggregates:
    mayDependOn:
      - primitives
      - entities
      - ports

  usecases:
    mayDependOn:
      - primitives
      - entities
      - aggregates
      - ports

  adapters.gemini:
    mayDependOn:
      - primitives
      - entities
      - ports
    canUse:
      - apis.gemini

  adapters.mcp:
    mayDependOn:
      - primitives
      - entities
      - ports

  adapters.mocks:
    mayDependOn:
      - primitives
      - entities
      - ports
    canUse:
      - mockery

  adapters.oauth:
    mayDependOn:
      - primitives
      - entities
      - ports

  adapters.ory:
    mayDependOn:
      - primitives
      - entities
      - ports

  adapters.sql:
    mayDependOn:
      - primitives
      - entities
      - ports

  controllers.a2a:
    mayDependOn:
      - primitives
      - usecases
    canUse:
      - apis.a2a

  controllers.admin:
    mayDependOn:
      - primitives
      - usecases
    canUse:
      - apis.admin

  controllers.mcp:
    mayDependOn:
      - primitives
      - usecases

  controllers.oauth:
    mayDependOn:
      - primitives
      - usecases

  controllers.telegram:
    mayDependOn:
      - primitives
      - usecases

  apps.cynosure:
    mayDependOn:
      - primitives
      - entities
      - ports
      - usecases
      - aggregates
      - logs
      - adapters.gemini
      - adapters.mcp
      - adapters.mocks
      - adapters.oauth
      - adapters.ory
      - adapters.sql
      - adapters.inmemory
      - controllers.a2a
      - controllers.admin
      - controllers.mcp
      - controllers.oauth
      - controllers.telegram
    canUse:
      - network.grpc
      - apis.gemini
      - apis.core
      - apis.mcp
      - apis.wire

  cmds.cynosure:
    mayDependOn:
      - apps.cynosure
