# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

version: 2
project_name: cynosure
dist: ./dist

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: cynosure
    builder: go
    main: ./cmd/cynosure
    binary: cynosure
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    tags: []
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: linux
        goarch: arm64
      - goos: darwin
        goarch: amd64

dockers_v2:
  - images:
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY }}"
    tags:
      - "v{{ .Version }}"
      - "{{ if .IsNightly }}nightly{{ end }}"
      - "{{ if not .IsNightly }}latest{{ end }}"
    flags:
      - "--build-arg=PRIMARY_APP_NAME=cynosure"
      - "--build-arg=APP_VERSION={{.Version}}"
      - "--build-arg=APP_COMMIT={{.Commit}}"
      - "--build-arg=APP_DATE={{.Date}}"
    dockerfile: Dockerfile

    annotations:
      "org.opencontainers.image.description": "Cynosure AI Runtime"
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.name": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"
      "org.opencontainers.image.source": "{{.GitURL}}"

      # You can also use `.BaseImage` and `.BaseImageDigest`.
      "org.opencontainers.image.base.name": "{{.BaseImage}}"
      "org.opencontainers.image.base.digest": "{{.BaseImageDigest}}"
