# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

version: 2
project_name: cynosure
dist: ./dist

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: cynosure
    builder: go
    main: ./cmd/cynosure
    binary: cynosure
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    tags: []
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    # goarm64:
    #   - "v8.0"
    ignore:
      - goos: linux
        goarch: arm64
      - goos: darwin
        goarch: amd64

upx:
  - enabled: true
