all: false
packages:
  github.com/quenbyako/cynosure/internal/domains/cynosure/ports:
    config:
      pkgname: "mocks"
      dir: ./internal/adapters/mocks
    interfaces:
      AccountStorage:
        config:
          filename: "account_storage.go"
      StorageRepository:
        config:
          filename: "storage_repository.go"
      ToolManager:
        config:
          filename: "tool_manager.go"
