all: false
packages:
  github.com/quenbyako/cynosure/internal/domains/cynosure/ports:
    config:
      pkgname: "mocks"
      dir: ./internal/adapters/mocks
    interfaces:
      AccountStorage:
        config:
          filename: "account_storage.go"
      AgentStorage:
        config:
          filename: "agent_storage.go"
      ChatModel:
        config:
          filename: "chat_model.go"
      ServerStorage:
        config:
          filename: "server_storage.go"
      ThreadStorage:
        config:
          filename: "thread_storage.go"
      ToolSemanticIndex:
        config:
          filename: "tool_semantic_index.go"
      ToolStorage:
        config:
          filename: "tool_storage.go"
  github.com/quenbyako/cynosure/internal/domains/cynosure/ports/toolclient:
    config:
      pkgname: "mocks"
      dir: ./internal/adapters/mocks
    interfaces:
      Port:
        config:
          filename: "tool_client.go"
          structname: "ToolClient"
  github.com/quenbyako/cynosure/internal/domains/cynosure/ports/oauthhandler:
    config:
      pkgname: "mocks"
      dir: ./internal/adapters/mocks
    interfaces:
      Port:
        config:
          filename: "oauth_handler.go"
          structname: "OAuthHandler"
