// Code generated by ogen, DO NOT EDIT.

package httpapi

import (
	"io"

	"github.com/go-faster/errors"
	"github.com/go-faster/jx"
)

// Defines optional capabilities supported by an agent.
// Ref: #/components/schemas/AgentCapabilities
type AgentCapabilities struct {
	// A list of protocol extensions supported by the agent.
	Extensions []AgentExtension `json:"extensions"`
	// Indicates if the agent supports sending push notifications for asynchronous task updates.
	PushNotifications OptBool `json:"pushNotifications"`
	// Indicates if the agent provides a history of state transitions for a task.
	StateTransitionHistory OptBool `json:"stateTransitionHistory"`
	// Indicates if the agent supports Server-Sent Events (SSE) for streaming responses.
	Streaming OptBool `json:"streaming"`
}

// GetExtensions returns the value of Extensions.
func (s *AgentCapabilities) GetExtensions() []AgentExtension {
	return s.Extensions
}

// GetPushNotifications returns the value of PushNotifications.
func (s *AgentCapabilities) GetPushNotifications() OptBool {
	return s.PushNotifications
}

// GetStateTransitionHistory returns the value of StateTransitionHistory.
func (s *AgentCapabilities) GetStateTransitionHistory() OptBool {
	return s.StateTransitionHistory
}

// GetStreaming returns the value of Streaming.
func (s *AgentCapabilities) GetStreaming() OptBool {
	return s.Streaming
}

// SetExtensions sets the value of Extensions.
func (s *AgentCapabilities) SetExtensions(val []AgentExtension) {
	s.Extensions = val
}

// SetPushNotifications sets the value of PushNotifications.
func (s *AgentCapabilities) SetPushNotifications(val OptBool) {
	s.PushNotifications = val
}

// SetStateTransitionHistory sets the value of StateTransitionHistory.
func (s *AgentCapabilities) SetStateTransitionHistory(val OptBool) {
	s.StateTransitionHistory = val
}

// SetStreaming sets the value of Streaming.
func (s *AgentCapabilities) SetStreaming(val OptBool) {
	s.Streaming = val
}

// A declaration of a protocol extension supported by an Agent.
// Ref: #/components/schemas/AgentExtension
type AgentExtension struct {
	// A human-readable description of how this agent uses the extension.
	Description OptString `json:"description"`
	// Optional, extension-specific configuration parameters.
	Params OptAgentExtensionParams `json:"params"`
	// If true, the client must understand and comply with the extension's requirements
	// to interact with the agent.
	Required OptBool `json:"required"`
	// The unique URI identifying the extension.
	URI string `json:"uri"`
}

// GetDescription returns the value of Description.
func (s *AgentExtension) GetDescription() OptString {
	return s.Description
}

// GetParams returns the value of Params.
func (s *AgentExtension) GetParams() OptAgentExtensionParams {
	return s.Params
}

// GetRequired returns the value of Required.
func (s *AgentExtension) GetRequired() OptBool {
	return s.Required
}

// GetURI returns the value of URI.
func (s *AgentExtension) GetURI() string {
	return s.URI
}

// SetDescription sets the value of Description.
func (s *AgentExtension) SetDescription(val OptString) {
	s.Description = val
}

// SetParams sets the value of Params.
func (s *AgentExtension) SetParams(val OptAgentExtensionParams) {
	s.Params = val
}

// SetRequired sets the value of Required.
func (s *AgentExtension) SetRequired(val OptBool) {
	s.Required = val
}

// SetURI sets the value of URI.
func (s *AgentExtension) SetURI(val string) {
	s.URI = val
}

// Optional, extension-specific configuration parameters.
type AgentExtensionParams map[string]jx.Raw

func (s *AgentExtensionParams) init() AgentExtensionParams {
	m := *s
	if m == nil {
		m = map[string]jx.Raw{}
		*s = m
	}
	return m
}

// Represents a distinct capability or function that an agent can perform.
// Ref: #/components/schemas/AgentSkill
type AgentSkill struct {
	// A detailed description of the skill, intended to help clients or users
	// understand its purpose and functionality.
	Description string `json:"description"`
	// Example prompts or scenarios that this skill can handle. Provides a hint to
	// the client on how to use the skill.
	Examples []string `json:"examples"`
	// A unique identifier for the agent's skill.
	ID string `json:"id"`
	// The set of supported input MIME types for this skill, overriding the agent's defaults.
	InputModes []string `json:"inputModes"`
	// A human-readable name for the skill.
	Name string `json:"name"`
	// The set of supported output MIME types for this skill, overriding the agent's defaults.
	OutputModes []string `json:"outputModes"`
	// Security schemes necessary for the agent to leverage this skill.
	// As in the overall AgentCard.security, this list represents a logical OR of security
	// requirement objects. Each object is a set of security schemes that must be used together
	// (a logical AND).
	Security []AgentSkillSecurityItem `json:"security"`
	// A set of keywords describing the skill's capabilities.
	Tags []string `json:"tags"`
}

// GetDescription returns the value of Description.
func (s *AgentSkill) GetDescription() string {
	return s.Description
}

// GetExamples returns the value of Examples.
func (s *AgentSkill) GetExamples() []string {
	return s.Examples
}

// GetID returns the value of ID.
func (s *AgentSkill) GetID() string {
	return s.ID
}

// GetInputModes returns the value of InputModes.
func (s *AgentSkill) GetInputModes() []string {
	return s.InputModes
}

// GetName returns the value of Name.
func (s *AgentSkill) GetName() string {
	return s.Name
}

// GetOutputModes returns the value of OutputModes.
func (s *AgentSkill) GetOutputModes() []string {
	return s.OutputModes
}

// GetSecurity returns the value of Security.
func (s *AgentSkill) GetSecurity() []AgentSkillSecurityItem {
	return s.Security
}

// GetTags returns the value of Tags.
func (s *AgentSkill) GetTags() []string {
	return s.Tags
}

// SetDescription sets the value of Description.
func (s *AgentSkill) SetDescription(val string) {
	s.Description = val
}

// SetExamples sets the value of Examples.
func (s *AgentSkill) SetExamples(val []string) {
	s.Examples = val
}

// SetID sets the value of ID.
func (s *AgentSkill) SetID(val string) {
	s.ID = val
}

// SetInputModes sets the value of InputModes.
func (s *AgentSkill) SetInputModes(val []string) {
	s.InputModes = val
}

// SetName sets the value of Name.
func (s *AgentSkill) SetName(val string) {
	s.Name = val
}

// SetOutputModes sets the value of OutputModes.
func (s *AgentSkill) SetOutputModes(val []string) {
	s.OutputModes = val
}

// SetSecurity sets the value of Security.
func (s *AgentSkill) SetSecurity(val []AgentSkillSecurityItem) {
	s.Security = val
}

// SetTags sets the value of Tags.
func (s *AgentSkill) SetTags(val []string) {
	s.Tags = val
}

type AgentSkillSecurityItem map[string][]string

func (s *AgentSkillSecurityItem) init() AgentSkillSecurityItem {
	m := *s
	if m == nil {
		m = map[string][]string{}
		*s = m
	}
	return m
}

type GetAgentCardDef struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s GetAgentCardDef) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

// GetAgentCardDefStatusCode wraps GetAgentCardDef with StatusCode.
type GetAgentCardDefStatusCode struct {
	StatusCode int
	Response   GetAgentCardDef
}

// GetStatusCode returns the value of StatusCode.
func (s *GetAgentCardDefStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *GetAgentCardDefStatusCode) GetResponse() GetAgentCardDef {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *GetAgentCardDefStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *GetAgentCardDefStatusCode) SetResponse(val GetAgentCardDef) {
	s.Response = val
}

func (*GetAgentCardDefStatusCode) getAgentCardRes() {}

type GetAgentCardOK struct {
	// The version of the A2A protocol this agent supports.
	ProtocolVersion string `json:"protocolVersion"`
	// A human-readable name for the agent.
	Name string `json:"name"`
	// A human-readable description of the agent, assisting users and other agents
	// in understanding its purpose.
	Description string `json:"description"`
	// The preferred endpoint URL for interacting with the agent.
	// This URL MUST support the transport specified by 'preferredTransport'.
	URL string `json:"url"`
	// The transport protocol for the preferred endpoint (the main 'url' field).
	// If not specified, defaults to 'JSONRPC'.
	// IMPORTANT: The transport specified here MUST be available at the main 'url'.
	// This creates a binding between the main URL and its supported transport protocol.
	// Clients should prefer this transport and URL combination when both are supported.
	PreferredTransport OptGetAgentCardOKPreferredTransport `json:"preferredTransport"`
	// The agent's own version number. The format is defined by the provider.
	Version string `json:"version"`
	// A declaration of optional capabilities supported by the agent.
	Capabilities AgentCapabilities `json:"capabilities"`
	// Default set of supported input MIME types for all skills, which can be
	// overridden on a per-skill basis.
	DefaultInputModes []string `json:"defaultInputModes"`
	// Default set of supported output MIME types for all skills, which can be
	// overridden on a per-skill basis.
	DefaultOutputModes []string `json:"defaultOutputModes"`
	// The set of skills, or distinct capabilities, that the agent can perform.
	Skills []AgentSkill `json:"skills"`
}

// GetProtocolVersion returns the value of ProtocolVersion.
func (s *GetAgentCardOK) GetProtocolVersion() string {
	return s.ProtocolVersion
}

// GetName returns the value of Name.
func (s *GetAgentCardOK) GetName() string {
	return s.Name
}

// GetDescription returns the value of Description.
func (s *GetAgentCardOK) GetDescription() string {
	return s.Description
}

// GetURL returns the value of URL.
func (s *GetAgentCardOK) GetURL() string {
	return s.URL
}

// GetPreferredTransport returns the value of PreferredTransport.
func (s *GetAgentCardOK) GetPreferredTransport() OptGetAgentCardOKPreferredTransport {
	return s.PreferredTransport
}

// GetVersion returns the value of Version.
func (s *GetAgentCardOK) GetVersion() string {
	return s.Version
}

// GetCapabilities returns the value of Capabilities.
func (s *GetAgentCardOK) GetCapabilities() AgentCapabilities {
	return s.Capabilities
}

// GetDefaultInputModes returns the value of DefaultInputModes.
func (s *GetAgentCardOK) GetDefaultInputModes() []string {
	return s.DefaultInputModes
}

// GetDefaultOutputModes returns the value of DefaultOutputModes.
func (s *GetAgentCardOK) GetDefaultOutputModes() []string {
	return s.DefaultOutputModes
}

// GetSkills returns the value of Skills.
func (s *GetAgentCardOK) GetSkills() []AgentSkill {
	return s.Skills
}

// SetProtocolVersion sets the value of ProtocolVersion.
func (s *GetAgentCardOK) SetProtocolVersion(val string) {
	s.ProtocolVersion = val
}

// SetName sets the value of Name.
func (s *GetAgentCardOK) SetName(val string) {
	s.Name = val
}

// SetDescription sets the value of Description.
func (s *GetAgentCardOK) SetDescription(val string) {
	s.Description = val
}

// SetURL sets the value of URL.
func (s *GetAgentCardOK) SetURL(val string) {
	s.URL = val
}

// SetPreferredTransport sets the value of PreferredTransport.
func (s *GetAgentCardOK) SetPreferredTransport(val OptGetAgentCardOKPreferredTransport) {
	s.PreferredTransport = val
}

// SetVersion sets the value of Version.
func (s *GetAgentCardOK) SetVersion(val string) {
	s.Version = val
}

// SetCapabilities sets the value of Capabilities.
func (s *GetAgentCardOK) SetCapabilities(val AgentCapabilities) {
	s.Capabilities = val
}

// SetDefaultInputModes sets the value of DefaultInputModes.
func (s *GetAgentCardOK) SetDefaultInputModes(val []string) {
	s.DefaultInputModes = val
}

// SetDefaultOutputModes sets the value of DefaultOutputModes.
func (s *GetAgentCardOK) SetDefaultOutputModes(val []string) {
	s.DefaultOutputModes = val
}

// SetSkills sets the value of Skills.
func (s *GetAgentCardOK) SetSkills(val []AgentSkill) {
	s.Skills = val
}

func (*GetAgentCardOK) getAgentCardRes() {}

// The transport protocol for the preferred endpoint (the main 'url' field).
// If not specified, defaults to 'JSONRPC'.
// IMPORTANT: The transport specified here MUST be available at the main 'url'.
// This creates a binding between the main URL and its supported transport protocol.
// Clients should prefer this transport and URL combination when both are supported.
type GetAgentCardOKPreferredTransport string

const (
	GetAgentCardOKPreferredTransportJSONRPC  GetAgentCardOKPreferredTransport = "JSONRPC"
	GetAgentCardOKPreferredTransportGRPC     GetAgentCardOKPreferredTransport = "GRPC"
	GetAgentCardOKPreferredTransportHTTPJSON GetAgentCardOKPreferredTransport = "HTTP+JSON"
)

// AllValues returns all GetAgentCardOKPreferredTransport values.
func (GetAgentCardOKPreferredTransport) AllValues() []GetAgentCardOKPreferredTransport {
	return []GetAgentCardOKPreferredTransport{
		GetAgentCardOKPreferredTransportJSONRPC,
		GetAgentCardOKPreferredTransportGRPC,
		GetAgentCardOKPreferredTransportHTTPJSON,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s GetAgentCardOKPreferredTransport) MarshalText() ([]byte, error) {
	switch s {
	case GetAgentCardOKPreferredTransportJSONRPC:
		return []byte(s), nil
	case GetAgentCardOKPreferredTransportGRPC:
		return []byte(s), nil
	case GetAgentCardOKPreferredTransportHTTPJSON:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *GetAgentCardOKPreferredTransport) UnmarshalText(data []byte) error {
	switch GetAgentCardOKPreferredTransport(data) {
	case GetAgentCardOKPreferredTransportJSONRPC:
		*s = GetAgentCardOKPreferredTransportJSONRPC
		return nil
	case GetAgentCardOKPreferredTransportGRPC:
		*s = GetAgentCardOKPreferredTransportGRPC
		return nil
	case GetAgentCardOKPreferredTransportHTTPJSON:
		*s = GetAgentCardOKPreferredTransportHTTPJSON
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type OAuthCallbackGetBadRequest struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s OAuthCallbackGetBadRequest) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*OAuthCallbackGetBadRequest) oAuthCallbackGetRes() {}

type OAuthCallbackGetDef struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s OAuthCallbackGetDef) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

// OAuthCallbackGetDefStatusCode wraps OAuthCallbackGetDef with StatusCode.
type OAuthCallbackGetDefStatusCode struct {
	StatusCode int
	Response   OAuthCallbackGetDef
}

// GetStatusCode returns the value of StatusCode.
func (s *OAuthCallbackGetDefStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *OAuthCallbackGetDefStatusCode) GetResponse() OAuthCallbackGetDef {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *OAuthCallbackGetDefStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *OAuthCallbackGetDefStatusCode) SetResponse(val OAuthCallbackGetDef) {
	s.Response = val
}

func (*OAuthCallbackGetDefStatusCode) oAuthCallbackGetRes() {}

type OAuthCallbackGetOK struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s OAuthCallbackGetOK) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*OAuthCallbackGetOK) oAuthCallbackGetRes() {}

// NewOptAgentExtensionParams returns new OptAgentExtensionParams with value set to v.
func NewOptAgentExtensionParams(v AgentExtensionParams) OptAgentExtensionParams {
	return OptAgentExtensionParams{
		Value: v,
		Set:   true,
	}
}

// OptAgentExtensionParams is optional AgentExtensionParams.
type OptAgentExtensionParams struct {
	Value AgentExtensionParams
	Set   bool
}

// IsSet returns true if OptAgentExtensionParams was set.
func (o OptAgentExtensionParams) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptAgentExtensionParams) Reset() {
	var v AgentExtensionParams
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptAgentExtensionParams) SetTo(v AgentExtensionParams) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptAgentExtensionParams) Get() (v AgentExtensionParams, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptAgentExtensionParams) Or(d AgentExtensionParams) AgentExtensionParams {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptBool returns new OptBool with value set to v.
func NewOptBool(v bool) OptBool {
	return OptBool{
		Value: v,
		Set:   true,
	}
}

// OptBool is optional bool.
type OptBool struct {
	Value bool
	Set   bool
}

// IsSet returns true if OptBool was set.
func (o OptBool) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptBool) Reset() {
	var v bool
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptBool) SetTo(v bool) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptBool) Get() (v bool, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptBool) Or(d bool) bool {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptGetAgentCardOKPreferredTransport returns new OptGetAgentCardOKPreferredTransport with value set to v.
func NewOptGetAgentCardOKPreferredTransport(v GetAgentCardOKPreferredTransport) OptGetAgentCardOKPreferredTransport {
	return OptGetAgentCardOKPreferredTransport{
		Value: v,
		Set:   true,
	}
}

// OptGetAgentCardOKPreferredTransport is optional GetAgentCardOKPreferredTransport.
type OptGetAgentCardOKPreferredTransport struct {
	Value GetAgentCardOKPreferredTransport
	Set   bool
}

// IsSet returns true if OptGetAgentCardOKPreferredTransport was set.
func (o OptGetAgentCardOKPreferredTransport) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptGetAgentCardOKPreferredTransport) Reset() {
	var v GetAgentCardOKPreferredTransport
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptGetAgentCardOKPreferredTransport) SetTo(v GetAgentCardOKPreferredTransport) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptGetAgentCardOKPreferredTransport) Get() (v GetAgentCardOKPreferredTransport, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptGetAgentCardOKPreferredTransport) Or(d GetAgentCardOKPreferredTransport) GetAgentCardOKPreferredTransport {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}
