// Code generated by ogen, DO NOT EDIT.

package httpapi

import (
	"net/http"

	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
)

// GetAgentCardParams is parameters of GetAgentCard operation.
type GetAgentCardParams struct {
	// The hostname of the server where the agent is running.
	Host OptString `json:",omitempty,omitzero"`
}

func unpackGetAgentCardParams(packed middleware.Parameters) (params GetAgentCardParams) {
	{
		key := middleware.ParameterKey{
			Name: "Host",
			In:   "header",
		}
		if v, ok := packed[key]; ok {
			params.Host = v.(OptString)
		}
	}
	return params
}

func decodeGetAgentCardParams(args [0]string, argsEscaped bool, r *http.Request) (params GetAgentCardParams, _ error) {
	h := uri.NewHeaderDecoder(r.Header)
	// Decode header: Host.
	if err := func() error {
		cfg := uri.HeaderParameterDecodingConfig{
			Name:    "Host",
			Explode: false,
		}
		if err := h.HasParam(cfg); err == nil {
			if err := h.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotHostVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotHostVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Host.SetTo(paramsDotHostVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "Host",
			In:   "header",
			Err:  err,
		}
	}
	return params, nil
}

// OAuthCallbackGetParams is parameters of GET /oauth/callback operation.
type OAuthCallbackGetParams struct {
	// The authorization code generated by the authorization server.
	Code string
	// An opaque value used by the client to maintain state between the
	// request and callback. The client should ensure that this value
	// matches the value sent in the original authorization request.
	State OptString `json:",omitempty,omitzero"`
}

func unpackOAuthCallbackGetParams(packed middleware.Parameters) (params OAuthCallbackGetParams) {
	{
		key := middleware.ParameterKey{
			Name: "code",
			In:   "query",
		}
		params.Code = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "state",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.State = v.(OptString)
		}
	}
	return params
}

func decodeOAuthCallbackGetParams(args [0]string, argsEscaped bool, r *http.Request) (params OAuthCallbackGetParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: code.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "code",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.Code = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "code",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: state.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "state",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotStateVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotStateVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.State.SetTo(paramsDotStateVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "state",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}
