// Code generated by ogen, DO NOT EDIT.

package httpapi

// OperationName is the ogen operation name
type OperationName = string

const (
	GetAgentCardOperation     OperationName = "GetAgentCard"
	OAuthCallbackGetOperation OperationName = "OAuthCallbackGet"
)
