// Code generated by ogen, DO NOT EDIT.

package httpapi

// setDefaults set default value of fields.
func (s *GetAgentCardOK) setDefaults() {
	{
		val := string("0.3.0")
		s.ProtocolVersion = val
	}
	{
		val := GetAgentCardOKPreferredTransport("JSONRPC")
		s.PreferredTransport.SetTo(val)
	}
}
