// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: xelaj/agent/v1alpha1/service.proto

package admin

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddServerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddServerRequest) Reset() {
	*x = AddServerRequest{}
	mi := &file_xelaj_agent_v1alpha1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddServerRequest) ProtoMessage() {}

func (x *AddServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xelaj_agent_v1alpha1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddServerRequest.ProtoReflect.Descriptor instead.
func (*AddServerRequest) Descriptor() ([]byte, []int) {
	return file_xelaj_agent_v1alpha1_service_proto_rawDescGZIP(), []int{0}
}

func (x *AddServerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AddServerRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type AddServerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddServerResponse) Reset() {
	*x = AddServerResponse{}
	mi := &file_xelaj_agent_v1alpha1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddServerResponse) ProtoMessage() {}

func (x *AddServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xelaj_agent_v1alpha1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddServerResponse.ProtoReflect.Descriptor instead.
func (*AddServerResponse) Descriptor() ([]byte, []int) {
	return file_xelaj_agent_v1alpha1_service_proto_rawDescGZIP(), []int{1}
}

type AuthorizeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AccountName   string                 `protobuf:"bytes,3,opt,name=account_name,json=accountName,proto3" json:"account_name,omitempty"`
	AccountDesc   string                 `protobuf:"bytes,4,opt,name=account_desc,json=accountDesc,proto3" json:"account_desc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizeRequest) Reset() {
	*x = AuthorizeRequest{}
	mi := &file_xelaj_agent_v1alpha1_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeRequest) ProtoMessage() {}

func (x *AuthorizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xelaj_agent_v1alpha1_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizeRequest.ProtoReflect.Descriptor instead.
func (*AuthorizeRequest) Descriptor() ([]byte, []int) {
	return file_xelaj_agent_v1alpha1_service_proto_rawDescGZIP(), []int{2}
}

func (x *AuthorizeRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *AuthorizeRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AuthorizeRequest) GetAccountName() string {
	if x != nil {
		return x.AccountName
	}
	return ""
}

func (x *AuthorizeRequest) GetAccountDesc() string {
	if x != nil {
		return x.AccountDesc
	}
	return ""
}

type AuthorizeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Link          string                 `protobuf:"bytes,1,opt,name=link,proto3" json:"link,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizeResponse) Reset() {
	*x = AuthorizeResponse{}
	mi := &file_xelaj_agent_v1alpha1_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeResponse) ProtoMessage() {}

func (x *AuthorizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xelaj_agent_v1alpha1_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizeResponse.ProtoReflect.Descriptor instead.
func (*AuthorizeResponse) Descriptor() ([]byte, []int) {
	return file_xelaj_agent_v1alpha1_service_proto_rawDescGZIP(), []int{3}
}

func (x *AuthorizeResponse) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

var File_xelaj_agent_v1alpha1_service_proto protoreflect.FileDescriptor

const file_xelaj_agent_v1alpha1_service_proto_rawDesc = "" +
	"\n" +
	"\"xelaj/agent/v1alpha1/service.proto\x12\x14xelaj.agent.v1alpha1\x1a\x1bbuf/validate/validate.proto\"H\n" +
	"\x10AddServerRequest\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\x12\x1a\n" +
	"\x03url\x18\x02 \x01(\tB\b\xbaH\x05r\x03\x88\x01\x01R\x03url\"\x13\n" +
	"\x11AddServerResponse\"\xcb\x01\n" +
	"\x10AuthorizeRequest\x12%\n" +
	"\tserver_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\bserverId\x12!\n" +
	"\auser_id\x18\x02 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x06userId\x12?\n" +
	"\faccount_name\x18\x03 \x01(\tB\x1c\xbaH\x19r\x172\x15^[a-zA-Z0-9_-]{3,32}$R\vaccountName\x12,\n" +
	"\faccount_desc\x18\x04 \x01(\tB\t\xbaH\x06r\x04\x10\x01\x18dR\vaccountDesc\"1\n" +
	"\x11AuthorizeResponse\x12\x1c\n" +
	"\x04link\x18\x01 \x01(\tB\b\xbaH\x05r\x03\x88\x01\x01R\x04link2\xce\x01\n" +
	"\fAdminService\x12^\n" +
	"\tAddServer\x12&.xelaj.agent.v1alpha1.AddServerRequest\x1a'.xelaj.agent.v1alpha1.AddServerResponse\"\x00\x12^\n" +
	"\tAuthorize\x12&.xelaj.agent.v1alpha1.AuthorizeRequest\x1a'.xelaj.agent.v1alpha1.AuthorizeResponse\"\x00B>Z<tg-helper/contrib/agent-proto/pkg/xelaj/admin/v1alpha1;adminb\x06proto3"

var (
	file_xelaj_agent_v1alpha1_service_proto_rawDescOnce sync.Once
	file_xelaj_agent_v1alpha1_service_proto_rawDescData []byte
)

func file_xelaj_agent_v1alpha1_service_proto_rawDescGZIP() []byte {
	file_xelaj_agent_v1alpha1_service_proto_rawDescOnce.Do(func() {
		file_xelaj_agent_v1alpha1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_xelaj_agent_v1alpha1_service_proto_rawDesc), len(file_xelaj_agent_v1alpha1_service_proto_rawDesc)))
	})
	return file_xelaj_agent_v1alpha1_service_proto_rawDescData
}

var file_xelaj_agent_v1alpha1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_xelaj_agent_v1alpha1_service_proto_goTypes = []any{
	(*AddServerRequest)(nil),  // 0: xelaj.agent.v1alpha1.AddServerRequest
	(*AddServerResponse)(nil), // 1: xelaj.agent.v1alpha1.AddServerResponse
	(*AuthorizeRequest)(nil),  // 2: xelaj.agent.v1alpha1.AuthorizeRequest
	(*AuthorizeResponse)(nil), // 3: xelaj.agent.v1alpha1.AuthorizeResponse
}
var file_xelaj_agent_v1alpha1_service_proto_depIdxs = []int32{
	0, // 0: xelaj.agent.v1alpha1.AdminService.AddServer:input_type -> xelaj.agent.v1alpha1.AddServerRequest
	2, // 1: xelaj.agent.v1alpha1.AdminService.Authorize:input_type -> xelaj.agent.v1alpha1.AuthorizeRequest
	1, // 2: xelaj.agent.v1alpha1.AdminService.AddServer:output_type -> xelaj.agent.v1alpha1.AddServerResponse
	3, // 3: xelaj.agent.v1alpha1.AdminService.Authorize:output_type -> xelaj.agent.v1alpha1.AuthorizeResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_xelaj_agent_v1alpha1_service_proto_init() }
func file_xelaj_agent_v1alpha1_service_proto_init() {
	if File_xelaj_agent_v1alpha1_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_xelaj_agent_v1alpha1_service_proto_rawDesc), len(file_xelaj_agent_v1alpha1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_xelaj_agent_v1alpha1_service_proto_goTypes,
		DependencyIndexes: file_xelaj_agent_v1alpha1_service_proto_depIdxs,
		MessageInfos:      file_xelaj_agent_v1alpha1_service_proto_msgTypes,
	}.Build()
	File_xelaj_agent_v1alpha1_service_proto = out.File
	file_xelaj_agent_v1alpha1_service_proto_goTypes = nil
	file_xelaj_agent_v1alpha1_service_proto_depIdxs = nil
}
