package chat

import (
	"context"
	"fmt"

	"github.com/quenbyako/cynosure/internal/domains/cynosure/primitives/messages"
)

// AcceptAssistantMessage records a response from the AI agent.
//
// Role in Agent Loop:
// This handles both final text responses and tool execution requests (Tool Calls)
// generated by the model.
//
// Optimization:
// Unlike [Chat.AcceptUserMessage], this method does NOT refresh the tool context.
// The assumption is that the model's response (or tool call) is based on the
// *current* context initiated by the user. Changing the available tools mid-turn
// (e.g., between a thought and a tool call) would be confusing and inconsistent.
//
// Atomicity:
// - Adds message to history.
// - Persists to storage.
func (c *Chat) AcceptAssistantMessage(ctx context.Context, message messages.MessageAssistant) error {
	c.mu.Lock()
	defer c.mu.Unlock()

	if err := c.thread.AddMessage(message); err != nil {
		return fmt.Errorf("adding assistant message: %w", err)
	}

	if err := c.storage.SaveThread(ctx, c.thread); err != nil {
		c.thread.Reset() // Rollback
		return fmt.Errorf("saving thread after assistant message: %w", err)
	}

	c.thread.ClearEvents()

	return nil
}
