package chat

import (
	"context"
	"fmt"

	"github.com/quenbyako/cynosure/internal/domains/cynosure/primitives/messages"
)

// AcceptToolRequest records tool calls generated by the assistant.
//
// Role in Agent Loop:
// When the model decides to use a tool, it generates an assistant message
// with one or more tool calls. This method registers these calls in the
// aggregate's state, marking them as "active" and awaiting results.
//
// Atomicity:
// 1. Adds the assistant message (containing tool calls) to the history.
// 2. Persists the state to storage.
// 3. Updates the activeCalls index.
func (c *Chat) AcceptToolRequest(ctx context.Context, message messages.MessageToolRequest) error {
	c.mu.Lock()
	defer c.mu.Unlock()

	if err := c.thread.AddMessage(message); err != nil {
		return fmt.Errorf("adding assistant tool request message: %w", err)
	}

	if err := c.storage.UpdateThread(ctx, c.thread); err != nil {
		c.thread.Reset()
		return fmt.Errorf("saving thread after tool request: %w", err)
	}

	c.activeCalls[message.ToolCallID()] = struct{}{}

	c.thread.ClearEvents()

	return nil
}
