// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package gateway

import (
	"context"
	"github.com/quenbyako/cynosure/internal/domains/gateway/ports"
)

// Injectors from wire.go:

func buildApp(ctx context.Context, config *appParams) (*App, error) {
	gatewayLogger := newLogCallbacks(config)
	messenger, err := newTelegramAdapter(ctx, config)
	if err != nil {
		return nil, err
	}
	portsMessenger := ports.NewMessenger(messenger)
	client, err := newA2AAdapter(ctx, config)
	if err != nil {
		return nil, err
	}
	agent := ports.NewAgent(client)
	usecase, err := newUsecase(ctx, config, portsMessenger, agent)
	if err != nil {
		return nil, err
	}
	app, err := newApp(config, gatewayLogger, usecase)
	if err != nil {
		return nil, err
	}
	return app, nil
}
