// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/quenbyako/cynosure/internal/domains/cynosure/entities"
	"github.com/quenbyako/cynosure/internal/domains/cynosure/ports/accounts"
	"github.com/quenbyako/cynosure/internal/domains/cynosure/primitives/ids"
	mock "github.com/stretchr/testify/mock"
)

// NewAccounts creates a new instance of Accounts. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAccounts(t interface {
	mock.TestingT
	Cleanup(func())
}) *Accounts {
	mock := &Accounts{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Accounts is an autogenerated mock type for the Port type
type Accounts struct {
	mock.Mock
}

type Accounts_Expecter struct {
	mock *mock.Mock
}

func (_m *Accounts) EXPECT() *Accounts_Expecter {
	return &Accounts_Expecter{mock: &_m.Mock}
}

// DeleteAccount provides a mock function for the type Accounts
func (_mock *Accounts) DeleteAccount(ctx context.Context, account ids.AccountID) error {
	ret := _mock.Called(ctx, account)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAccount")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ids.AccountID) error); ok {
		r0 = returnFunc(ctx, account)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Accounts_DeleteAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAccount'
type Accounts_DeleteAccount_Call struct {
	*mock.Call
}

// DeleteAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - account ids.AccountID
func (_e *Accounts_Expecter) DeleteAccount(ctx interface{}, account interface{}) *Accounts_DeleteAccount_Call {
	return &Accounts_DeleteAccount_Call{Call: _e.mock.On("DeleteAccount", ctx, account)}
}

func (_c *Accounts_DeleteAccount_Call) Run(run func(ctx context.Context, account ids.AccountID)) *Accounts_DeleteAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ids.AccountID
		if args[1] != nil {
			arg1 = args[1].(ids.AccountID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Accounts_DeleteAccount_Call) Return(err error) *Accounts_DeleteAccount_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Accounts_DeleteAccount_Call) RunAndReturn(run func(ctx context.Context, account ids.AccountID) error) *Accounts_DeleteAccount_Call {
	_c.Call.Return(run)
	return _c
}

// FindAccountsByName provides a mock function for the type Accounts
func (_mock *Accounts) FindAccountsByName(ctx context.Context, user ids.UserID, name string) ([]*entities.Account, error) {
	ret := _mock.Called(ctx, user, name)

	if len(ret) == 0 {
		panic("no return value specified for FindAccountsByName")
	}

	var r0 []*entities.Account
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ids.UserID, string) ([]*entities.Account, error)); ok {
		return returnFunc(ctx, user, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ids.UserID, string) []*entities.Account); ok {
		r0 = returnFunc(ctx, user, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Account)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ids.UserID, string) error); ok {
		r1 = returnFunc(ctx, user, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Accounts_FindAccountsByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAccountsByName'
type Accounts_FindAccountsByName_Call struct {
	*mock.Call
}

// FindAccountsByName is a helper method to define mock.On call
//   - ctx context.Context
//   - user ids.UserID
//   - name string
func (_e *Accounts_Expecter) FindAccountsByName(ctx interface{}, user interface{}, name interface{}) *Accounts_FindAccountsByName_Call {
	return &Accounts_FindAccountsByName_Call{Call: _e.mock.On("FindAccountsByName", ctx, user, name)}
}

func (_c *Accounts_FindAccountsByName_Call) Run(run func(ctx context.Context, user ids.UserID, name string)) *Accounts_FindAccountsByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ids.UserID
		if args[1] != nil {
			arg1 = args[1].(ids.UserID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Accounts_FindAccountsByName_Call) Return(accounts []*entities.Account, err error) *Accounts_FindAccountsByName_Call {
	_c.Call.Return(accounts, err)
	return _c
}

func (_c *Accounts_FindAccountsByName_Call) RunAndReturn(run func(ctx context.Context, user ids.UserID, name string) ([]*entities.Account, error)) *Accounts_FindAccountsByName_Call {
	_c.Call.Return(run)
	return _c
}

// GetAccount provides a mock function for the type Accounts
func (_mock *Accounts) GetAccount(ctx context.Context, account ids.AccountID, opts ...accounts.GetAccountOption) (*entities.Account, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, account, opts)
	} else {
		tmpRet = _mock.Called(ctx, account)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetAccount")
	}

	var r0 *entities.Account
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ids.AccountID, ...accounts.GetAccountOption) (*entities.Account, error)); ok {
		return returnFunc(ctx, account, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ids.AccountID, ...accounts.GetAccountOption) *entities.Account); ok {
		r0 = returnFunc(ctx, account, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Account)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ids.AccountID, ...accounts.GetAccountOption) error); ok {
		r1 = returnFunc(ctx, account, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Accounts_GetAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccount'
type Accounts_GetAccount_Call struct {
	*mock.Call
}

// GetAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - account ids.AccountID
//   - opts ...accounts.GetAccountOption
func (_e *Accounts_Expecter) GetAccount(ctx interface{}, account interface{}, opts ...interface{}) *Accounts_GetAccount_Call {
	return &Accounts_GetAccount_Call{Call: _e.mock.On("GetAccount",
		append([]interface{}{ctx, account}, opts...)...)}
}

func (_c *Accounts_GetAccount_Call) Run(run func(ctx context.Context, account ids.AccountID, opts ...accounts.GetAccountOption)) *Accounts_GetAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ids.AccountID
		if args[1] != nil {
			arg1 = args[1].(ids.AccountID)
		}
		var arg2 []accounts.GetAccountOption
		var variadicArgs []accounts.GetAccountOption
		if len(args) > 2 {
			variadicArgs = args[2].([]accounts.GetAccountOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *Accounts_GetAccount_Call) Return(account1 *entities.Account, err error) *Accounts_GetAccount_Call {
	_c.Call.Return(account1, err)
	return _c
}

func (_c *Accounts_GetAccount_Call) RunAndReturn(run func(ctx context.Context, account ids.AccountID, opts ...accounts.GetAccountOption) (*entities.Account, error)) *Accounts_GetAccount_Call {
	_c.Call.Return(run)
	return _c
}

// GetAccountsBatch provides a mock function for the type Accounts
func (_mock *Accounts) GetAccountsBatch(ctx context.Context, accounts1 []ids.AccountID) ([]*entities.Account, error) {
	ret := _mock.Called(ctx, accounts1)

	if len(ret) == 0 {
		panic("no return value specified for GetAccountsBatch")
	}

	var r0 []*entities.Account
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []ids.AccountID) ([]*entities.Account, error)); ok {
		return returnFunc(ctx, accounts1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []ids.AccountID) []*entities.Account); ok {
		r0 = returnFunc(ctx, accounts1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Account)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []ids.AccountID) error); ok {
		r1 = returnFunc(ctx, accounts1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Accounts_GetAccountsBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccountsBatch'
type Accounts_GetAccountsBatch_Call struct {
	*mock.Call
}

// GetAccountsBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - accounts1 []ids.AccountID
func (_e *Accounts_Expecter) GetAccountsBatch(ctx interface{}, accounts1 interface{}) *Accounts_GetAccountsBatch_Call {
	return &Accounts_GetAccountsBatch_Call{Call: _e.mock.On("GetAccountsBatch", ctx, accounts1)}
}

func (_c *Accounts_GetAccountsBatch_Call) Run(run func(ctx context.Context, accounts1 []ids.AccountID)) *Accounts_GetAccountsBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []ids.AccountID
		if args[1] != nil {
			arg1 = args[1].([]ids.AccountID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Accounts_GetAccountsBatch_Call) Return(accounts11 []*entities.Account, err error) *Accounts_GetAccountsBatch_Call {
	_c.Call.Return(accounts11, err)
	return _c
}

func (_c *Accounts_GetAccountsBatch_Call) RunAndReturn(run func(ctx context.Context, accounts1 []ids.AccountID) ([]*entities.Account, error)) *Accounts_GetAccountsBatch_Call {
	_c.Call.Return(run)
	return _c
}

// ListAccounts provides a mock function for the type Accounts
func (_mock *Accounts) ListAccounts(ctx context.Context, user ids.UserID) ([]ids.AccountID, error) {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for ListAccounts")
	}

	var r0 []ids.AccountID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ids.UserID) ([]ids.AccountID, error)); ok {
		return returnFunc(ctx, user)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ids.UserID) []ids.AccountID); ok {
		r0 = returnFunc(ctx, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ids.AccountID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ids.UserID) error); ok {
		r1 = returnFunc(ctx, user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Accounts_ListAccounts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAccounts'
type Accounts_ListAccounts_Call struct {
	*mock.Call
}

// ListAccounts is a helper method to define mock.On call
//   - ctx context.Context
//   - user ids.UserID
func (_e *Accounts_Expecter) ListAccounts(ctx interface{}, user interface{}) *Accounts_ListAccounts_Call {
	return &Accounts_ListAccounts_Call{Call: _e.mock.On("ListAccounts", ctx, user)}
}

func (_c *Accounts_ListAccounts_Call) Run(run func(ctx context.Context, user ids.UserID)) *Accounts_ListAccounts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ids.UserID
		if args[1] != nil {
			arg1 = args[1].(ids.UserID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Accounts_ListAccounts_Call) Return(accountIDs []ids.AccountID, err error) *Accounts_ListAccounts_Call {
	_c.Call.Return(accountIDs, err)
	return _c
}

func (_c *Accounts_ListAccounts_Call) RunAndReturn(run func(ctx context.Context, user ids.UserID) ([]ids.AccountID, error)) *Accounts_ListAccounts_Call {
	_c.Call.Return(run)
	return _c
}

// ReactivateAccount provides a mock function for the type Accounts
func (_mock *Accounts) ReactivateAccount(ctx context.Context, account ids.AccountID) error {
	ret := _mock.Called(ctx, account)

	if len(ret) == 0 {
		panic("no return value specified for ReactivateAccount")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ids.AccountID) error); ok {
		r0 = returnFunc(ctx, account)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Accounts_ReactivateAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReactivateAccount'
type Accounts_ReactivateAccount_Call struct {
	*mock.Call
}

// ReactivateAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - account ids.AccountID
func (_e *Accounts_Expecter) ReactivateAccount(ctx interface{}, account interface{}) *Accounts_ReactivateAccount_Call {
	return &Accounts_ReactivateAccount_Call{Call: _e.mock.On("ReactivateAccount", ctx, account)}
}

func (_c *Accounts_ReactivateAccount_Call) Run(run func(ctx context.Context, account ids.AccountID)) *Accounts_ReactivateAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ids.AccountID
		if args[1] != nil {
			arg1 = args[1].(ids.AccountID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Accounts_ReactivateAccount_Call) Return(err error) *Accounts_ReactivateAccount_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Accounts_ReactivateAccount_Call) RunAndReturn(run func(ctx context.Context, account ids.AccountID) error) *Accounts_ReactivateAccount_Call {
	_c.Call.Return(run)
	return _c
}

// SaveAccount provides a mock function for the type Accounts
func (_mock *Accounts) SaveAccount(ctx context.Context, info entities.AccountReadOnly) error {
	ret := _mock.Called(ctx, info)

	if len(ret) == 0 {
		panic("no return value specified for SaveAccount")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.AccountReadOnly) error); ok {
		r0 = returnFunc(ctx, info)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Accounts_SaveAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveAccount'
type Accounts_SaveAccount_Call struct {
	*mock.Call
}

// SaveAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - info entities.AccountReadOnly
func (_e *Accounts_Expecter) SaveAccount(ctx interface{}, info interface{}) *Accounts_SaveAccount_Call {
	return &Accounts_SaveAccount_Call{Call: _e.mock.On("SaveAccount", ctx, info)}
}

func (_c *Accounts_SaveAccount_Call) Run(run func(ctx context.Context, info entities.AccountReadOnly)) *Accounts_SaveAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entities.AccountReadOnly
		if args[1] != nil {
			arg1 = args[1].(entities.AccountReadOnly)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Accounts_SaveAccount_Call) Return(err error) *Accounts_SaveAccount_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Accounts_SaveAccount_Call) RunAndReturn(run func(ctx context.Context, info entities.AccountReadOnly) error) *Accounts_SaveAccount_Call {
	_c.Call.Return(run)
	return _c
}
