// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/quenbyako/cynosure/internal/domains/cynosure/entities"
	"github.com/quenbyako/cynosure/internal/domains/cynosure/types/ids"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAccountStorage creates a new instance of MockAccountStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAccountStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAccountStorage {
	mock := &MockAccountStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAccountStorage is an autogenerated mock type for the AccountStorage type
type MockAccountStorage struct {
	mock.Mock
}

type MockAccountStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAccountStorage) EXPECT() *MockAccountStorage_Expecter {
	return &MockAccountStorage_Expecter{mock: &_m.Mock}
}

// DeleteAccount provides a mock function for the type MockAccountStorage
func (_mock *MockAccountStorage) DeleteAccount(ctx context.Context, account ids.AccountID) error {
	ret := _mock.Called(ctx, account)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAccount")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ids.AccountID) error); ok {
		r0 = returnFunc(ctx, account)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAccountStorage_DeleteAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAccount'
type MockAccountStorage_DeleteAccount_Call struct {
	*mock.Call
}

// DeleteAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - account ids.AccountID
func (_e *MockAccountStorage_Expecter) DeleteAccount(ctx interface{}, account interface{}) *MockAccountStorage_DeleteAccount_Call {
	return &MockAccountStorage_DeleteAccount_Call{Call: _e.mock.On("DeleteAccount", ctx, account)}
}

func (_c *MockAccountStorage_DeleteAccount_Call) Run(run func(ctx context.Context, account ids.AccountID)) *MockAccountStorage_DeleteAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ids.AccountID
		if args[1] != nil {
			arg1 = args[1].(ids.AccountID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAccountStorage_DeleteAccount_Call) Return(err error) *MockAccountStorage_DeleteAccount_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAccountStorage_DeleteAccount_Call) RunAndReturn(run func(ctx context.Context, account ids.AccountID) error) *MockAccountStorage_DeleteAccount_Call {
	_c.Call.Return(run)
	return _c
}

// GetAccount provides a mock function for the type MockAccountStorage
func (_mock *MockAccountStorage) GetAccount(ctx context.Context, account ids.AccountID) (*entities.Account, error) {
	ret := _mock.Called(ctx, account)

	if len(ret) == 0 {
		panic("no return value specified for GetAccount")
	}

	var r0 *entities.Account
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ids.AccountID) (*entities.Account, error)); ok {
		return returnFunc(ctx, account)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ids.AccountID) *entities.Account); ok {
		r0 = returnFunc(ctx, account)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Account)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ids.AccountID) error); ok {
		r1 = returnFunc(ctx, account)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAccountStorage_GetAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccount'
type MockAccountStorage_GetAccount_Call struct {
	*mock.Call
}

// GetAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - account ids.AccountID
func (_e *MockAccountStorage_Expecter) GetAccount(ctx interface{}, account interface{}) *MockAccountStorage_GetAccount_Call {
	return &MockAccountStorage_GetAccount_Call{Call: _e.mock.On("GetAccount", ctx, account)}
}

func (_c *MockAccountStorage_GetAccount_Call) Run(run func(ctx context.Context, account ids.AccountID)) *MockAccountStorage_GetAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ids.AccountID
		if args[1] != nil {
			arg1 = args[1].(ids.AccountID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAccountStorage_GetAccount_Call) Return(account1 *entities.Account, err error) *MockAccountStorage_GetAccount_Call {
	_c.Call.Return(account1, err)
	return _c
}

func (_c *MockAccountStorage_GetAccount_Call) RunAndReturn(run func(ctx context.Context, account ids.AccountID) (*entities.Account, error)) *MockAccountStorage_GetAccount_Call {
	_c.Call.Return(run)
	return _c
}

// GetAccountsBatch provides a mock function for the type MockAccountStorage
func (_mock *MockAccountStorage) GetAccountsBatch(ctx context.Context, accounts []ids.AccountID) ([]*entities.Account, error) {
	ret := _mock.Called(ctx, accounts)

	if len(ret) == 0 {
		panic("no return value specified for GetAccountsBatch")
	}

	var r0 []*entities.Account
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []ids.AccountID) ([]*entities.Account, error)); ok {
		return returnFunc(ctx, accounts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []ids.AccountID) []*entities.Account); ok {
		r0 = returnFunc(ctx, accounts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Account)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []ids.AccountID) error); ok {
		r1 = returnFunc(ctx, accounts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAccountStorage_GetAccountsBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccountsBatch'
type MockAccountStorage_GetAccountsBatch_Call struct {
	*mock.Call
}

// GetAccountsBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - accounts []ids.AccountID
func (_e *MockAccountStorage_Expecter) GetAccountsBatch(ctx interface{}, accounts interface{}) *MockAccountStorage_GetAccountsBatch_Call {
	return &MockAccountStorage_GetAccountsBatch_Call{Call: _e.mock.On("GetAccountsBatch", ctx, accounts)}
}

func (_c *MockAccountStorage_GetAccountsBatch_Call) Run(run func(ctx context.Context, accounts []ids.AccountID)) *MockAccountStorage_GetAccountsBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []ids.AccountID
		if args[1] != nil {
			arg1 = args[1].([]ids.AccountID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAccountStorage_GetAccountsBatch_Call) Return(accounts1 []*entities.Account, err error) *MockAccountStorage_GetAccountsBatch_Call {
	_c.Call.Return(accounts1, err)
	return _c
}

func (_c *MockAccountStorage_GetAccountsBatch_Call) RunAndReturn(run func(ctx context.Context, accounts []ids.AccountID) ([]*entities.Account, error)) *MockAccountStorage_GetAccountsBatch_Call {
	_c.Call.Return(run)
	return _c
}

// ListAccounts provides a mock function for the type MockAccountStorage
func (_mock *MockAccountStorage) ListAccounts(ctx context.Context, user ids.UserID) ([]ids.AccountID, error) {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for ListAccounts")
	}

	var r0 []ids.AccountID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ids.UserID) ([]ids.AccountID, error)); ok {
		return returnFunc(ctx, user)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ids.UserID) []ids.AccountID); ok {
		r0 = returnFunc(ctx, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ids.AccountID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ids.UserID) error); ok {
		r1 = returnFunc(ctx, user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAccountStorage_ListAccounts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAccounts'
type MockAccountStorage_ListAccounts_Call struct {
	*mock.Call
}

// ListAccounts is a helper method to define mock.On call
//   - ctx context.Context
//   - user ids.UserID
func (_e *MockAccountStorage_Expecter) ListAccounts(ctx interface{}, user interface{}) *MockAccountStorage_ListAccounts_Call {
	return &MockAccountStorage_ListAccounts_Call{Call: _e.mock.On("ListAccounts", ctx, user)}
}

func (_c *MockAccountStorage_ListAccounts_Call) Run(run func(ctx context.Context, user ids.UserID)) *MockAccountStorage_ListAccounts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ids.UserID
		if args[1] != nil {
			arg1 = args[1].(ids.UserID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAccountStorage_ListAccounts_Call) Return(accountIDs []ids.AccountID, err error) *MockAccountStorage_ListAccounts_Call {
	_c.Call.Return(accountIDs, err)
	return _c
}

func (_c *MockAccountStorage_ListAccounts_Call) RunAndReturn(run func(ctx context.Context, user ids.UserID) ([]ids.AccountID, error)) *MockAccountStorage_ListAccounts_Call {
	_c.Call.Return(run)
	return _c
}

// SaveAccount provides a mock function for the type MockAccountStorage
func (_mock *MockAccountStorage) SaveAccount(ctx context.Context, info entities.AccountReadOnly) error {
	ret := _mock.Called(ctx, info)

	if len(ret) == 0 {
		panic("no return value specified for SaveAccount")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.AccountReadOnly) error); ok {
		r0 = returnFunc(ctx, info)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAccountStorage_SaveAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveAccount'
type MockAccountStorage_SaveAccount_Call struct {
	*mock.Call
}

// SaveAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - info entities.AccountReadOnly
func (_e *MockAccountStorage_Expecter) SaveAccount(ctx interface{}, info interface{}) *MockAccountStorage_SaveAccount_Call {
	return &MockAccountStorage_SaveAccount_Call{Call: _e.mock.On("SaveAccount", ctx, info)}
}

func (_c *MockAccountStorage_SaveAccount_Call) Run(run func(ctx context.Context, info entities.AccountReadOnly)) *MockAccountStorage_SaveAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entities.AccountReadOnly
		if args[1] != nil {
			arg1 = args[1].(entities.AccountReadOnly)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAccountStorage_SaveAccount_Call) Return(err error) *MockAccountStorage_SaveAccount_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAccountStorage_SaveAccount_Call) RunAndReturn(run func(ctx context.Context, info entities.AccountReadOnly) error) *MockAccountStorage_SaveAccount_Call {
	_c.Call.Return(run)
	return _c
}
