// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/quenbyako/cynosure/internal/domains/cynosure/entities"
	"github.com/quenbyako/cynosure/internal/domains/cynosure/primitives/ids"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAgentStorage creates a new instance of MockAgentStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAgentStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAgentStorage {
	mock := &MockAgentStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAgentStorage is an autogenerated mock type for the AgentStorage type
type MockAgentStorage struct {
	mock.Mock
}

type MockAgentStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAgentStorage) EXPECT() *MockAgentStorage_Expecter {
	return &MockAgentStorage_Expecter{mock: &_m.Mock}
}

// DeleteAgent provides a mock function for the type MockAgentStorage
func (_mock *MockAgentStorage) DeleteAgent(ctx context.Context, model ids.AgentID) error {
	ret := _mock.Called(ctx, model)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAgent")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ids.AgentID) error); ok {
		r0 = returnFunc(ctx, model)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAgentStorage_DeleteAgent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAgent'
type MockAgentStorage_DeleteAgent_Call struct {
	*mock.Call
}

// DeleteAgent is a helper method to define mock.On call
//   - ctx context.Context
//   - model ids.AgentID
func (_e *MockAgentStorage_Expecter) DeleteAgent(ctx interface{}, model interface{}) *MockAgentStorage_DeleteAgent_Call {
	return &MockAgentStorage_DeleteAgent_Call{Call: _e.mock.On("DeleteAgent", ctx, model)}
}

func (_c *MockAgentStorage_DeleteAgent_Call) Run(run func(ctx context.Context, model ids.AgentID)) *MockAgentStorage_DeleteAgent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ids.AgentID
		if args[1] != nil {
			arg1 = args[1].(ids.AgentID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAgentStorage_DeleteAgent_Call) Return(err error) *MockAgentStorage_DeleteAgent_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAgentStorage_DeleteAgent_Call) RunAndReturn(run func(ctx context.Context, model ids.AgentID) error) *MockAgentStorage_DeleteAgent_Call {
	_c.Call.Return(run)
	return _c
}

// GetAgent provides a mock function for the type MockAgentStorage
func (_mock *MockAgentStorage) GetAgent(ctx context.Context, model ids.AgentID) (*entities.Agent, error) {
	ret := _mock.Called(ctx, model)

	if len(ret) == 0 {
		panic("no return value specified for GetAgent")
	}

	var r0 *entities.Agent
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ids.AgentID) (*entities.Agent, error)); ok {
		return returnFunc(ctx, model)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ids.AgentID) *entities.Agent); ok {
		r0 = returnFunc(ctx, model)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Agent)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ids.AgentID) error); ok {
		r1 = returnFunc(ctx, model)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAgentStorage_GetAgent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAgent'
type MockAgentStorage_GetAgent_Call struct {
	*mock.Call
}

// GetAgent is a helper method to define mock.On call
//   - ctx context.Context
//   - model ids.AgentID
func (_e *MockAgentStorage_Expecter) GetAgent(ctx interface{}, model interface{}) *MockAgentStorage_GetAgent_Call {
	return &MockAgentStorage_GetAgent_Call{Call: _e.mock.On("GetAgent", ctx, model)}
}

func (_c *MockAgentStorage_GetAgent_Call) Run(run func(ctx context.Context, model ids.AgentID)) *MockAgentStorage_GetAgent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ids.AgentID
		if args[1] != nil {
			arg1 = args[1].(ids.AgentID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAgentStorage_GetAgent_Call) Return(agent *entities.Agent, err error) *MockAgentStorage_GetAgent_Call {
	_c.Call.Return(agent, err)
	return _c
}

func (_c *MockAgentStorage_GetAgent_Call) RunAndReturn(run func(ctx context.Context, model ids.AgentID) (*entities.Agent, error)) *MockAgentStorage_GetAgent_Call {
	_c.Call.Return(run)
	return _c
}

// ListAgents provides a mock function for the type MockAgentStorage
func (_mock *MockAgentStorage) ListAgents(ctx context.Context, user ids.UserID) ([]*entities.Agent, error) {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for ListAgents")
	}

	var r0 []*entities.Agent
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ids.UserID) ([]*entities.Agent, error)); ok {
		return returnFunc(ctx, user)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ids.UserID) []*entities.Agent); ok {
		r0 = returnFunc(ctx, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Agent)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ids.UserID) error); ok {
		r1 = returnFunc(ctx, user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAgentStorage_ListAgents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAgents'
type MockAgentStorage_ListAgents_Call struct {
	*mock.Call
}

// ListAgents is a helper method to define mock.On call
//   - ctx context.Context
//   - user ids.UserID
func (_e *MockAgentStorage_Expecter) ListAgents(ctx interface{}, user interface{}) *MockAgentStorage_ListAgents_Call {
	return &MockAgentStorage_ListAgents_Call{Call: _e.mock.On("ListAgents", ctx, user)}
}

func (_c *MockAgentStorage_ListAgents_Call) Run(run func(ctx context.Context, user ids.UserID)) *MockAgentStorage_ListAgents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ids.UserID
		if args[1] != nil {
			arg1 = args[1].(ids.UserID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAgentStorage_ListAgents_Call) Return(agents []*entities.Agent, err error) *MockAgentStorage_ListAgents_Call {
	_c.Call.Return(agents, err)
	return _c
}

func (_c *MockAgentStorage_ListAgents_Call) RunAndReturn(run func(ctx context.Context, user ids.UserID) ([]*entities.Agent, error)) *MockAgentStorage_ListAgents_Call {
	_c.Call.Return(run)
	return _c
}

// SaveAgent provides a mock function for the type MockAgentStorage
func (_mock *MockAgentStorage) SaveAgent(ctx context.Context, model entities.AgentReadOnly) error {
	ret := _mock.Called(ctx, model)

	if len(ret) == 0 {
		panic("no return value specified for SaveAgent")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.AgentReadOnly) error); ok {
		r0 = returnFunc(ctx, model)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAgentStorage_SaveAgent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveAgent'
type MockAgentStorage_SaveAgent_Call struct {
	*mock.Call
}

// SaveAgent is a helper method to define mock.On call
//   - ctx context.Context
//   - model entities.AgentReadOnly
func (_e *MockAgentStorage_Expecter) SaveAgent(ctx interface{}, model interface{}) *MockAgentStorage_SaveAgent_Call {
	return &MockAgentStorage_SaveAgent_Call{Call: _e.mock.On("SaveAgent", ctx, model)}
}

func (_c *MockAgentStorage_SaveAgent_Call) Run(run func(ctx context.Context, model entities.AgentReadOnly)) *MockAgentStorage_SaveAgent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entities.AgentReadOnly
		if args[1] != nil {
			arg1 = args[1].(entities.AgentReadOnly)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAgentStorage_SaveAgent_Call) Return(err error) *MockAgentStorage_SaveAgent_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAgentStorage_SaveAgent_Call) RunAndReturn(run func(ctx context.Context, model entities.AgentReadOnly) error) *MockAgentStorage_SaveAgent_Call {
	_c.Call.Return(run)
	return _c
}
