// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/quenbyako/cynosure/internal/domains/cynosure/entities"
	"github.com/quenbyako/cynosure/internal/domains/cynosure/ports/chatmodel"
	"github.com/quenbyako/cynosure/internal/domains/cynosure/primitives/messages"
	mock "github.com/stretchr/testify/mock"
)

// NewChatModel creates a new instance of ChatModel. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewChatModel(t interface {
	mock.TestingT
	Cleanup(func())
}) *ChatModel {
	mock := &ChatModel{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ChatModel is an autogenerated mock type for the Port type
type ChatModel struct {
	mock.Mock
}

type ChatModel_Expecter struct {
	mock *mock.Mock
}

func (_m *ChatModel) EXPECT() *ChatModel_Expecter {
	return &ChatModel_Expecter{mock: &_m.Mock}
}

// StreamWithStats provides a mock function for the type ChatModel
func (_mock *ChatModel) StreamWithStats(ctx context.Context, input []messages.Message, settings entities.AgentReadOnly, opts ...chatmodel.StreamOption) (chatmodel.Iter, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, input, settings, opts)
	} else {
		tmpRet = _mock.Called(ctx, input, settings)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for StreamWithStats")
	}

	var r0 chatmodel.Iter
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []messages.Message, entities.AgentReadOnly, ...chatmodel.StreamOption) (chatmodel.Iter, error)); ok {
		return returnFunc(ctx, input, settings, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []messages.Message, entities.AgentReadOnly, ...chatmodel.StreamOption) chatmodel.Iter); ok {
		r0 = returnFunc(ctx, input, settings, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(chatmodel.Iter)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []messages.Message, entities.AgentReadOnly, ...chatmodel.StreamOption) error); ok {
		r1 = returnFunc(ctx, input, settings, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ChatModel_StreamWithStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StreamWithStats'
type ChatModel_StreamWithStats_Call struct {
	*mock.Call
}

// StreamWithStats is a helper method to define mock.On call
//   - ctx context.Context
//   - input []messages.Message
//   - settings entities.AgentReadOnly
//   - opts ...chatmodel.StreamOption
func (_e *ChatModel_Expecter) StreamWithStats(ctx interface{}, input interface{}, settings interface{}, opts ...interface{}) *ChatModel_StreamWithStats_Call {
	return &ChatModel_StreamWithStats_Call{Call: _e.mock.On("StreamWithStats",
		append([]interface{}{ctx, input, settings}, opts...)...)}
}

func (_c *ChatModel_StreamWithStats_Call) Run(run func(ctx context.Context, input []messages.Message, settings entities.AgentReadOnly, opts ...chatmodel.StreamOption)) *ChatModel_StreamWithStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []messages.Message
		if args[1] != nil {
			arg1 = args[1].([]messages.Message)
		}
		var arg2 entities.AgentReadOnly
		if args[2] != nil {
			arg2 = args[2].(entities.AgentReadOnly)
		}
		var arg3 []chatmodel.StreamOption
		var variadicArgs []chatmodel.StreamOption
		if len(args) > 3 {
			variadicArgs = args[3].([]chatmodel.StreamOption)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *ChatModel_StreamWithStats_Call) Return(iter chatmodel.Iter, err error) *ChatModel_StreamWithStats_Call {
	_c.Call.Return(iter, err)
	return _c
}

func (_c *ChatModel_StreamWithStats_Call) RunAndReturn(run func(ctx context.Context, input []messages.Message, settings entities.AgentReadOnly, opts ...chatmodel.StreamOption) (chatmodel.Iter, error)) *ChatModel_StreamWithStats_Call {
	_c.Call.Return(run)
	return _c
}
