// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"iter"

	"github.com/quenbyako/cynosure/internal/domains/cynosure/entities"
	"github.com/quenbyako/cynosure/internal/domains/cynosure/ports"
	"github.com/quenbyako/cynosure/internal/domains/cynosure/primitives/messages"
	mock "github.com/stretchr/testify/mock"
)

// NewMockChatModel creates a new instance of MockChatModel. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChatModel(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChatModel {
	mock := &MockChatModel{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockChatModel is an autogenerated mock type for the ChatModel type
type MockChatModel struct {
	mock.Mock
}

type MockChatModel_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChatModel) EXPECT() *MockChatModel_Expecter {
	return &MockChatModel_Expecter{mock: &_m.Mock}
}

// Stream provides a mock function for the type MockChatModel
func (_mock *MockChatModel) Stream(ctx context.Context, input []messages.Message, settings entities.AgentReadOnly, opts ...ports.StreamOption) (iter.Seq2[messages.Message, error], error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, input, settings, opts)
	} else {
		tmpRet = _mock.Called(ctx, input, settings)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Stream")
	}

	var r0 iter.Seq2[messages.Message, error]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []messages.Message, entities.AgentReadOnly, ...ports.StreamOption) (iter.Seq2[messages.Message, error], error)); ok {
		return returnFunc(ctx, input, settings, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []messages.Message, entities.AgentReadOnly, ...ports.StreamOption) iter.Seq2[messages.Message, error]); ok {
		r0 = returnFunc(ctx, input, settings, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(iter.Seq2[messages.Message, error])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []messages.Message, entities.AgentReadOnly, ...ports.StreamOption) error); ok {
		r1 = returnFunc(ctx, input, settings, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChatModel_Stream_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stream'
type MockChatModel_Stream_Call struct {
	*mock.Call
}

// Stream is a helper method to define mock.On call
//   - ctx context.Context
//   - input []messages.Message
//   - settings entities.AgentReadOnly
//   - opts ...ports.StreamOption
func (_e *MockChatModel_Expecter) Stream(ctx interface{}, input interface{}, settings interface{}, opts ...interface{}) *MockChatModel_Stream_Call {
	return &MockChatModel_Stream_Call{Call: _e.mock.On("Stream",
		append([]interface{}{ctx, input, settings}, opts...)...)}
}

func (_c *MockChatModel_Stream_Call) Run(run func(ctx context.Context, input []messages.Message, settings entities.AgentReadOnly, opts ...ports.StreamOption)) *MockChatModel_Stream_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []messages.Message
		if args[1] != nil {
			arg1 = args[1].([]messages.Message)
		}
		var arg2 entities.AgentReadOnly
		if args[2] != nil {
			arg2 = args[2].(entities.AgentReadOnly)
		}
		var arg3 []ports.StreamOption
		var variadicArgs []ports.StreamOption
		if len(args) > 3 {
			variadicArgs = args[3].([]ports.StreamOption)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockChatModel_Stream_Call) Return(seq2 iter.Seq2[messages.Message, error], err error) *MockChatModel_Stream_Call {
	_c.Call.Return(seq2, err)
	return _c
}

func (_c *MockChatModel_Stream_Call) RunAndReturn(run func(ctx context.Context, input []messages.Message, settings entities.AgentReadOnly, opts ...ports.StreamOption) (iter.Seq2[messages.Message, error], error)) *MockChatModel_Stream_Call {
	_c.Call.Return(run)
	return _c
}
