// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/quenbyako/cynosure/internal/domains/cynosure/entities"
	"github.com/quenbyako/cynosure/internal/domains/cynosure/ports/embedding"
	"github.com/quenbyako/cynosure/internal/domains/cynosure/primitives/messages"
	mock "github.com/stretchr/testify/mock"
)

// NewEmbedding creates a new instance of Embedding. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEmbedding(t interface {
	mock.TestingT
	Cleanup(func())
}) *Embedding {
	mock := &Embedding{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Embedding is an autogenerated mock type for the Port type
type Embedding struct {
	mock.Mock
}

type Embedding_Expecter struct {
	mock *mock.Mock
}

func (_m *Embedding) EXPECT() *Embedding_Expecter {
	return &Embedding_Expecter{mock: &_m.Mock}
}

// BuildToolEmbedding provides a mock function for the type Embedding
func (_mock *Embedding) BuildToolEmbedding(ctx context.Context, msgs []messages.Message, opts ...embedding.BuildToolEmbeddingOption) ([1536]float32, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, msgs, opts)
	} else {
		tmpRet = _mock.Called(ctx, msgs)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for BuildToolEmbedding")
	}

	var r0 [1536]float32
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []messages.Message, ...embedding.BuildToolEmbeddingOption) ([1536]float32, error)); ok {
		return returnFunc(ctx, msgs, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []messages.Message, ...embedding.BuildToolEmbeddingOption) [1536]float32); ok {
		r0 = returnFunc(ctx, msgs, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([1536]float32)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []messages.Message, ...embedding.BuildToolEmbeddingOption) error); ok {
		r1 = returnFunc(ctx, msgs, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Embedding_BuildToolEmbedding_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BuildToolEmbedding'
type Embedding_BuildToolEmbedding_Call struct {
	*mock.Call
}

// BuildToolEmbedding is a helper method to define mock.On call
//   - ctx context.Context
//   - msgs []messages.Message
//   - opts ...embedding.BuildToolEmbeddingOption
func (_e *Embedding_Expecter) BuildToolEmbedding(ctx interface{}, msgs interface{}, opts ...interface{}) *Embedding_BuildToolEmbedding_Call {
	return &Embedding_BuildToolEmbedding_Call{Call: _e.mock.On("BuildToolEmbedding",
		append([]interface{}{ctx, msgs}, opts...)...)}
}

func (_c *Embedding_BuildToolEmbedding_Call) Run(run func(ctx context.Context, msgs []messages.Message, opts ...embedding.BuildToolEmbeddingOption)) *Embedding_BuildToolEmbedding_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []messages.Message
		if args[1] != nil {
			arg1 = args[1].([]messages.Message)
		}
		var arg2 []embedding.BuildToolEmbeddingOption
		var variadicArgs []embedding.BuildToolEmbeddingOption
		if len(args) > 2 {
			variadicArgs = args[2].([]embedding.BuildToolEmbeddingOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *Embedding_BuildToolEmbedding_Call) Return(float32s [1536]float32, err error) *Embedding_BuildToolEmbedding_Call {
	_c.Call.Return(float32s, err)
	return _c
}

func (_c *Embedding_BuildToolEmbedding_Call) RunAndReturn(run func(ctx context.Context, msgs []messages.Message, opts ...embedding.BuildToolEmbeddingOption) ([1536]float32, error)) *Embedding_BuildToolEmbedding_Call {
	_c.Call.Return(run)
	return _c
}

// IndexTool provides a mock function for the type Embedding
func (_mock *Embedding) IndexTool(ctx context.Context, tool entities.ToolReadOnly, opts ...embedding.IndexToolOption) ([1536]float32, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, tool, opts)
	} else {
		tmpRet = _mock.Called(ctx, tool)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for IndexTool")
	}

	var r0 [1536]float32
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.ToolReadOnly, ...embedding.IndexToolOption) ([1536]float32, error)); ok {
		return returnFunc(ctx, tool, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.ToolReadOnly, ...embedding.IndexToolOption) [1536]float32); ok {
		r0 = returnFunc(ctx, tool, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([1536]float32)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entities.ToolReadOnly, ...embedding.IndexToolOption) error); ok {
		r1 = returnFunc(ctx, tool, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Embedding_IndexTool_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IndexTool'
type Embedding_IndexTool_Call struct {
	*mock.Call
}

// IndexTool is a helper method to define mock.On call
//   - ctx context.Context
//   - tool entities.ToolReadOnly
//   - opts ...embedding.IndexToolOption
func (_e *Embedding_Expecter) IndexTool(ctx interface{}, tool interface{}, opts ...interface{}) *Embedding_IndexTool_Call {
	return &Embedding_IndexTool_Call{Call: _e.mock.On("IndexTool",
		append([]interface{}{ctx, tool}, opts...)...)}
}

func (_c *Embedding_IndexTool_Call) Run(run func(ctx context.Context, tool entities.ToolReadOnly, opts ...embedding.IndexToolOption)) *Embedding_IndexTool_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entities.ToolReadOnly
		if args[1] != nil {
			arg1 = args[1].(entities.ToolReadOnly)
		}
		var arg2 []embedding.IndexToolOption
		var variadicArgs []embedding.IndexToolOption
		if len(args) > 2 {
			variadicArgs = args[2].([]embedding.IndexToolOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *Embedding_IndexTool_Call) Return(float32s [1536]float32, err error) *Embedding_IndexTool_Call {
	_c.Call.Return(float32s, err)
	return _c
}

func (_c *Embedding_IndexTool_Call) RunAndReturn(run func(ctx context.Context, tool entities.ToolReadOnly, opts ...embedding.IndexToolOption) ([1536]float32, error)) *Embedding_IndexTool_Call {
	_c.Call.Return(run)
	return _c
}
