// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/quenbyako/cynosure/internal/domains/cynosure/primitives/ids"
	mock "github.com/stretchr/testify/mock"
	"golang.org/x/oauth2"
)

// NewIdentityManager creates a new instance of IdentityManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIdentityManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *IdentityManager {
	mock := &IdentityManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// IdentityManager is an autogenerated mock type for the Port type
type IdentityManager struct {
	mock.Mock
}

type IdentityManager_Expecter struct {
	mock *mock.Mock
}

func (_m *IdentityManager) EXPECT() *IdentityManager_Expecter {
	return &IdentityManager_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function for the type IdentityManager
func (_mock *IdentityManager) CreateUser(ctx context.Context, telegramID string, nickname string, firstName string, lastName string) (ids.UserID, error) {
	ret := _mock.Called(ctx, telegramID, nickname, firstName, lastName)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 ids.UserID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string) (ids.UserID, error)); ok {
		return returnFunc(ctx, telegramID, nickname, firstName, lastName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string) ids.UserID); ok {
		r0 = returnFunc(ctx, telegramID, nickname, firstName, lastName)
	} else {
		r0 = ret.Get(0).(ids.UserID)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, string) error); ok {
		r1 = returnFunc(ctx, telegramID, nickname, firstName, lastName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// IdentityManager_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type IdentityManager_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - telegramID string
//   - nickname string
//   - firstName string
//   - lastName string
func (_e *IdentityManager_Expecter) CreateUser(ctx interface{}, telegramID interface{}, nickname interface{}, firstName interface{}, lastName interface{}) *IdentityManager_CreateUser_Call {
	return &IdentityManager_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, telegramID, nickname, firstName, lastName)}
}

func (_c *IdentityManager_CreateUser_Call) Run(run func(ctx context.Context, telegramID string, nickname string, firstName string, lastName string)) *IdentityManager_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *IdentityManager_CreateUser_Call) Return(userID ids.UserID, err error) *IdentityManager_CreateUser_Call {
	_c.Call.Return(userID, err)
	return _c
}

func (_c *IdentityManager_CreateUser_Call) RunAndReturn(run func(ctx context.Context, telegramID string, nickname string, firstName string, lastName string) (ids.UserID, error)) *IdentityManager_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// HasUser provides a mock function for the type IdentityManager
func (_mock *IdentityManager) HasUser(ctx context.Context, id ids.UserID) (bool, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for HasUser")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ids.UserID) (bool, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ids.UserID) bool); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ids.UserID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// IdentityManager_HasUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasUser'
type IdentityManager_HasUser_Call struct {
	*mock.Call
}

// HasUser is a helper method to define mock.On call
//   - ctx context.Context
//   - id ids.UserID
func (_e *IdentityManager_Expecter) HasUser(ctx interface{}, id interface{}) *IdentityManager_HasUser_Call {
	return &IdentityManager_HasUser_Call{Call: _e.mock.On("HasUser", ctx, id)}
}

func (_c *IdentityManager_HasUser_Call) Run(run func(ctx context.Context, id ids.UserID)) *IdentityManager_HasUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ids.UserID
		if args[1] != nil {
			arg1 = args[1].(ids.UserID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *IdentityManager_HasUser_Call) Return(b bool, err error) *IdentityManager_HasUser_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *IdentityManager_HasUser_Call) RunAndReturn(run func(ctx context.Context, id ids.UserID) (bool, error)) *IdentityManager_HasUser_Call {
	_c.Call.Return(run)
	return _c
}

// IssueToken provides a mock function for the type IdentityManager
func (_mock *IdentityManager) IssueToken(ctx context.Context, id ids.UserID) (*oauth2.Token, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for IssueToken")
	}

	var r0 *oauth2.Token
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ids.UserID) (*oauth2.Token, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ids.UserID) *oauth2.Token); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*oauth2.Token)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ids.UserID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// IdentityManager_IssueToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IssueToken'
type IdentityManager_IssueToken_Call struct {
	*mock.Call
}

// IssueToken is a helper method to define mock.On call
//   - ctx context.Context
//   - id ids.UserID
func (_e *IdentityManager_Expecter) IssueToken(ctx interface{}, id interface{}) *IdentityManager_IssueToken_Call {
	return &IdentityManager_IssueToken_Call{Call: _e.mock.On("IssueToken", ctx, id)}
}

func (_c *IdentityManager_IssueToken_Call) Run(run func(ctx context.Context, id ids.UserID)) *IdentityManager_IssueToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ids.UserID
		if args[1] != nil {
			arg1 = args[1].(ids.UserID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *IdentityManager_IssueToken_Call) Return(token *oauth2.Token, err error) *IdentityManager_IssueToken_Call {
	_c.Call.Return(token, err)
	return _c
}

func (_c *IdentityManager_IssueToken_Call) RunAndReturn(run func(ctx context.Context, id ids.UserID) (*oauth2.Token, error)) *IdentityManager_IssueToken_Call {
	_c.Call.Return(run)
	return _c
}

// LookupUser provides a mock function for the type IdentityManager
func (_mock *IdentityManager) LookupUser(ctx context.Context, telegramID string) (ids.UserID, error) {
	ret := _mock.Called(ctx, telegramID)

	if len(ret) == 0 {
		panic("no return value specified for LookupUser")
	}

	var r0 ids.UserID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (ids.UserID, error)); ok {
		return returnFunc(ctx, telegramID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ids.UserID); ok {
		r0 = returnFunc(ctx, telegramID)
	} else {
		r0 = ret.Get(0).(ids.UserID)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, telegramID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// IdentityManager_LookupUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LookupUser'
type IdentityManager_LookupUser_Call struct {
	*mock.Call
}

// LookupUser is a helper method to define mock.On call
//   - ctx context.Context
//   - telegramID string
func (_e *IdentityManager_Expecter) LookupUser(ctx interface{}, telegramID interface{}) *IdentityManager_LookupUser_Call {
	return &IdentityManager_LookupUser_Call{Call: _e.mock.On("LookupUser", ctx, telegramID)}
}

func (_c *IdentityManager_LookupUser_Call) Run(run func(ctx context.Context, telegramID string)) *IdentityManager_LookupUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *IdentityManager_LookupUser_Call) Return(userID ids.UserID, err error) *IdentityManager_LookupUser_Call {
	_c.Call.Return(userID, err)
	return _c
}

func (_c *IdentityManager_LookupUser_Call) RunAndReturn(run func(ctx context.Context, telegramID string) (ids.UserID, error)) *IdentityManager_LookupUser_Call {
	_c.Call.Return(run)
	return _c
}
