// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/quenbyako/cynosure/internal/domains/gateway/components"
	"github.com/quenbyako/cynosure/internal/domains/gateway/components/ids"
	mock "github.com/stretchr/testify/mock"
)

// NewMockMessenger creates a new instance of MockMessenger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMessenger(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMessenger {
	mock := &MockMessenger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMessenger is an autogenerated mock type for the Messenger type
type MockMessenger struct {
	mock.Mock
}

type MockMessenger_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMessenger) EXPECT() *MockMessenger_Expecter {
	return &MockMessenger_Expecter{mock: &_m.Mock}
}

// NotifyProcessingStarted provides a mock function for the type MockMessenger
func (_mock *MockMessenger) NotifyProcessingStarted(ctx context.Context, channelID ids.ChannelID) error {
	ret := _mock.Called(ctx, channelID)

	if len(ret) == 0 {
		panic("no return value specified for NotifyProcessingStarted")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ids.ChannelID) error); ok {
		r0 = returnFunc(ctx, channelID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMessenger_NotifyProcessingStarted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NotifyProcessingStarted'
type MockMessenger_NotifyProcessingStarted_Call struct {
	*mock.Call
}

// NotifyProcessingStarted is a helper method to define mock.On call
//   - ctx context.Context
//   - channelID ids.ChannelID
func (_e *MockMessenger_Expecter) NotifyProcessingStarted(ctx interface{}, channelID interface{}) *MockMessenger_NotifyProcessingStarted_Call {
	return &MockMessenger_NotifyProcessingStarted_Call{Call: _e.mock.On("NotifyProcessingStarted", ctx, channelID)}
}

func (_c *MockMessenger_NotifyProcessingStarted_Call) Run(run func(ctx context.Context, channelID ids.ChannelID)) *MockMessenger_NotifyProcessingStarted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ids.ChannelID
		if args[1] != nil {
			arg1 = args[1].(ids.ChannelID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMessenger_NotifyProcessingStarted_Call) Return(err error) *MockMessenger_NotifyProcessingStarted_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMessenger_NotifyProcessingStarted_Call) RunAndReturn(run func(ctx context.Context, channelID ids.ChannelID) error) *MockMessenger_NotifyProcessingStarted_Call {
	_c.Call.Return(run)
	return _c
}

// SendMessage provides a mock function for the type MockMessenger
func (_mock *MockMessenger) SendMessage(ctx context.Context, channelID ids.ChannelID, text components.MessageText) (ids.MessageID, error) {
	ret := _mock.Called(ctx, channelID, text)

	if len(ret) == 0 {
		panic("no return value specified for SendMessage")
	}

	var r0 ids.MessageID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ids.ChannelID, components.MessageText) (ids.MessageID, error)); ok {
		return returnFunc(ctx, channelID, text)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ids.ChannelID, components.MessageText) ids.MessageID); ok {
		r0 = returnFunc(ctx, channelID, text)
	} else {
		r0 = ret.Get(0).(ids.MessageID)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ids.ChannelID, components.MessageText) error); ok {
		r1 = returnFunc(ctx, channelID, text)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMessenger_SendMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMessage'
type MockMessenger_SendMessage_Call struct {
	*mock.Call
}

// SendMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - channelID ids.ChannelID
//   - text components.MessageText
func (_e *MockMessenger_Expecter) SendMessage(ctx interface{}, channelID interface{}, text interface{}) *MockMessenger_SendMessage_Call {
	return &MockMessenger_SendMessage_Call{Call: _e.mock.On("SendMessage", ctx, channelID, text)}
}

func (_c *MockMessenger_SendMessage_Call) Run(run func(ctx context.Context, channelID ids.ChannelID, text components.MessageText)) *MockMessenger_SendMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ids.ChannelID
		if args[1] != nil {
			arg1 = args[1].(ids.ChannelID)
		}
		var arg2 components.MessageText
		if args[2] != nil {
			arg2 = args[2].(components.MessageText)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMessenger_SendMessage_Call) Return(messageID ids.MessageID, err error) *MockMessenger_SendMessage_Call {
	_c.Call.Return(messageID, err)
	return _c
}

func (_c *MockMessenger_SendMessage_Call) RunAndReturn(run func(ctx context.Context, channelID ids.ChannelID, text components.MessageText) (ids.MessageID, error)) *MockMessenger_SendMessage_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateMessage provides a mock function for the type MockMessenger
func (_mock *MockMessenger) UpdateMessage(ctx context.Context, messageID ids.MessageID, text components.MessageText) error {
	ret := _mock.Called(ctx, messageID, text)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMessage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ids.MessageID, components.MessageText) error); ok {
		r0 = returnFunc(ctx, messageID, text)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMessenger_UpdateMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateMessage'
type MockMessenger_UpdateMessage_Call struct {
	*mock.Call
}

// UpdateMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - messageID ids.MessageID
//   - text components.MessageText
func (_e *MockMessenger_Expecter) UpdateMessage(ctx interface{}, messageID interface{}, text interface{}) *MockMessenger_UpdateMessage_Call {
	return &MockMessenger_UpdateMessage_Call{Call: _e.mock.On("UpdateMessage", ctx, messageID, text)}
}

func (_c *MockMessenger_UpdateMessage_Call) Run(run func(ctx context.Context, messageID ids.MessageID, text components.MessageText)) *MockMessenger_UpdateMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ids.MessageID
		if args[1] != nil {
			arg1 = args[1].(ids.MessageID)
		}
		var arg2 components.MessageText
		if args[2] != nil {
			arg2 = args[2].(components.MessageText)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMessenger_UpdateMessage_Call) Return(err error) *MockMessenger_UpdateMessage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMessenger_UpdateMessage_Call) RunAndReturn(run func(ctx context.Context, messageID ids.MessageID, text components.MessageText) error) *MockMessenger_UpdateMessage_Call {
	_c.Call.Return(run)
	return _c
}
