// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"net/url"
	"time"

	"github.com/quenbyako/cynosure/internal/domains/cynosure/ports/oauthhandler"
	mock "github.com/stretchr/testify/mock"
	"golang.org/x/oauth2"
)

// NewOAuthHandler creates a new instance of OAuthHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOAuthHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *OAuthHandler {
	mock := &OAuthHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// OAuthHandler is an autogenerated mock type for the Port type
type OAuthHandler struct {
	mock.Mock
}

type OAuthHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *OAuthHandler) EXPECT() *OAuthHandler_Expecter {
	return &OAuthHandler_Expecter{mock: &_m.Mock}
}

// Exchange provides a mock function for the type OAuthHandler
func (_mock *OAuthHandler) Exchange(ctx context.Context, config *oauth2.Config, code string, verifier []byte) (*oauth2.Token, error) {
	ret := _mock.Called(ctx, config, code, verifier)

	if len(ret) == 0 {
		panic("no return value specified for Exchange")
	}

	var r0 *oauth2.Token
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *oauth2.Config, string, []byte) (*oauth2.Token, error)); ok {
		return returnFunc(ctx, config, code, verifier)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *oauth2.Config, string, []byte) *oauth2.Token); ok {
		r0 = returnFunc(ctx, config, code, verifier)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*oauth2.Token)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *oauth2.Config, string, []byte) error); ok {
		r1 = returnFunc(ctx, config, code, verifier)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OAuthHandler_Exchange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exchange'
type OAuthHandler_Exchange_Call struct {
	*mock.Call
}

// Exchange is a helper method to define mock.On call
//   - ctx context.Context
//   - config *oauth2.Config
//   - code string
//   - verifier []byte
func (_e *OAuthHandler_Expecter) Exchange(ctx interface{}, config interface{}, code interface{}, verifier interface{}) *OAuthHandler_Exchange_Call {
	return &OAuthHandler_Exchange_Call{Call: _e.mock.On("Exchange", ctx, config, code, verifier)}
}

func (_c *OAuthHandler_Exchange_Call) Run(run func(ctx context.Context, config *oauth2.Config, code string, verifier []byte)) *OAuthHandler_Exchange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *oauth2.Config
		if args[1] != nil {
			arg1 = args[1].(*oauth2.Config)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []byte
		if args[3] != nil {
			arg3 = args[3].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *OAuthHandler_Exchange_Call) Return(token *oauth2.Token, err error) *OAuthHandler_Exchange_Call {
	_c.Call.Return(token, err)
	return _c
}

func (_c *OAuthHandler_Exchange_Call) RunAndReturn(run func(ctx context.Context, config *oauth2.Config, code string, verifier []byte) (*oauth2.Token, error)) *OAuthHandler_Exchange_Call {
	_c.Call.Return(run)
	return _c
}

// RefreshToken provides a mock function for the type OAuthHandler
func (_mock *OAuthHandler) RefreshToken(ctx context.Context, config *oauth2.Config, token *oauth2.Token) (*oauth2.Token, error) {
	ret := _mock.Called(ctx, config, token)

	if len(ret) == 0 {
		panic("no return value specified for RefreshToken")
	}

	var r0 *oauth2.Token
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *oauth2.Config, *oauth2.Token) (*oauth2.Token, error)); ok {
		return returnFunc(ctx, config, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *oauth2.Config, *oauth2.Token) *oauth2.Token); ok {
		r0 = returnFunc(ctx, config, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*oauth2.Token)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *oauth2.Config, *oauth2.Token) error); ok {
		r1 = returnFunc(ctx, config, token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OAuthHandler_RefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefreshToken'
type OAuthHandler_RefreshToken_Call struct {
	*mock.Call
}

// RefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - config *oauth2.Config
//   - token *oauth2.Token
func (_e *OAuthHandler_Expecter) RefreshToken(ctx interface{}, config interface{}, token interface{}) *OAuthHandler_RefreshToken_Call {
	return &OAuthHandler_RefreshToken_Call{Call: _e.mock.On("RefreshToken", ctx, config, token)}
}

func (_c *OAuthHandler_RefreshToken_Call) Run(run func(ctx context.Context, config *oauth2.Config, token *oauth2.Token)) *OAuthHandler_RefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *oauth2.Config
		if args[1] != nil {
			arg1 = args[1].(*oauth2.Config)
		}
		var arg2 *oauth2.Token
		if args[2] != nil {
			arg2 = args[2].(*oauth2.Token)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *OAuthHandler_RefreshToken_Call) Return(token1 *oauth2.Token, err error) *OAuthHandler_RefreshToken_Call {
	_c.Call.Return(token1, err)
	return _c
}

func (_c *OAuthHandler_RefreshToken_Call) RunAndReturn(run func(ctx context.Context, config *oauth2.Config, token *oauth2.Token) (*oauth2.Token, error)) *OAuthHandler_RefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterClient provides a mock function for the type OAuthHandler
func (_mock *OAuthHandler) RegisterClient(ctx context.Context, resourceURL *url.URL, clientName string, setRedirect *url.URL, opts ...oauthhandler.RegisterClientOption) (*oauth2.Config, time.Time, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, resourceURL, clientName, setRedirect, opts)
	} else {
		tmpRet = _mock.Called(ctx, resourceURL, clientName, setRedirect)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for RegisterClient")
	}

	var r0 *oauth2.Config
	var r1 time.Time
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *url.URL, string, *url.URL, ...oauthhandler.RegisterClientOption) (*oauth2.Config, time.Time, error)); ok {
		return returnFunc(ctx, resourceURL, clientName, setRedirect, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *url.URL, string, *url.URL, ...oauthhandler.RegisterClientOption) *oauth2.Config); ok {
		r0 = returnFunc(ctx, resourceURL, clientName, setRedirect, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*oauth2.Config)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *url.URL, string, *url.URL, ...oauthhandler.RegisterClientOption) time.Time); ok {
		r1 = returnFunc(ctx, resourceURL, clientName, setRedirect, opts...)
	} else {
		r1 = ret.Get(1).(time.Time)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, *url.URL, string, *url.URL, ...oauthhandler.RegisterClientOption) error); ok {
		r2 = returnFunc(ctx, resourceURL, clientName, setRedirect, opts...)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// OAuthHandler_RegisterClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterClient'
type OAuthHandler_RegisterClient_Call struct {
	*mock.Call
}

// RegisterClient is a helper method to define mock.On call
//   - ctx context.Context
//   - resourceURL *url.URL
//   - clientName string
//   - setRedirect *url.URL
//   - opts ...oauthhandler.RegisterClientOption
func (_e *OAuthHandler_Expecter) RegisterClient(ctx interface{}, resourceURL interface{}, clientName interface{}, setRedirect interface{}, opts ...interface{}) *OAuthHandler_RegisterClient_Call {
	return &OAuthHandler_RegisterClient_Call{Call: _e.mock.On("RegisterClient",
		append([]interface{}{ctx, resourceURL, clientName, setRedirect}, opts...)...)}
}

func (_c *OAuthHandler_RegisterClient_Call) Run(run func(ctx context.Context, resourceURL *url.URL, clientName string, setRedirect *url.URL, opts ...oauthhandler.RegisterClientOption)) *OAuthHandler_RegisterClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *url.URL
		if args[1] != nil {
			arg1 = args[1].(*url.URL)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 *url.URL
		if args[3] != nil {
			arg3 = args[3].(*url.URL)
		}
		var arg4 []oauthhandler.RegisterClientOption
		var variadicArgs []oauthhandler.RegisterClientOption
		if len(args) > 4 {
			variadicArgs = args[4].([]oauthhandler.RegisterClientOption)
		}
		arg4 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4...,
		)
	})
	return _c
}

func (_c *OAuthHandler_RegisterClient_Call) Return(cfg *oauth2.Config, expiresAt time.Time, err error) *OAuthHandler_RegisterClient_Call {
	_c.Call.Return(cfg, expiresAt, err)
	return _c
}

func (_c *OAuthHandler_RegisterClient_Call) RunAndReturn(run func(ctx context.Context, resourceURL *url.URL, clientName string, setRedirect *url.URL, opts ...oauthhandler.RegisterClientOption) (*oauth2.Config, time.Time, error)) *OAuthHandler_RegisterClient_Call {
	_c.Call.Return(run)
	return _c
}
