// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/quenbyako/cynosure/internal/domains/cynosure/ports/ratelimiter"
	"github.com/quenbyako/cynosure/internal/domains/cynosure/primitives/ids"
	mock "github.com/stretchr/testify/mock"
)

// NewRateLimiter creates a new instance of RateLimiter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRateLimiter(t interface {
	mock.TestingT
	Cleanup(func())
}) *RateLimiter {
	mock := &RateLimiter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// RateLimiter is an autogenerated mock type for the Port type
type RateLimiter struct {
	mock.Mock
}

type RateLimiter_Expecter struct {
	mock *mock.Mock
}

func (_m *RateLimiter) EXPECT() *RateLimiter_Expecter {
	return &RateLimiter_Expecter{mock: &_m.Mock}
}

// ConsumeChatRequests provides a mock function for the type RateLimiter
func (_mock *RateLimiter) ConsumeChatRequests(ctx context.Context, user ids.UserID, model string, inputTokens int) (ratelimiter.ConsumedTokensFunc, error) {
	ret := _mock.Called(ctx, user, model, inputTokens)

	if len(ret) == 0 {
		panic("no return value specified for ConsumeChatRequests")
	}

	var r0 ratelimiter.ConsumedTokensFunc
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ids.UserID, string, int) (ratelimiter.ConsumedTokensFunc, error)); ok {
		return returnFunc(ctx, user, model, inputTokens)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ids.UserID, string, int) ratelimiter.ConsumedTokensFunc); ok {
		r0 = returnFunc(ctx, user, model, inputTokens)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ratelimiter.ConsumedTokensFunc)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ids.UserID, string, int) error); ok {
		r1 = returnFunc(ctx, user, model, inputTokens)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RateLimiter_ConsumeChatRequests_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConsumeChatRequests'
type RateLimiter_ConsumeChatRequests_Call struct {
	*mock.Call
}

// ConsumeChatRequests is a helper method to define mock.On call
//   - ctx context.Context
//   - user ids.UserID
//   - model string
//   - inputTokens int
func (_e *RateLimiter_Expecter) ConsumeChatRequests(ctx interface{}, user interface{}, model interface{}, inputTokens interface{}) *RateLimiter_ConsumeChatRequests_Call {
	return &RateLimiter_ConsumeChatRequests_Call{Call: _e.mock.On("ConsumeChatRequests", ctx, user, model, inputTokens)}
}

func (_c *RateLimiter_ConsumeChatRequests_Call) Run(run func(ctx context.Context, user ids.UserID, model string, inputTokens int)) *RateLimiter_ConsumeChatRequests_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ids.UserID
		if args[1] != nil {
			arg1 = args[1].(ids.UserID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *RateLimiter_ConsumeChatRequests_Call) Return(consumedTokensFunc ratelimiter.ConsumedTokensFunc, err error) *RateLimiter_ConsumeChatRequests_Call {
	_c.Call.Return(consumedTokensFunc, err)
	return _c
}

func (_c *RateLimiter_ConsumeChatRequests_Call) RunAndReturn(run func(ctx context.Context, user ids.UserID, model string, inputTokens int) (ratelimiter.ConsumedTokensFunc, error)) *RateLimiter_ConsumeChatRequests_Call {
	_c.Call.Return(run)
	return _c
}

// ConsumeEmbeddingRequests provides a mock function for the type RateLimiter
func (_mock *RateLimiter) ConsumeEmbeddingRequests(ctx context.Context, user ids.UserID, model string, inputTokens int) error {
	ret := _mock.Called(ctx, user, model, inputTokens)

	if len(ret) == 0 {
		panic("no return value specified for ConsumeEmbeddingRequests")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ids.UserID, string, int) error); ok {
		r0 = returnFunc(ctx, user, model, inputTokens)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// RateLimiter_ConsumeEmbeddingRequests_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConsumeEmbeddingRequests'
type RateLimiter_ConsumeEmbeddingRequests_Call struct {
	*mock.Call
}

// ConsumeEmbeddingRequests is a helper method to define mock.On call
//   - ctx context.Context
//   - user ids.UserID
//   - model string
//   - inputTokens int
func (_e *RateLimiter_Expecter) ConsumeEmbeddingRequests(ctx interface{}, user interface{}, model interface{}, inputTokens interface{}) *RateLimiter_ConsumeEmbeddingRequests_Call {
	return &RateLimiter_ConsumeEmbeddingRequests_Call{Call: _e.mock.On("ConsumeEmbeddingRequests", ctx, user, model, inputTokens)}
}

func (_c *RateLimiter_ConsumeEmbeddingRequests_Call) Run(run func(ctx context.Context, user ids.UserID, model string, inputTokens int)) *RateLimiter_ConsumeEmbeddingRequests_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ids.UserID
		if args[1] != nil {
			arg1 = args[1].(ids.UserID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *RateLimiter_ConsumeEmbeddingRequests_Call) Return(err error) *RateLimiter_ConsumeEmbeddingRequests_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *RateLimiter_ConsumeEmbeddingRequests_Call) RunAndReturn(run func(ctx context.Context, user ids.UserID, model string, inputTokens int) error) *RateLimiter_ConsumeEmbeddingRequests_Call {
	_c.Call.Return(run)
	return _c
}
