// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"net/url"

	"github.com/quenbyako/cynosure/internal/domains/cynosure/ports"
	"github.com/quenbyako/cynosure/internal/domains/cynosure/types/ids"
	mock "github.com/stretchr/testify/mock"
)

// NewMockServerStorage creates a new instance of MockServerStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockServerStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockServerStorage {
	mock := &MockServerStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockServerStorage is an autogenerated mock type for the ServerStorage type
type MockServerStorage struct {
	mock.Mock
}

type MockServerStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockServerStorage) EXPECT() *MockServerStorage_Expecter {
	return &MockServerStorage_Expecter{mock: &_m.Mock}
}

// AddServer provides a mock function for the type MockServerStorage
func (_mock *MockServerStorage) AddServer(ctx context.Context, name ids.ServerID, info ports.ServerInfo) error {
	ret := _mock.Called(ctx, name, info)

	if len(ret) == 0 {
		panic("no return value specified for AddServer")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ids.ServerID, ports.ServerInfo) error); ok {
		r0 = returnFunc(ctx, name, info)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockServerStorage_AddServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddServer'
type MockServerStorage_AddServer_Call struct {
	*mock.Call
}

// AddServer is a helper method to define mock.On call
//   - ctx context.Context
//   - name ids.ServerID
//   - info ports.ServerInfo
func (_e *MockServerStorage_Expecter) AddServer(ctx interface{}, name interface{}, info interface{}) *MockServerStorage_AddServer_Call {
	return &MockServerStorage_AddServer_Call{Call: _e.mock.On("AddServer", ctx, name, info)}
}

func (_c *MockServerStorage_AddServer_Call) Run(run func(ctx context.Context, name ids.ServerID, info ports.ServerInfo)) *MockServerStorage_AddServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ids.ServerID
		if args[1] != nil {
			arg1 = args[1].(ids.ServerID)
		}
		var arg2 ports.ServerInfo
		if args[2] != nil {
			arg2 = args[2].(ports.ServerInfo)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockServerStorage_AddServer_Call) Return(err error) *MockServerStorage_AddServer_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockServerStorage_AddServer_Call) RunAndReturn(run func(ctx context.Context, name ids.ServerID, info ports.ServerInfo) error) *MockServerStorage_AddServer_Call {
	_c.Call.Return(run)
	return _c
}

// GetServerInfo provides a mock function for the type MockServerStorage
func (_mock *MockServerStorage) GetServerInfo(ctx context.Context, name ids.ServerID) (*ports.ServerInfo, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetServerInfo")
	}

	var r0 *ports.ServerInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ids.ServerID) (*ports.ServerInfo, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ids.ServerID) *ports.ServerInfo); ok {
		r0 = returnFunc(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ports.ServerInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ids.ServerID) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockServerStorage_GetServerInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetServerInfo'
type MockServerStorage_GetServerInfo_Call struct {
	*mock.Call
}

// GetServerInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - name ids.ServerID
func (_e *MockServerStorage_Expecter) GetServerInfo(ctx interface{}, name interface{}) *MockServerStorage_GetServerInfo_Call {
	return &MockServerStorage_GetServerInfo_Call{Call: _e.mock.On("GetServerInfo", ctx, name)}
}

func (_c *MockServerStorage_GetServerInfo_Call) Run(run func(ctx context.Context, name ids.ServerID)) *MockServerStorage_GetServerInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ids.ServerID
		if args[1] != nil {
			arg1 = args[1].(ids.ServerID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockServerStorage_GetServerInfo_Call) Return(serverInfo *ports.ServerInfo, err error) *MockServerStorage_GetServerInfo_Call {
	_c.Call.Return(serverInfo, err)
	return _c
}

func (_c *MockServerStorage_GetServerInfo_Call) RunAndReturn(run func(ctx context.Context, name ids.ServerID) (*ports.ServerInfo, error)) *MockServerStorage_GetServerInfo_Call {
	_c.Call.Return(run)
	return _c
}

// ListServers provides a mock function for the type MockServerStorage
func (_mock *MockServerStorage) ListServers(ctx context.Context, limit uint, token string) (map[ids.ServerID]ports.ServerInfo, string, error) {
	ret := _mock.Called(ctx, limit, token)

	if len(ret) == 0 {
		panic("no return value specified for ListServers")
	}

	var r0 map[ids.ServerID]ports.ServerInfo
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, string) (map[ids.ServerID]ports.ServerInfo, string, error)); ok {
		return returnFunc(ctx, limit, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, string) map[ids.ServerID]ports.ServerInfo); ok {
		r0 = returnFunc(ctx, limit, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[ids.ServerID]ports.ServerInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint, string) string); ok {
		r1 = returnFunc(ctx, limit, token)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, uint, string) error); ok {
		r2 = returnFunc(ctx, limit, token)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockServerStorage_ListServers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListServers'
type MockServerStorage_ListServers_Call struct {
	*mock.Call
}

// ListServers is a helper method to define mock.On call
//   - ctx context.Context
//   - limit uint
//   - token string
func (_e *MockServerStorage_Expecter) ListServers(ctx interface{}, limit interface{}, token interface{}) *MockServerStorage_ListServers_Call {
	return &MockServerStorage_ListServers_Call{Call: _e.mock.On("ListServers", ctx, limit, token)}
}

func (_c *MockServerStorage_ListServers_Call) Run(run func(ctx context.Context, limit uint, token string)) *MockServerStorage_ListServers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockServerStorage_ListServers_Call) Return(m map[ids.ServerID]ports.ServerInfo, nextToken string, err error) *MockServerStorage_ListServers_Call {
	_c.Call.Return(m, nextToken, err)
	return _c
}

func (_c *MockServerStorage_ListServers_Call) RunAndReturn(run func(ctx context.Context, limit uint, token string) (map[ids.ServerID]ports.ServerInfo, string, error)) *MockServerStorage_ListServers_Call {
	_c.Call.Return(run)
	return _c
}

// LookupByURL provides a mock function for the type MockServerStorage
func (_mock *MockServerStorage) LookupByURL(ctx context.Context, url1 *url.URL) (ids.ServerID, ports.ServerInfo, error) {
	ret := _mock.Called(ctx, url1)

	if len(ret) == 0 {
		panic("no return value specified for LookupByURL")
	}

	var r0 ids.ServerID
	var r1 ports.ServerInfo
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *url.URL) (ids.ServerID, ports.ServerInfo, error)); ok {
		return returnFunc(ctx, url1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *url.URL) ids.ServerID); ok {
		r0 = returnFunc(ctx, url1)
	} else {
		r0 = ret.Get(0).(ids.ServerID)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *url.URL) ports.ServerInfo); ok {
		r1 = returnFunc(ctx, url1)
	} else {
		r1 = ret.Get(1).(ports.ServerInfo)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, *url.URL) error); ok {
		r2 = returnFunc(ctx, url1)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockServerStorage_LookupByURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LookupByURL'
type MockServerStorage_LookupByURL_Call struct {
	*mock.Call
}

// LookupByURL is a helper method to define mock.On call
//   - ctx context.Context
//   - url1 *url.URL
func (_e *MockServerStorage_Expecter) LookupByURL(ctx interface{}, url1 interface{}) *MockServerStorage_LookupByURL_Call {
	return &MockServerStorage_LookupByURL_Call{Call: _e.mock.On("LookupByURL", ctx, url1)}
}

func (_c *MockServerStorage_LookupByURL_Call) Run(run func(ctx context.Context, url1 *url.URL)) *MockServerStorage_LookupByURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *url.URL
		if args[1] != nil {
			arg1 = args[1].(*url.URL)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockServerStorage_LookupByURL_Call) Return(serverID ids.ServerID, serverInfo ports.ServerInfo, err error) *MockServerStorage_LookupByURL_Call {
	_c.Call.Return(serverID, serverInfo, err)
	return _c
}

func (_c *MockServerStorage_LookupByURL_Call) RunAndReturn(run func(ctx context.Context, url1 *url.URL) (ids.ServerID, ports.ServerInfo, error)) *MockServerStorage_LookupByURL_Call {
	_c.Call.Return(run)
	return _c
}
