// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"net/url"

	"github.com/quenbyako/cynosure/internal/domains/cynosure/entities"
	"github.com/quenbyako/cynosure/internal/domains/cynosure/primitives/ids"
	mock "github.com/stretchr/testify/mock"
)

// NewMockServerStorage creates a new instance of MockServerStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockServerStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockServerStorage {
	mock := &MockServerStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockServerStorage is an autogenerated mock type for the ServerStorage type
type MockServerStorage struct {
	mock.Mock
}

type MockServerStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockServerStorage) EXPECT() *MockServerStorage_Expecter {
	return &MockServerStorage_Expecter{mock: &_m.Mock}
}

// DeleteServer provides a mock function for the type MockServerStorage
func (_mock *MockServerStorage) DeleteServer(ctx context.Context, id ids.ServerID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteServer")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ids.ServerID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockServerStorage_DeleteServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteServer'
type MockServerStorage_DeleteServer_Call struct {
	*mock.Call
}

// DeleteServer is a helper method to define mock.On call
//   - ctx context.Context
//   - id ids.ServerID
func (_e *MockServerStorage_Expecter) DeleteServer(ctx interface{}, id interface{}) *MockServerStorage_DeleteServer_Call {
	return &MockServerStorage_DeleteServer_Call{Call: _e.mock.On("DeleteServer", ctx, id)}
}

func (_c *MockServerStorage_DeleteServer_Call) Run(run func(ctx context.Context, id ids.ServerID)) *MockServerStorage_DeleteServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ids.ServerID
		if args[1] != nil {
			arg1 = args[1].(ids.ServerID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockServerStorage_DeleteServer_Call) Return(err error) *MockServerStorage_DeleteServer_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockServerStorage_DeleteServer_Call) RunAndReturn(run func(ctx context.Context, id ids.ServerID) error) *MockServerStorage_DeleteServer_Call {
	_c.Call.Return(run)
	return _c
}

// GetServerInfo provides a mock function for the type MockServerStorage
func (_mock *MockServerStorage) GetServerInfo(ctx context.Context, name ids.ServerID) (*entities.ServerConfig, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetServerInfo")
	}

	var r0 *entities.ServerConfig
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ids.ServerID) (*entities.ServerConfig, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ids.ServerID) *entities.ServerConfig); ok {
		r0 = returnFunc(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.ServerConfig)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ids.ServerID) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockServerStorage_GetServerInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetServerInfo'
type MockServerStorage_GetServerInfo_Call struct {
	*mock.Call
}

// GetServerInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - name ids.ServerID
func (_e *MockServerStorage_Expecter) GetServerInfo(ctx interface{}, name interface{}) *MockServerStorage_GetServerInfo_Call {
	return &MockServerStorage_GetServerInfo_Call{Call: _e.mock.On("GetServerInfo", ctx, name)}
}

func (_c *MockServerStorage_GetServerInfo_Call) Run(run func(ctx context.Context, name ids.ServerID)) *MockServerStorage_GetServerInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ids.ServerID
		if args[1] != nil {
			arg1 = args[1].(ids.ServerID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockServerStorage_GetServerInfo_Call) Return(serverConfig *entities.ServerConfig, err error) *MockServerStorage_GetServerInfo_Call {
	_c.Call.Return(serverConfig, err)
	return _c
}

func (_c *MockServerStorage_GetServerInfo_Call) RunAndReturn(run func(ctx context.Context, name ids.ServerID) (*entities.ServerConfig, error)) *MockServerStorage_GetServerInfo_Call {
	_c.Call.Return(run)
	return _c
}

// ListServers provides a mock function for the type MockServerStorage
func (_mock *MockServerStorage) ListServers(ctx context.Context) ([]*entities.ServerConfig, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListServers")
	}

	var r0 []*entities.ServerConfig
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*entities.ServerConfig, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*entities.ServerConfig); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.ServerConfig)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockServerStorage_ListServers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListServers'
type MockServerStorage_ListServers_Call struct {
	*mock.Call
}

// ListServers is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockServerStorage_Expecter) ListServers(ctx interface{}) *MockServerStorage_ListServers_Call {
	return &MockServerStorage_ListServers_Call{Call: _e.mock.On("ListServers", ctx)}
}

func (_c *MockServerStorage_ListServers_Call) Run(run func(ctx context.Context)) *MockServerStorage_ListServers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockServerStorage_ListServers_Call) Return(m []*entities.ServerConfig, err error) *MockServerStorage_ListServers_Call {
	_c.Call.Return(m, err)
	return _c
}

func (_c *MockServerStorage_ListServers_Call) RunAndReturn(run func(ctx context.Context) ([]*entities.ServerConfig, error)) *MockServerStorage_ListServers_Call {
	_c.Call.Return(run)
	return _c
}

// LookupByURL provides a mock function for the type MockServerStorage
func (_mock *MockServerStorage) LookupByURL(ctx context.Context, url1 *url.URL) (*entities.ServerConfig, error) {
	ret := _mock.Called(ctx, url1)

	if len(ret) == 0 {
		panic("no return value specified for LookupByURL")
	}

	var r0 *entities.ServerConfig
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *url.URL) (*entities.ServerConfig, error)); ok {
		return returnFunc(ctx, url1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *url.URL) *entities.ServerConfig); ok {
		r0 = returnFunc(ctx, url1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.ServerConfig)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *url.URL) error); ok {
		r1 = returnFunc(ctx, url1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockServerStorage_LookupByURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LookupByURL'
type MockServerStorage_LookupByURL_Call struct {
	*mock.Call
}

// LookupByURL is a helper method to define mock.On call
//   - ctx context.Context
//   - url1 *url.URL
func (_e *MockServerStorage_Expecter) LookupByURL(ctx interface{}, url1 interface{}) *MockServerStorage_LookupByURL_Call {
	return &MockServerStorage_LookupByURL_Call{Call: _e.mock.On("LookupByURL", ctx, url1)}
}

func (_c *MockServerStorage_LookupByURL_Call) Run(run func(ctx context.Context, url1 *url.URL)) *MockServerStorage_LookupByURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *url.URL
		if args[1] != nil {
			arg1 = args[1].(*url.URL)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockServerStorage_LookupByURL_Call) Return(serverConfig *entities.ServerConfig, err error) *MockServerStorage_LookupByURL_Call {
	_c.Call.Return(serverConfig, err)
	return _c
}

func (_c *MockServerStorage_LookupByURL_Call) RunAndReturn(run func(ctx context.Context, url1 *url.URL) (*entities.ServerConfig, error)) *MockServerStorage_LookupByURL_Call {
	_c.Call.Return(run)
	return _c
}

// SetServer provides a mock function for the type MockServerStorage
func (_mock *MockServerStorage) SetServer(ctx context.Context, config entities.ServerConfigReadOnly) error {
	ret := _mock.Called(ctx, config)

	if len(ret) == 0 {
		panic("no return value specified for SetServer")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.ServerConfigReadOnly) error); ok {
		r0 = returnFunc(ctx, config)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockServerStorage_SetServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetServer'
type MockServerStorage_SetServer_Call struct {
	*mock.Call
}

// SetServer is a helper method to define mock.On call
//   - ctx context.Context
//   - config entities.ServerConfigReadOnly
func (_e *MockServerStorage_Expecter) SetServer(ctx interface{}, config interface{}) *MockServerStorage_SetServer_Call {
	return &MockServerStorage_SetServer_Call{Call: _e.mock.On("SetServer", ctx, config)}
}

func (_c *MockServerStorage_SetServer_Call) Run(run func(ctx context.Context, config entities.ServerConfigReadOnly)) *MockServerStorage_SetServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entities.ServerConfigReadOnly
		if args[1] != nil {
			arg1 = args[1].(entities.ServerConfigReadOnly)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockServerStorage_SetServer_Call) Return(err error) *MockServerStorage_SetServer_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockServerStorage_SetServer_Call) RunAndReturn(run func(ctx context.Context, config entities.ServerConfigReadOnly) error) *MockServerStorage_SetServer_Call {
	_c.Call.Return(run)
	return _c
}
