// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/quenbyako/cynosure/internal/domains/cynosure/entities"
	"github.com/quenbyako/cynosure/internal/domains/cynosure/types/ids"
	mock "github.com/stretchr/testify/mock"
)

// NewMockStorageRepository creates a new instance of MockStorageRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorageRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorageRepository {
	mock := &MockStorageRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStorageRepository is an autogenerated mock type for the StorageRepository type
type MockStorageRepository struct {
	mock.Mock
}

type MockStorageRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorageRepository) EXPECT() *MockStorageRepository_Expecter {
	return &MockStorageRepository_Expecter{mock: &_m.Mock}
}

// CreateThread provides a mock function for the type MockStorageRepository
func (_mock *MockStorageRepository) CreateThread(ctx context.Context, thread entities.ChatHistoryReadOnly) error {
	ret := _mock.Called(ctx, thread)

	if len(ret) == 0 {
		panic("no return value specified for CreateThread")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.ChatHistoryReadOnly) error); ok {
		r0 = returnFunc(ctx, thread)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorageRepository_CreateThread_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateThread'
type MockStorageRepository_CreateThread_Call struct {
	*mock.Call
}

// CreateThread is a helper method to define mock.On call
//   - ctx context.Context
//   - thread entities.ChatHistoryReadOnly
func (_e *MockStorageRepository_Expecter) CreateThread(ctx interface{}, thread interface{}) *MockStorageRepository_CreateThread_Call {
	return &MockStorageRepository_CreateThread_Call{Call: _e.mock.On("CreateThread", ctx, thread)}
}

func (_c *MockStorageRepository_CreateThread_Call) Run(run func(ctx context.Context, thread entities.ChatHistoryReadOnly)) *MockStorageRepository_CreateThread_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entities.ChatHistoryReadOnly
		if args[1] != nil {
			arg1 = args[1].(entities.ChatHistoryReadOnly)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorageRepository_CreateThread_Call) Return(err error) *MockStorageRepository_CreateThread_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorageRepository_CreateThread_Call) RunAndReturn(run func(ctx context.Context, thread entities.ChatHistoryReadOnly) error) *MockStorageRepository_CreateThread_Call {
	_c.Call.Return(run)
	return _c
}

// GetThread provides a mock function for the type MockStorageRepository
func (_mock *MockStorageRepository) GetThread(ctx context.Context, user ids.UserID, threadID string) (*entities.ChatHistory, error) {
	ret := _mock.Called(ctx, user, threadID)

	if len(ret) == 0 {
		panic("no return value specified for GetThread")
	}

	var r0 *entities.ChatHistory
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ids.UserID, string) (*entities.ChatHistory, error)); ok {
		return returnFunc(ctx, user, threadID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ids.UserID, string) *entities.ChatHistory); ok {
		r0 = returnFunc(ctx, user, threadID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.ChatHistory)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ids.UserID, string) error); ok {
		r1 = returnFunc(ctx, user, threadID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorageRepository_GetThread_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetThread'
type MockStorageRepository_GetThread_Call struct {
	*mock.Call
}

// GetThread is a helper method to define mock.On call
//   - ctx context.Context
//   - user ids.UserID
//   - threadID string
func (_e *MockStorageRepository_Expecter) GetThread(ctx interface{}, user interface{}, threadID interface{}) *MockStorageRepository_GetThread_Call {
	return &MockStorageRepository_GetThread_Call{Call: _e.mock.On("GetThread", ctx, user, threadID)}
}

func (_c *MockStorageRepository_GetThread_Call) Run(run func(ctx context.Context, user ids.UserID, threadID string)) *MockStorageRepository_GetThread_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ids.UserID
		if args[1] != nil {
			arg1 = args[1].(ids.UserID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStorageRepository_GetThread_Call) Return(chatHistory *entities.ChatHistory, err error) *MockStorageRepository_GetThread_Call {
	_c.Call.Return(chatHistory, err)
	return _c
}

func (_c *MockStorageRepository_GetThread_Call) RunAndReturn(run func(ctx context.Context, user ids.UserID, threadID string) (*entities.ChatHistory, error)) *MockStorageRepository_GetThread_Call {
	_c.Call.Return(run)
	return _c
}

// SaveThread provides a mock function for the type MockStorageRepository
func (_mock *MockStorageRepository) SaveThread(ctx context.Context, thread entities.ChatHistoryReadOnly) error {
	ret := _mock.Called(ctx, thread)

	if len(ret) == 0 {
		panic("no return value specified for SaveThread")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.ChatHistoryReadOnly) error); ok {
		r0 = returnFunc(ctx, thread)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorageRepository_SaveThread_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveThread'
type MockStorageRepository_SaveThread_Call struct {
	*mock.Call
}

// SaveThread is a helper method to define mock.On call
//   - ctx context.Context
//   - thread entities.ChatHistoryReadOnly
func (_e *MockStorageRepository_Expecter) SaveThread(ctx interface{}, thread interface{}) *MockStorageRepository_SaveThread_Call {
	return &MockStorageRepository_SaveThread_Call{Call: _e.mock.On("SaveThread", ctx, thread)}
}

func (_c *MockStorageRepository_SaveThread_Call) Run(run func(ctx context.Context, thread entities.ChatHistoryReadOnly)) *MockStorageRepository_SaveThread_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entities.ChatHistoryReadOnly
		if args[1] != nil {
			arg1 = args[1].(entities.ChatHistoryReadOnly)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorageRepository_SaveThread_Call) Return(err error) *MockStorageRepository_SaveThread_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorageRepository_SaveThread_Call) RunAndReturn(run func(ctx context.Context, thread entities.ChatHistoryReadOnly) error) *MockStorageRepository_SaveThread_Call {
	_c.Call.Return(run)
	return _c
}
