// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/quenbyako/cynosure/internal/domains/cynosure/entities"
	"github.com/quenbyako/cynosure/internal/domains/cynosure/primitives/ids"
	mock "github.com/stretchr/testify/mock"
)

// NewMockThreadStorage creates a new instance of MockThreadStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockThreadStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockThreadStorage {
	mock := &MockThreadStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockThreadStorage is an autogenerated mock type for the ThreadStorage type
type MockThreadStorage struct {
	mock.Mock
}

type MockThreadStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockThreadStorage) EXPECT() *MockThreadStorage_Expecter {
	return &MockThreadStorage_Expecter{mock: &_m.Mock}
}

// CreateThread provides a mock function for the type MockThreadStorage
func (_mock *MockThreadStorage) CreateThread(ctx context.Context, thread entities.ThreadReadOnly) error {
	ret := _mock.Called(ctx, thread)

	if len(ret) == 0 {
		panic("no return value specified for CreateThread")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.ThreadReadOnly) error); ok {
		r0 = returnFunc(ctx, thread)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockThreadStorage_CreateThread_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateThread'
type MockThreadStorage_CreateThread_Call struct {
	*mock.Call
}

// CreateThread is a helper method to define mock.On call
//   - ctx context.Context
//   - thread entities.ThreadReadOnly
func (_e *MockThreadStorage_Expecter) CreateThread(ctx interface{}, thread interface{}) *MockThreadStorage_CreateThread_Call {
	return &MockThreadStorage_CreateThread_Call{Call: _e.mock.On("CreateThread", ctx, thread)}
}

func (_c *MockThreadStorage_CreateThread_Call) Run(run func(ctx context.Context, thread entities.ThreadReadOnly)) *MockThreadStorage_CreateThread_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entities.ThreadReadOnly
		if args[1] != nil {
			arg1 = args[1].(entities.ThreadReadOnly)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockThreadStorage_CreateThread_Call) Return(err error) *MockThreadStorage_CreateThread_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockThreadStorage_CreateThread_Call) RunAndReturn(run func(ctx context.Context, thread entities.ThreadReadOnly) error) *MockThreadStorage_CreateThread_Call {
	_c.Call.Return(run)
	return _c
}

// GetThread provides a mock function for the type MockThreadStorage
func (_mock *MockThreadStorage) GetThread(ctx context.Context, threadID ids.ThreadID) (*entities.Thread, error) {
	ret := _mock.Called(ctx, threadID)

	if len(ret) == 0 {
		panic("no return value specified for GetThread")
	}

	var r0 *entities.Thread
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ids.ThreadID) (*entities.Thread, error)); ok {
		return returnFunc(ctx, threadID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ids.ThreadID) *entities.Thread); ok {
		r0 = returnFunc(ctx, threadID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Thread)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ids.ThreadID) error); ok {
		r1 = returnFunc(ctx, threadID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockThreadStorage_GetThread_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetThread'
type MockThreadStorage_GetThread_Call struct {
	*mock.Call
}

// GetThread is a helper method to define mock.On call
//   - ctx context.Context
//   - threadID ids.ThreadID
func (_e *MockThreadStorage_Expecter) GetThread(ctx interface{}, threadID interface{}) *MockThreadStorage_GetThread_Call {
	return &MockThreadStorage_GetThread_Call{Call: _e.mock.On("GetThread", ctx, threadID)}
}

func (_c *MockThreadStorage_GetThread_Call) Run(run func(ctx context.Context, threadID ids.ThreadID)) *MockThreadStorage_GetThread_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ids.ThreadID
		if args[1] != nil {
			arg1 = args[1].(ids.ThreadID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockThreadStorage_GetThread_Call) Return(thread *entities.Thread, err error) *MockThreadStorage_GetThread_Call {
	_c.Call.Return(thread, err)
	return _c
}

func (_c *MockThreadStorage_GetThread_Call) RunAndReturn(run func(ctx context.Context, threadID ids.ThreadID) (*entities.Thread, error)) *MockThreadStorage_GetThread_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateThread provides a mock function for the type MockThreadStorage
func (_mock *MockThreadStorage) UpdateThread(ctx context.Context, thread entities.ThreadReadOnly) error {
	ret := _mock.Called(ctx, thread)

	if len(ret) == 0 {
		panic("no return value specified for UpdateThread")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.ThreadReadOnly) error); ok {
		r0 = returnFunc(ctx, thread)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockThreadStorage_UpdateThread_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateThread'
type MockThreadStorage_UpdateThread_Call struct {
	*mock.Call
}

// UpdateThread is a helper method to define mock.On call
//   - ctx context.Context
//   - thread entities.ThreadReadOnly
func (_e *MockThreadStorage_Expecter) UpdateThread(ctx interface{}, thread interface{}) *MockThreadStorage_UpdateThread_Call {
	return &MockThreadStorage_UpdateThread_Call{Call: _e.mock.On("UpdateThread", ctx, thread)}
}

func (_c *MockThreadStorage_UpdateThread_Call) Run(run func(ctx context.Context, thread entities.ThreadReadOnly)) *MockThreadStorage_UpdateThread_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entities.ThreadReadOnly
		if args[1] != nil {
			arg1 = args[1].(entities.ThreadReadOnly)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockThreadStorage_UpdateThread_Call) Return(err error) *MockThreadStorage_UpdateThread_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockThreadStorage_UpdateThread_Call) RunAndReturn(run func(ctx context.Context, thread entities.ThreadReadOnly) error) *MockThreadStorage_UpdateThread_Call {
	_c.Call.Return(run)
	return _c
}
