// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"encoding/json"
	"net/url"

	"github.com/quenbyako/cynosure/internal/domains/cynosure/entities"
	"github.com/quenbyako/cynosure/internal/domains/cynosure/primitives/ids"
	"github.com/quenbyako/cynosure/internal/domains/cynosure/primitives/messages"
	"github.com/quenbyako/cynosure/internal/domains/cynosure/primitives/tools"
	mock "github.com/stretchr/testify/mock"
	"golang.org/x/oauth2"
)

// NewMockToolClient creates a new instance of MockToolClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockToolClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockToolClient {
	mock := &MockToolClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockToolClient is an autogenerated mock type for the ToolClient type
type MockToolClient struct {
	mock.Mock
}

type MockToolClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockToolClient) EXPECT() *MockToolClient_Expecter {
	return &MockToolClient_Expecter{mock: &_m.Mock}
}

// DiscoverTools provides a mock function for the type MockToolClient
func (_mock *MockToolClient) DiscoverTools(ctx context.Context, u *url.URL, token *oauth2.Token, account ids.AccountID, accountDesc string) ([]tools.RawToolInfo, error) {
	ret := _mock.Called(ctx, u, token, account, accountDesc)

	if len(ret) == 0 {
		panic("no return value specified for DiscoverTools")
	}

	var r0 []tools.RawToolInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *url.URL, *oauth2.Token, ids.AccountID, string) ([]tools.RawToolInfo, error)); ok {
		return returnFunc(ctx, u, token, account, accountDesc)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *url.URL, *oauth2.Token, ids.AccountID, string) []tools.RawToolInfo); ok {
		r0 = returnFunc(ctx, u, token, account, accountDesc)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]tools.RawToolInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *url.URL, *oauth2.Token, ids.AccountID, string) error); ok {
		r1 = returnFunc(ctx, u, token, account, accountDesc)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockToolClient_DiscoverTools_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DiscoverTools'
type MockToolClient_DiscoverTools_Call struct {
	*mock.Call
}

// DiscoverTools is a helper method to define mock.On call
//   - ctx context.Context
//   - u *url.URL
//   - token *oauth2.Token
//   - account ids.AccountID
//   - accountDesc string
func (_e *MockToolClient_Expecter) DiscoverTools(ctx interface{}, u interface{}, token interface{}, account interface{}, accountDesc interface{}) *MockToolClient_DiscoverTools_Call {
	return &MockToolClient_DiscoverTools_Call{Call: _e.mock.On("DiscoverTools", ctx, u, token, account, accountDesc)}
}

func (_c *MockToolClient_DiscoverTools_Call) Run(run func(ctx context.Context, u *url.URL, token *oauth2.Token, account ids.AccountID, accountDesc string)) *MockToolClient_DiscoverTools_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *url.URL
		if args[1] != nil {
			arg1 = args[1].(*url.URL)
		}
		var arg2 *oauth2.Token
		if args[2] != nil {
			arg2 = args[2].(*oauth2.Token)
		}
		var arg3 ids.AccountID
		if args[3] != nil {
			arg3 = args[3].(ids.AccountID)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockToolClient_DiscoverTools_Call) Return(rawToolInfos []tools.RawToolInfo, err error) *MockToolClient_DiscoverTools_Call {
	_c.Call.Return(rawToolInfos, err)
	return _c
}

func (_c *MockToolClient_DiscoverTools_Call) RunAndReturn(run func(ctx context.Context, u *url.URL, token *oauth2.Token, account ids.AccountID, accountDesc string) ([]tools.RawToolInfo, error)) *MockToolClient_DiscoverTools_Call {
	_c.Call.Return(run)
	return _c
}

// ExecuteTool provides a mock function for the type MockToolClient
func (_mock *MockToolClient) ExecuteTool(ctx context.Context, tool entities.Tool, args map[string]json.RawMessage, toolCallID string) (messages.MessageTool, error) {
	ret := _mock.Called(ctx, tool, args, toolCallID)

	if len(ret) == 0 {
		panic("no return value specified for ExecuteTool")
	}

	var r0 messages.MessageTool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.Tool, map[string]json.RawMessage, string) (messages.MessageTool, error)); ok {
		return returnFunc(ctx, tool, args, toolCallID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.Tool, map[string]json.RawMessage, string) messages.MessageTool); ok {
		r0 = returnFunc(ctx, tool, args, toolCallID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(messages.MessageTool)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entities.Tool, map[string]json.RawMessage, string) error); ok {
		r1 = returnFunc(ctx, tool, args, toolCallID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockToolClient_ExecuteTool_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecuteTool'
type MockToolClient_ExecuteTool_Call struct {
	*mock.Call
}

// ExecuteTool is a helper method to define mock.On call
//   - ctx context.Context
//   - tool entities.Tool
//   - args map[string]json.RawMessage
//   - toolCallID string
func (_e *MockToolClient_Expecter) ExecuteTool(ctx interface{}, tool interface{}, args interface{}, toolCallID interface{}) *MockToolClient_ExecuteTool_Call {
	return &MockToolClient_ExecuteTool_Call{Call: _e.mock.On("ExecuteTool", ctx, tool, args, toolCallID)}
}

func (_c *MockToolClient_ExecuteTool_Call) Run(run func(ctx context.Context, tool entities.Tool, args map[string]json.RawMessage, toolCallID string)) *MockToolClient_ExecuteTool_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entities.Tool
		if args[1] != nil {
			arg1 = args[1].(entities.Tool)
		}
		var arg2 map[string]json.RawMessage
		if args[2] != nil {
			arg2 = args[2].(map[string]json.RawMessage)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockToolClient_ExecuteTool_Call) Return(messageTool messages.MessageTool, err error) *MockToolClient_ExecuteTool_Call {
	_c.Call.Return(messageTool, err)
	return _c
}

func (_c *MockToolClient_ExecuteTool_Call) RunAndReturn(run func(ctx context.Context, tool entities.Tool, args map[string]json.RawMessage, toolCallID string) (messages.MessageTool, error)) *MockToolClient_ExecuteTool_Call {
	_c.Call.Return(run)
	return _c
}
