// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"encoding/json"

	"github.com/quenbyako/cynosure/internal/domains/cynosure/entities"
	"github.com/quenbyako/cynosure/internal/domains/cynosure/primitives/messages"
	mock "github.com/stretchr/testify/mock"
	"golang.org/x/oauth2"
)

// NewMockToolClient creates a new instance of MockToolClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockToolClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockToolClient {
	mock := &MockToolClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockToolClient is an autogenerated mock type for the ToolClient type
type MockToolClient struct {
	mock.Mock
}

type MockToolClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockToolClient) EXPECT() *MockToolClient_Expecter {
	return &MockToolClient_Expecter{mock: &_m.Mock}
}

// DiscoverTools provides a mock function for the type MockToolClient
func (_mock *MockToolClient) DiscoverTools(ctx context.Context, url string, token *oauth2.Token) ([]*entities.Tool, error) {
	ret := _mock.Called(ctx, url, token)

	if len(ret) == 0 {
		panic("no return value specified for DiscoverTools")
	}

	var r0 []*entities.Tool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *oauth2.Token) ([]*entities.Tool, error)); ok {
		return returnFunc(ctx, url, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *oauth2.Token) []*entities.Tool); ok {
		r0 = returnFunc(ctx, url, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Tool)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *oauth2.Token) error); ok {
		r1 = returnFunc(ctx, url, token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockToolClient_DiscoverTools_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DiscoverTools'
type MockToolClient_DiscoverTools_Call struct {
	*mock.Call
}

// DiscoverTools is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
//   - token *oauth2.Token
func (_e *MockToolClient_Expecter) DiscoverTools(ctx interface{}, url interface{}, token interface{}) *MockToolClient_DiscoverTools_Call {
	return &MockToolClient_DiscoverTools_Call{Call: _e.mock.On("DiscoverTools", ctx, url, token)}
}

func (_c *MockToolClient_DiscoverTools_Call) Run(run func(ctx context.Context, url string, token *oauth2.Token)) *MockToolClient_DiscoverTools_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *oauth2.Token
		if args[2] != nil {
			arg2 = args[2].(*oauth2.Token)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockToolClient_DiscoverTools_Call) Return(tools []*entities.Tool, err error) *MockToolClient_DiscoverTools_Call {
	_c.Call.Return(tools, err)
	return _c
}

func (_c *MockToolClient_DiscoverTools_Call) RunAndReturn(run func(ctx context.Context, url string, token *oauth2.Token) ([]*entities.Tool, error)) *MockToolClient_DiscoverTools_Call {
	_c.Call.Return(run)
	return _c
}

// ExecuteTool provides a mock function for the type MockToolClient
func (_mock *MockToolClient) ExecuteTool(ctx context.Context, tool entities.Tool, args map[string]json.RawMessage) (messages.MessageTool, error) {
	ret := _mock.Called(ctx, tool, args)

	if len(ret) == 0 {
		panic("no return value specified for ExecuteTool")
	}

	var r0 messages.MessageTool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.Tool, map[string]json.RawMessage) (messages.MessageTool, error)); ok {
		return returnFunc(ctx, tool, args)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.Tool, map[string]json.RawMessage) messages.MessageTool); ok {
		r0 = returnFunc(ctx, tool, args)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(messages.MessageTool)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entities.Tool, map[string]json.RawMessage) error); ok {
		r1 = returnFunc(ctx, tool, args)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockToolClient_ExecuteTool_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecuteTool'
type MockToolClient_ExecuteTool_Call struct {
	*mock.Call
}

// ExecuteTool is a helper method to define mock.On call
//   - ctx context.Context
//   - tool entities.Tool
//   - args map[string]json.RawMessage
func (_e *MockToolClient_Expecter) ExecuteTool(ctx interface{}, tool interface{}, args interface{}) *MockToolClient_ExecuteTool_Call {
	return &MockToolClient_ExecuteTool_Call{Call: _e.mock.On("ExecuteTool", ctx, tool, args)}
}

func (_c *MockToolClient_ExecuteTool_Call) Run(run func(ctx context.Context, tool entities.Tool, args map[string]json.RawMessage)) *MockToolClient_ExecuteTool_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entities.Tool
		if args[1] != nil {
			arg1 = args[1].(entities.Tool)
		}
		var arg2 map[string]json.RawMessage
		if args[2] != nil {
			arg2 = args[2].(map[string]json.RawMessage)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockToolClient_ExecuteTool_Call) Return(messageTool messages.MessageTool, err error) *MockToolClient_ExecuteTool_Call {
	_c.Call.Return(messageTool, err)
	return _c
}

func (_c *MockToolClient_ExecuteTool_Call) RunAndReturn(run func(ctx context.Context, tool entities.Tool, args map[string]json.RawMessage) (messages.MessageTool, error)) *MockToolClient_ExecuteTool_Call {
	_c.Call.Return(run)
	return _c
}
