// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/quenbyako/cynosure/internal/domains/cynosure/types/ids"
	"github.com/quenbyako/cynosure/internal/domains/cynosure/types/messages"
	"github.com/quenbyako/cynosure/internal/domains/cynosure/types/tools"
	mock "github.com/stretchr/testify/mock"
	"golang.org/x/oauth2"
)

// NewMockToolManager creates a new instance of MockToolManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockToolManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockToolManager {
	mock := &MockToolManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockToolManager is an autogenerated mock type for the ToolManager type
type MockToolManager struct {
	mock.Mock
}

type MockToolManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockToolManager) EXPECT() *MockToolManager_Expecter {
	return &MockToolManager_Expecter{mock: &_m.Mock}
}

// ExecuteTool provides a mock function for the type MockToolManager
func (_mock *MockToolManager) ExecuteTool(ctx context.Context, call tools.ToolCall) (messages.MessageTool, error) {
	ret := _mock.Called(ctx, call)

	if len(ret) == 0 {
		panic("no return value specified for ExecuteTool")
	}

	var r0 messages.MessageTool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, tools.ToolCall) (messages.MessageTool, error)); ok {
		return returnFunc(ctx, call)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, tools.ToolCall) messages.MessageTool); ok {
		r0 = returnFunc(ctx, call)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(messages.MessageTool)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, tools.ToolCall) error); ok {
		r1 = returnFunc(ctx, call)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockToolManager_ExecuteTool_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecuteTool'
type MockToolManager_ExecuteTool_Call struct {
	*mock.Call
}

// ExecuteTool is a helper method to define mock.On call
//   - ctx context.Context
//   - call tools.ToolCall
func (_e *MockToolManager_Expecter) ExecuteTool(ctx interface{}, call interface{}) *MockToolManager_ExecuteTool_Call {
	return &MockToolManager_ExecuteTool_Call{Call: _e.mock.On("ExecuteTool", ctx, call)}
}

func (_c *MockToolManager_ExecuteTool_Call) Run(run func(ctx context.Context, call tools.ToolCall)) *MockToolManager_ExecuteTool_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 tools.ToolCall
		if args[1] != nil {
			arg1 = args[1].(tools.ToolCall)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockToolManager_ExecuteTool_Call) Return(messageTool messages.MessageTool, err error) *MockToolManager_ExecuteTool_Call {
	_c.Call.Return(messageTool, err)
	return _c
}

func (_c *MockToolManager_ExecuteTool_Call) RunAndReturn(run func(ctx context.Context, call tools.ToolCall) (messages.MessageTool, error)) *MockToolManager_ExecuteTool_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterTools provides a mock function for the type MockToolManager
func (_mock *MockToolManager) RegisterTools(ctx context.Context, account ids.AccountID, name string, description string, token *oauth2.Token) error {
	ret := _mock.Called(ctx, account, name, description, token)

	if len(ret) == 0 {
		panic("no return value specified for RegisterTools")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ids.AccountID, string, string, *oauth2.Token) error); ok {
		r0 = returnFunc(ctx, account, name, description, token)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockToolManager_RegisterTools_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterTools'
type MockToolManager_RegisterTools_Call struct {
	*mock.Call
}

// RegisterTools is a helper method to define mock.On call
//   - ctx context.Context
//   - account ids.AccountID
//   - name string
//   - description string
//   - token *oauth2.Token
func (_e *MockToolManager_Expecter) RegisterTools(ctx interface{}, account interface{}, name interface{}, description interface{}, token interface{}) *MockToolManager_RegisterTools_Call {
	return &MockToolManager_RegisterTools_Call{Call: _e.mock.On("RegisterTools", ctx, account, name, description, token)}
}

func (_c *MockToolManager_RegisterTools_Call) Run(run func(ctx context.Context, account ids.AccountID, name string, description string, token *oauth2.Token)) *MockToolManager_RegisterTools_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ids.AccountID
		if args[1] != nil {
			arg1 = args[1].(ids.AccountID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 *oauth2.Token
		if args[4] != nil {
			arg4 = args[4].(*oauth2.Token)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockToolManager_RegisterTools_Call) Return(err error) *MockToolManager_RegisterTools_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockToolManager_RegisterTools_Call) RunAndReturn(run func(ctx context.Context, account ids.AccountID, name string, description string, token *oauth2.Token) error) *MockToolManager_RegisterTools_Call {
	_c.Call.Return(run)
	return _c
}

// RetrieveRelevantTools provides a mock function for the type MockToolManager
func (_mock *MockToolManager) RetrieveRelevantTools(ctx context.Context, user ids.UserID, input []messages.Message) (map[ids.AccountID][]tools.ToolInfo, error) {
	ret := _mock.Called(ctx, user, input)

	if len(ret) == 0 {
		panic("no return value specified for RetrieveRelevantTools")
	}

	var r0 map[ids.AccountID][]tools.ToolInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ids.UserID, []messages.Message) (map[ids.AccountID][]tools.ToolInfo, error)); ok {
		return returnFunc(ctx, user, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ids.UserID, []messages.Message) map[ids.AccountID][]tools.ToolInfo); ok {
		r0 = returnFunc(ctx, user, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[ids.AccountID][]tools.ToolInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ids.UserID, []messages.Message) error); ok {
		r1 = returnFunc(ctx, user, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockToolManager_RetrieveRelevantTools_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RetrieveRelevantTools'
type MockToolManager_RetrieveRelevantTools_Call struct {
	*mock.Call
}

// RetrieveRelevantTools is a helper method to define mock.On call
//   - ctx context.Context
//   - user ids.UserID
//   - input []messages.Message
func (_e *MockToolManager_Expecter) RetrieveRelevantTools(ctx interface{}, user interface{}, input interface{}) *MockToolManager_RetrieveRelevantTools_Call {
	return &MockToolManager_RetrieveRelevantTools_Call{Call: _e.mock.On("RetrieveRelevantTools", ctx, user, input)}
}

func (_c *MockToolManager_RetrieveRelevantTools_Call) Run(run func(ctx context.Context, user ids.UserID, input []messages.Message)) *MockToolManager_RetrieveRelevantTools_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ids.UserID
		if args[1] != nil {
			arg1 = args[1].(ids.UserID)
		}
		var arg2 []messages.Message
		if args[2] != nil {
			arg2 = args[2].([]messages.Message)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockToolManager_RetrieveRelevantTools_Call) Return(accountIDToToolInfos map[ids.AccountID][]tools.ToolInfo, err error) *MockToolManager_RetrieveRelevantTools_Call {
	_c.Call.Return(accountIDToToolInfos, err)
	return _c
}

func (_c *MockToolManager_RetrieveRelevantTools_Call) RunAndReturn(run func(ctx context.Context, user ids.UserID, input []messages.Message) (map[ids.AccountID][]tools.ToolInfo, error)) *MockToolManager_RetrieveRelevantTools_Call {
	_c.Call.Return(run)
	return _c
}
