// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/quenbyako/cynosure/internal/domains/cynosure/entities"
	"github.com/quenbyako/cynosure/internal/domains/cynosure/primitives/messages"
	mock "github.com/stretchr/testify/mock"
)

// NewMockToolSemanticIndex creates a new instance of MockToolSemanticIndex. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockToolSemanticIndex(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockToolSemanticIndex {
	mock := &MockToolSemanticIndex{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockToolSemanticIndex is an autogenerated mock type for the ToolSemanticIndex type
type MockToolSemanticIndex struct {
	mock.Mock
}

type MockToolSemanticIndex_Expecter struct {
	mock *mock.Mock
}

func (_m *MockToolSemanticIndex) EXPECT() *MockToolSemanticIndex_Expecter {
	return &MockToolSemanticIndex_Expecter{mock: &_m.Mock}
}

// BuildToolEmbedding provides a mock function for the type MockToolSemanticIndex
func (_mock *MockToolSemanticIndex) BuildToolEmbedding(ctx context.Context, msgs []messages.Message) ([1536]float32, error) {
	ret := _mock.Called(ctx, msgs)

	if len(ret) == 0 {
		panic("no return value specified for BuildToolEmbedding")
	}

	var r0 [1536]float32
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []messages.Message) ([1536]float32, error)); ok {
		return returnFunc(ctx, msgs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []messages.Message) [1536]float32); ok {
		r0 = returnFunc(ctx, msgs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([1536]float32)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []messages.Message) error); ok {
		r1 = returnFunc(ctx, msgs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockToolSemanticIndex_BuildToolEmbedding_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BuildToolEmbedding'
type MockToolSemanticIndex_BuildToolEmbedding_Call struct {
	*mock.Call
}

// BuildToolEmbedding is a helper method to define mock.On call
//   - ctx context.Context
//   - msgs []messages.Message
func (_e *MockToolSemanticIndex_Expecter) BuildToolEmbedding(ctx interface{}, msgs interface{}) *MockToolSemanticIndex_BuildToolEmbedding_Call {
	return &MockToolSemanticIndex_BuildToolEmbedding_Call{Call: _e.mock.On("BuildToolEmbedding", ctx, msgs)}
}

func (_c *MockToolSemanticIndex_BuildToolEmbedding_Call) Run(run func(ctx context.Context, msgs []messages.Message)) *MockToolSemanticIndex_BuildToolEmbedding_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []messages.Message
		if args[1] != nil {
			arg1 = args[1].([]messages.Message)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockToolSemanticIndex_BuildToolEmbedding_Call) Return(float32s [1536]float32, err error) *MockToolSemanticIndex_BuildToolEmbedding_Call {
	_c.Call.Return(float32s, err)
	return _c
}

func (_c *MockToolSemanticIndex_BuildToolEmbedding_Call) RunAndReturn(run func(ctx context.Context, msgs []messages.Message) ([1536]float32, error)) *MockToolSemanticIndex_BuildToolEmbedding_Call {
	_c.Call.Return(run)
	return _c
}

// IndexTool provides a mock function for the type MockToolSemanticIndex
func (_mock *MockToolSemanticIndex) IndexTool(ctx context.Context, tool entities.ToolReadOnly) ([1536]float32, error) {
	ret := _mock.Called(ctx, tool)

	if len(ret) == 0 {
		panic("no return value specified for IndexTool")
	}

	var r0 [1536]float32
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.ToolReadOnly) ([1536]float32, error)); ok {
		return returnFunc(ctx, tool)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.ToolReadOnly) [1536]float32); ok {
		r0 = returnFunc(ctx, tool)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([1536]float32)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entities.ToolReadOnly) error); ok {
		r1 = returnFunc(ctx, tool)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockToolSemanticIndex_IndexTool_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IndexTool'
type MockToolSemanticIndex_IndexTool_Call struct {
	*mock.Call
}

// IndexTool is a helper method to define mock.On call
//   - ctx context.Context
//   - tool entities.ToolReadOnly
func (_e *MockToolSemanticIndex_Expecter) IndexTool(ctx interface{}, tool interface{}) *MockToolSemanticIndex_IndexTool_Call {
	return &MockToolSemanticIndex_IndexTool_Call{Call: _e.mock.On("IndexTool", ctx, tool)}
}

func (_c *MockToolSemanticIndex_IndexTool_Call) Run(run func(ctx context.Context, tool entities.ToolReadOnly)) *MockToolSemanticIndex_IndexTool_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entities.ToolReadOnly
		if args[1] != nil {
			arg1 = args[1].(entities.ToolReadOnly)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockToolSemanticIndex_IndexTool_Call) Return(float32s [1536]float32, err error) *MockToolSemanticIndex_IndexTool_Call {
	_c.Call.Return(float32s, err)
	return _c
}

func (_c *MockToolSemanticIndex_IndexTool_Call) RunAndReturn(run func(ctx context.Context, tool entities.ToolReadOnly) ([1536]float32, error)) *MockToolSemanticIndex_IndexTool_Call {
	_c.Call.Return(run)
	return _c
}
