// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"encoding/json"
	"net/url"

	"github.com/quenbyako/cynosure/internal/domains/cynosure/entities"
	"github.com/quenbyako/cynosure/internal/domains/cynosure/ports/toolclient"
	"github.com/quenbyako/cynosure/internal/domains/cynosure/primitives/ids"
	"github.com/quenbyako/cynosure/internal/domains/cynosure/primitives/messages"
	"github.com/quenbyako/cynosure/internal/domains/cynosure/primitives/tools"
	mock "github.com/stretchr/testify/mock"
)

// NewToolClient creates a new instance of ToolClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewToolClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *ToolClient {
	mock := &ToolClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ToolClient is an autogenerated mock type for the Port type
type ToolClient struct {
	mock.Mock
}

type ToolClient_Expecter struct {
	mock *mock.Mock
}

func (_m *ToolClient) EXPECT() *ToolClient_Expecter {
	return &ToolClient_Expecter{mock: &_m.Mock}
}

// DiscoverTools provides a mock function for the type ToolClient
func (_mock *ToolClient) DiscoverTools(ctx context.Context, u *url.URL, account ids.AccountID, accountSlug string, accountDesc string, opts ...toolclient.DiscoverToolsOption) ([]tools.RawToolInfo, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, u, account, accountSlug, accountDesc, opts)
	} else {
		tmpRet = _mock.Called(ctx, u, account, accountSlug, accountDesc)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for DiscoverTools")
	}

	var r0 []tools.RawToolInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *url.URL, ids.AccountID, string, string, ...toolclient.DiscoverToolsOption) ([]tools.RawToolInfo, error)); ok {
		return returnFunc(ctx, u, account, accountSlug, accountDesc, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *url.URL, ids.AccountID, string, string, ...toolclient.DiscoverToolsOption) []tools.RawToolInfo); ok {
		r0 = returnFunc(ctx, u, account, accountSlug, accountDesc, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]tools.RawToolInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *url.URL, ids.AccountID, string, string, ...toolclient.DiscoverToolsOption) error); ok {
		r1 = returnFunc(ctx, u, account, accountSlug, accountDesc, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ToolClient_DiscoverTools_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DiscoverTools'
type ToolClient_DiscoverTools_Call struct {
	*mock.Call
}

// DiscoverTools is a helper method to define mock.On call
//   - ctx context.Context
//   - u *url.URL
//   - account ids.AccountID
//   - accountSlug string
//   - accountDesc string
//   - opts ...toolclient.DiscoverToolsOption
func (_e *ToolClient_Expecter) DiscoverTools(ctx interface{}, u interface{}, account interface{}, accountSlug interface{}, accountDesc interface{}, opts ...interface{}) *ToolClient_DiscoverTools_Call {
	return &ToolClient_DiscoverTools_Call{Call: _e.mock.On("DiscoverTools",
		append([]interface{}{ctx, u, account, accountSlug, accountDesc}, opts...)...)}
}

func (_c *ToolClient_DiscoverTools_Call) Run(run func(ctx context.Context, u *url.URL, account ids.AccountID, accountSlug string, accountDesc string, opts ...toolclient.DiscoverToolsOption)) *ToolClient_DiscoverTools_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *url.URL
		if args[1] != nil {
			arg1 = args[1].(*url.URL)
		}
		var arg2 ids.AccountID
		if args[2] != nil {
			arg2 = args[2].(ids.AccountID)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 []toolclient.DiscoverToolsOption
		var variadicArgs []toolclient.DiscoverToolsOption
		if len(args) > 5 {
			variadicArgs = args[5].([]toolclient.DiscoverToolsOption)
		}
		arg5 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5...,
		)
	})
	return _c
}

func (_c *ToolClient_DiscoverTools_Call) Return(rawToolInfos []tools.RawToolInfo, err error) *ToolClient_DiscoverTools_Call {
	_c.Call.Return(rawToolInfos, err)
	return _c
}

func (_c *ToolClient_DiscoverTools_Call) RunAndReturn(run func(ctx context.Context, u *url.URL, account ids.AccountID, accountSlug string, accountDesc string, opts ...toolclient.DiscoverToolsOption) ([]tools.RawToolInfo, error)) *ToolClient_DiscoverTools_Call {
	_c.Call.Return(run)
	return _c
}

// ExecuteTool provides a mock function for the type ToolClient
func (_mock *ToolClient) ExecuteTool(ctx context.Context, tool entities.ToolReadOnly, args map[string]json.RawMessage, toolCallID string) (messages.MessageTool, error) {
	ret := _mock.Called(ctx, tool, args, toolCallID)

	if len(ret) == 0 {
		panic("no return value specified for ExecuteTool")
	}

	var r0 messages.MessageTool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.ToolReadOnly, map[string]json.RawMessage, string) (messages.MessageTool, error)); ok {
		return returnFunc(ctx, tool, args, toolCallID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.ToolReadOnly, map[string]json.RawMessage, string) messages.MessageTool); ok {
		r0 = returnFunc(ctx, tool, args, toolCallID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(messages.MessageTool)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entities.ToolReadOnly, map[string]json.RawMessage, string) error); ok {
		r1 = returnFunc(ctx, tool, args, toolCallID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ToolClient_ExecuteTool_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecuteTool'
type ToolClient_ExecuteTool_Call struct {
	*mock.Call
}

// ExecuteTool is a helper method to define mock.On call
//   - ctx context.Context
//   - tool entities.ToolReadOnly
//   - args map[string]json.RawMessage
//   - toolCallID string
func (_e *ToolClient_Expecter) ExecuteTool(ctx interface{}, tool interface{}, args interface{}, toolCallID interface{}) *ToolClient_ExecuteTool_Call {
	return &ToolClient_ExecuteTool_Call{Call: _e.mock.On("ExecuteTool", ctx, tool, args, toolCallID)}
}

func (_c *ToolClient_ExecuteTool_Call) Run(run func(ctx context.Context, tool entities.ToolReadOnly, args map[string]json.RawMessage, toolCallID string)) *ToolClient_ExecuteTool_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entities.ToolReadOnly
		if args[1] != nil {
			arg1 = args[1].(entities.ToolReadOnly)
		}
		var arg2 map[string]json.RawMessage
		if args[2] != nil {
			arg2 = args[2].(map[string]json.RawMessage)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *ToolClient_ExecuteTool_Call) Return(messageTool messages.MessageTool, err error) *ToolClient_ExecuteTool_Call {
	_c.Call.Return(messageTool, err)
	return _c
}

func (_c *ToolClient_ExecuteTool_Call) RunAndReturn(run func(ctx context.Context, tool entities.ToolReadOnly, args map[string]json.RawMessage, toolCallID string) (messages.MessageTool, error)) *ToolClient_ExecuteTool_Call {
	_c.Call.Return(run)
	return _c
}
