// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/quenbyako/cynosure/internal/domains/cynosure/entities"
	"github.com/quenbyako/cynosure/internal/domains/cynosure/primitives/ids"
	mock "github.com/stretchr/testify/mock"
)

// NewMockToolStorage creates a new instance of MockToolStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockToolStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockToolStorage {
	mock := &MockToolStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockToolStorage is an autogenerated mock type for the ToolStorage type
type MockToolStorage struct {
	mock.Mock
}

type MockToolStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockToolStorage) EXPECT() *MockToolStorage_Expecter {
	return &MockToolStorage_Expecter{mock: &_m.Mock}
}

// DeleteTool provides a mock function for the type MockToolStorage
func (_mock *MockToolStorage) DeleteTool(ctx context.Context, tool ids.ToolID) error {
	ret := _mock.Called(ctx, tool)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTool")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ids.ToolID) error); ok {
		r0 = returnFunc(ctx, tool)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockToolStorage_DeleteTool_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTool'
type MockToolStorage_DeleteTool_Call struct {
	*mock.Call
}

// DeleteTool is a helper method to define mock.On call
//   - ctx context.Context
//   - tool ids.ToolID
func (_e *MockToolStorage_Expecter) DeleteTool(ctx interface{}, tool interface{}) *MockToolStorage_DeleteTool_Call {
	return &MockToolStorage_DeleteTool_Call{Call: _e.mock.On("DeleteTool", ctx, tool)}
}

func (_c *MockToolStorage_DeleteTool_Call) Run(run func(ctx context.Context, tool ids.ToolID)) *MockToolStorage_DeleteTool_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ids.ToolID
		if args[1] != nil {
			arg1 = args[1].(ids.ToolID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockToolStorage_DeleteTool_Call) Return(err error) *MockToolStorage_DeleteTool_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockToolStorage_DeleteTool_Call) RunAndReturn(run func(ctx context.Context, tool ids.ToolID) error) *MockToolStorage_DeleteTool_Call {
	_c.Call.Return(run)
	return _c
}

// GetTool provides a mock function for the type MockToolStorage
func (_mock *MockToolStorage) GetTool(ctx context.Context, account ids.AccountID, tool ids.ToolID) (*entities.Tool, error) {
	ret := _mock.Called(ctx, account, tool)

	if len(ret) == 0 {
		panic("no return value specified for GetTool")
	}

	var r0 *entities.Tool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ids.AccountID, ids.ToolID) (*entities.Tool, error)); ok {
		return returnFunc(ctx, account, tool)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ids.AccountID, ids.ToolID) *entities.Tool); ok {
		r0 = returnFunc(ctx, account, tool)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Tool)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ids.AccountID, ids.ToolID) error); ok {
		r1 = returnFunc(ctx, account, tool)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockToolStorage_GetTool_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTool'
type MockToolStorage_GetTool_Call struct {
	*mock.Call
}

// GetTool is a helper method to define mock.On call
//   - ctx context.Context
//   - account ids.AccountID
//   - tool ids.ToolID
func (_e *MockToolStorage_Expecter) GetTool(ctx interface{}, account interface{}, tool interface{}) *MockToolStorage_GetTool_Call {
	return &MockToolStorage_GetTool_Call{Call: _e.mock.On("GetTool", ctx, account, tool)}
}

func (_c *MockToolStorage_GetTool_Call) Run(run func(ctx context.Context, account ids.AccountID, tool ids.ToolID)) *MockToolStorage_GetTool_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ids.AccountID
		if args[1] != nil {
			arg1 = args[1].(ids.AccountID)
		}
		var arg2 ids.ToolID
		if args[2] != nil {
			arg2 = args[2].(ids.ToolID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockToolStorage_GetTool_Call) Return(tool1 *entities.Tool, err error) *MockToolStorage_GetTool_Call {
	_c.Call.Return(tool1, err)
	return _c
}

func (_c *MockToolStorage_GetTool_Call) RunAndReturn(run func(ctx context.Context, account ids.AccountID, tool ids.ToolID) (*entities.Tool, error)) *MockToolStorage_GetTool_Call {
	_c.Call.Return(run)
	return _c
}

// ListTools provides a mock function for the type MockToolStorage
func (_mock *MockToolStorage) ListTools(ctx context.Context, account ids.AccountID) ([]*entities.Tool, error) {
	ret := _mock.Called(ctx, account)

	if len(ret) == 0 {
		panic("no return value specified for ListTools")
	}

	var r0 []*entities.Tool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ids.AccountID) ([]*entities.Tool, error)); ok {
		return returnFunc(ctx, account)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ids.AccountID) []*entities.Tool); ok {
		r0 = returnFunc(ctx, account)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Tool)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ids.AccountID) error); ok {
		r1 = returnFunc(ctx, account)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockToolStorage_ListTools_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTools'
type MockToolStorage_ListTools_Call struct {
	*mock.Call
}

// ListTools is a helper method to define mock.On call
//   - ctx context.Context
//   - account ids.AccountID
func (_e *MockToolStorage_Expecter) ListTools(ctx interface{}, account interface{}) *MockToolStorage_ListTools_Call {
	return &MockToolStorage_ListTools_Call{Call: _e.mock.On("ListTools", ctx, account)}
}

func (_c *MockToolStorage_ListTools_Call) Run(run func(ctx context.Context, account ids.AccountID)) *MockToolStorage_ListTools_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ids.AccountID
		if args[1] != nil {
			arg1 = args[1].(ids.AccountID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockToolStorage_ListTools_Call) Return(tools []*entities.Tool, err error) *MockToolStorage_ListTools_Call {
	_c.Call.Return(tools, err)
	return _c
}

func (_c *MockToolStorage_ListTools_Call) RunAndReturn(run func(ctx context.Context, account ids.AccountID) ([]*entities.Tool, error)) *MockToolStorage_ListTools_Call {
	_c.Call.Return(run)
	return _c
}

// LookupTools provides a mock function for the type MockToolStorage
func (_mock *MockToolStorage) LookupTools(ctx context.Context, user ids.UserID, embedding [1536]float32, limit int) ([]*entities.Tool, error) {
	ret := _mock.Called(ctx, user, embedding, limit)

	if len(ret) == 0 {
		panic("no return value specified for LookupTools")
	}

	var r0 []*entities.Tool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ids.UserID, [1536]float32, int) ([]*entities.Tool, error)); ok {
		return returnFunc(ctx, user, embedding, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ids.UserID, [1536]float32, int) []*entities.Tool); ok {
		r0 = returnFunc(ctx, user, embedding, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Tool)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ids.UserID, [1536]float32, int) error); ok {
		r1 = returnFunc(ctx, user, embedding, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockToolStorage_LookupTools_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LookupTools'
type MockToolStorage_LookupTools_Call struct {
	*mock.Call
}

// LookupTools is a helper method to define mock.On call
//   - ctx context.Context
//   - user ids.UserID
//   - embedding [1536]float32
//   - limit int
func (_e *MockToolStorage_Expecter) LookupTools(ctx interface{}, user interface{}, embedding interface{}, limit interface{}) *MockToolStorage_LookupTools_Call {
	return &MockToolStorage_LookupTools_Call{Call: _e.mock.On("LookupTools", ctx, user, embedding, limit)}
}

func (_c *MockToolStorage_LookupTools_Call) Run(run func(ctx context.Context, user ids.UserID, embedding [1536]float32, limit int)) *MockToolStorage_LookupTools_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ids.UserID
		if args[1] != nil {
			arg1 = args[1].(ids.UserID)
		}
		var arg2 [1536]float32
		if args[2] != nil {
			arg2 = args[2].([1536]float32)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockToolStorage_LookupTools_Call) Return(tools []*entities.Tool, err error) *MockToolStorage_LookupTools_Call {
	_c.Call.Return(tools, err)
	return _c
}

func (_c *MockToolStorage_LookupTools_Call) RunAndReturn(run func(ctx context.Context, user ids.UserID, embedding [1536]float32, limit int) ([]*entities.Tool, error)) *MockToolStorage_LookupTools_Call {
	_c.Call.Return(run)
	return _c
}

// SaveTool provides a mock function for the type MockToolStorage
func (_mock *MockToolStorage) SaveTool(ctx context.Context, info entities.ToolReadOnly) error {
	ret := _mock.Called(ctx, info)

	if len(ret) == 0 {
		panic("no return value specified for SaveTool")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.ToolReadOnly) error); ok {
		r0 = returnFunc(ctx, info)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockToolStorage_SaveTool_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveTool'
type MockToolStorage_SaveTool_Call struct {
	*mock.Call
}

// SaveTool is a helper method to define mock.On call
//   - ctx context.Context
//   - info entities.ToolReadOnly
func (_e *MockToolStorage_Expecter) SaveTool(ctx interface{}, info interface{}) *MockToolStorage_SaveTool_Call {
	return &MockToolStorage_SaveTool_Call{Call: _e.mock.On("SaveTool", ctx, info)}
}

func (_c *MockToolStorage_SaveTool_Call) Run(run func(ctx context.Context, info entities.ToolReadOnly)) *MockToolStorage_SaveTool_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entities.ToolReadOnly
		if args[1] != nil {
			arg1 = args[1].(entities.ToolReadOnly)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockToolStorage_SaveTool_Call) Return(err error) *MockToolStorage_SaveTool_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockToolStorage_SaveTool_Call) RunAndReturn(run func(ctx context.Context, info entities.ToolReadOnly) error) *MockToolStorage_SaveTool_Call {
	_c.Call.Return(run)
	return _c
}
