// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: message.proto

package botapi

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Message struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MessageId       int64                  `protobuf:"varint,1,opt,name=message_id,proto3" json:"message_id,omitempty"`
	MessageThreadId int64                  `protobuf:"varint,2,opt,name=message_thread_id,proto3" json:"message_thread_id,omitempty"`
	// direct_message_topic
	From                 *User   `protobuf:"bytes,4,opt,name=from,proto3,oneof" json:"from,omitempty"`
	SenderChat           *Chat   `protobuf:"bytes,5,opt,name=sender_chat,proto3,oneof" json:"sender_chat,omitempty"`
	SenderBoostCount     *int64  `protobuf:"varint,6,opt,name=sender_boost_count,proto3,oneof" json:"sender_boost_count,omitempty"`
	SenderBusinessBot    *User   `protobuf:"bytes,7,opt,name=sender_business_bot,proto3,oneof" json:"sender_business_bot,omitempty"`
	Date                 int64   `protobuf:"varint,8,opt,name=date,proto3" json:"date,omitempty"`
	BusinessConnectionId *string `protobuf:"bytes,9,opt,name=business_connection_id,proto3,oneof" json:"business_connection_id,omitempty"`
	Chat                 *Chat   `protobuf:"bytes,10,opt,name=chat,proto3" json:"chat,omitempty"`
	// forward_origin
	IsTopicMessage     bool     `protobuf:"varint,12,opt,name=is_topic_message,proto3" json:"is_topic_message,omitempty"`
	IsAutomaticForward bool     `protobuf:"varint,13,opt,name=is_automatic_forward,proto3" json:"is_automatic_forward,omitempty"`
	ReplyToMessage     *Message `protobuf:"bytes,14,opt,name=reply_to_message,proto3,oneof" json:"reply_to_message,omitempty"`
	// external_reply
	// quote
	// reply_to_story
	ReplyToChecklistTaskId *int64  `protobuf:"varint,18,opt,name=reply_to_checklist_task_id,proto3,oneof" json:"reply_to_checklist_task_id,omitempty"`
	ViaBot                 *User   `protobuf:"bytes,19,opt,name=via_bot,proto3,oneof" json:"via_bot,omitempty"`
	EditDate               *int64  `protobuf:"varint,20,opt,name=edit_date,proto3,oneof" json:"edit_date,omitempty"`
	HasProtectedContent    bool    `protobuf:"varint,21,opt,name=has_protected_content,proto3" json:"has_protected_content,omitempty"`
	IsFromOnline           bool    `protobuf:"varint,22,opt,name=is_from_online,proto3" json:"is_from_online,omitempty"`
	IsPaidPost             bool    `protobuf:"varint,23,opt,name=is_paid_post,proto3" json:"is_paid_post,omitempty"`
	MediaGroupId           *string `protobuf:"bytes,24,opt,name=media_group_id,proto3,oneof" json:"media_group_id,omitempty"`
	AuthorSignature        *string `protobuf:"bytes,25,opt,name=author_signature,proto3,oneof" json:"author_signature,omitempty"`
	PaidStarCount          *int64  `protobuf:"varint,26,opt,name=paid_star_count,proto3,oneof" json:"paid_star_count,omitempty"`
	Text                   *string `protobuf:"bytes,27,opt,name=text,proto3,oneof" json:"text,omitempty"`
	// repeated MessageEntity entities = 28 [json_name = "entities"];
	// optional LinkPreviewOptions link_preview_options           = 29  [json_name = "link_preview_options"];
	// optional SuggestedPostInfo suggested_post_info             = 30  [json_name = "suggested_post_info"];
	EffectId *string `protobuf:"bytes,32,opt,name=effect_id,proto3,oneof" json:"effect_id,omitempty"`
	// optional Animation animation                         	     = 33  [json_name = "animation"];
	// optional Audio audio                             	         = 34  [json_name = "audio"];
	// optional Document document                          	     = 35  [json_name = "document"];
	// optional PaidMediaInfo paid_media                        	 = 36  [json_name = "paid_media"];
	// repeated PhotoSize photo                                   = 37  [json_name = "photo"];
	// optional Sticker sticker                           	       = 38  [json_name = "sticker"];
	// optional Story story                             	         = 39  [json_name = "story"];
	// optional Video video                             	         = 40  [json_name = "video"];
	// optional VideoNote video_note                        	     = 41  [json_name = "video_note"];
	// optional Voice voice                             	         = 42  [json_name = "voice"];
	Caption *string `protobuf:"bytes,43,opt,name=caption,proto3,oneof" json:"caption,omitempty"`
	// repeated MessageEntity caption_entities                  	 = 44  [json_name = "caption_entities"];
	ShowCaptionAboveMedia bool `protobuf:"varint,45,opt,name=show_caption_above_media,proto3" json:"show_caption_above_media,omitempty"`
	HasMediaSpoiler       bool `protobuf:"varint,46,opt,name=has_media_spoiler,proto3" json:"has_media_spoiler,omitempty"`
	// optional Checklist checklist                               = 47 [json_name = "checklist"];
	// optional Contact contact                                   = 48 [json_name = "contact"];
	// optional Dice dice                                         = 49 [json_name = "dice"];
	// optional Game game                                         = 50 [json_name = "game"];
	// optional Poll poll                                         = 51 [json_name = "poll"];
	// optional Venue venue                                       = 52 [json_name = "venue"];
	// optional Location location                                 = 53 [json_name = "location"];
	NewChatMembers []*User `protobuf:"bytes,54,rep,name=new_chat_members,proto3" json:"new_chat_members,omitempty"`
	LeftChatMember *User   `protobuf:"bytes,55,opt,name=left_chat_member,proto3,oneof" json:"left_chat_member,omitempty"`
	NewChatTitle   *string `protobuf:"bytes,56,opt,name=new_chat_title,proto3,oneof" json:"new_chat_title,omitempty"`
	// repeated PhotoSize new_chat_photo                          = 57 [json_name = "new_chat_photo"];
	DeleteChatPhoto       bool `protobuf:"varint,58,opt,name=delete_chat_photo,proto3" json:"delete_chat_photo,omitempty"`
	GroupChatCreated      bool `protobuf:"varint,59,opt,name=group_chat_created,proto3" json:"group_chat_created,omitempty"`
	SupergroupChatCreated bool `protobuf:"varint,60,opt,name=supergroup_chat_created,proto3" json:"supergroup_chat_created,omitempty"`
	ChannelChatCreated    bool `protobuf:"varint,61,opt,name=channel_chat_created,proto3" json:"channel_chat_created,omitempty"`
	// optional MessageAutoDeleteTimerChanged message_auto_delete_timer_changed = 62 [json_name = "message_auto_delete_timer_changed"];
	MigrateToChatId   *int64 `protobuf:"varint,63,opt,name=migrate_to_chat_id,proto3,oneof" json:"migrate_to_chat_id,omitempty"`
	MigrateFromChatId *int64 `protobuf:"varint,64,opt,name=migrate_from_chat_id,proto3,oneof" json:"migrate_from_chat_id,omitempty"`
	// optional MaybeInaccessibleMessage pinned_message                         = 65 [json_name = "pinned_message"];
	// optional Invoice invoice                                                 = 66 [json_name = "invoice"];
	// optional SuccessfulPayment successful_payment                            = 67 [json_name = "successful_payment"];
	// optional RefundedPayment refunded_payment                                = 68 [json_name = "refunded_payment"];
	// optional UsersShared users_shared                                        = 69 [json_name = "users_shared"];
	// optional ChatShared chat_shared                                          = 70 [json_name = "chat_shared"];
	// optional GiftInfo gift                                                   = 71 [json_name = "gift"];
	// optional UniqueGiftInfo unique_gift                                      = 72 [json_name = "unique_gift"];
	ConnectedWebsite *string `protobuf:"bytes,73,opt,name=connected_website,proto3,oneof" json:"connected_website,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *Message) GetMessageThreadId() int64 {
	if x != nil {
		return x.MessageThreadId
	}
	return 0
}

func (x *Message) GetFrom() *User {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *Message) GetSenderChat() *Chat {
	if x != nil {
		return x.SenderChat
	}
	return nil
}

func (x *Message) GetSenderBoostCount() int64 {
	if x != nil && x.SenderBoostCount != nil {
		return *x.SenderBoostCount
	}
	return 0
}

func (x *Message) GetSenderBusinessBot() *User {
	if x != nil {
		return x.SenderBusinessBot
	}
	return nil
}

func (x *Message) GetDate() int64 {
	if x != nil {
		return x.Date
	}
	return 0
}

func (x *Message) GetBusinessConnectionId() string {
	if x != nil && x.BusinessConnectionId != nil {
		return *x.BusinessConnectionId
	}
	return ""
}

func (x *Message) GetChat() *Chat {
	if x != nil {
		return x.Chat
	}
	return nil
}

func (x *Message) GetIsTopicMessage() bool {
	if x != nil {
		return x.IsTopicMessage
	}
	return false
}

func (x *Message) GetIsAutomaticForward() bool {
	if x != nil {
		return x.IsAutomaticForward
	}
	return false
}

func (x *Message) GetReplyToMessage() *Message {
	if x != nil {
		return x.ReplyToMessage
	}
	return nil
}

func (x *Message) GetReplyToChecklistTaskId() int64 {
	if x != nil && x.ReplyToChecklistTaskId != nil {
		return *x.ReplyToChecklistTaskId
	}
	return 0
}

func (x *Message) GetViaBot() *User {
	if x != nil {
		return x.ViaBot
	}
	return nil
}

func (x *Message) GetEditDate() int64 {
	if x != nil && x.EditDate != nil {
		return *x.EditDate
	}
	return 0
}

func (x *Message) GetHasProtectedContent() bool {
	if x != nil {
		return x.HasProtectedContent
	}
	return false
}

func (x *Message) GetIsFromOnline() bool {
	if x != nil {
		return x.IsFromOnline
	}
	return false
}

func (x *Message) GetIsPaidPost() bool {
	if x != nil {
		return x.IsPaidPost
	}
	return false
}

func (x *Message) GetMediaGroupId() string {
	if x != nil && x.MediaGroupId != nil {
		return *x.MediaGroupId
	}
	return ""
}

func (x *Message) GetAuthorSignature() string {
	if x != nil && x.AuthorSignature != nil {
		return *x.AuthorSignature
	}
	return ""
}

func (x *Message) GetPaidStarCount() int64 {
	if x != nil && x.PaidStarCount != nil {
		return *x.PaidStarCount
	}
	return 0
}

func (x *Message) GetText() string {
	if x != nil && x.Text != nil {
		return *x.Text
	}
	return ""
}

func (x *Message) GetEffectId() string {
	if x != nil && x.EffectId != nil {
		return *x.EffectId
	}
	return ""
}

func (x *Message) GetCaption() string {
	if x != nil && x.Caption != nil {
		return *x.Caption
	}
	return ""
}

func (x *Message) GetShowCaptionAboveMedia() bool {
	if x != nil {
		return x.ShowCaptionAboveMedia
	}
	return false
}

func (x *Message) GetHasMediaSpoiler() bool {
	if x != nil {
		return x.HasMediaSpoiler
	}
	return false
}

func (x *Message) GetNewChatMembers() []*User {
	if x != nil {
		return x.NewChatMembers
	}
	return nil
}

func (x *Message) GetLeftChatMember() *User {
	if x != nil {
		return x.LeftChatMember
	}
	return nil
}

func (x *Message) GetNewChatTitle() string {
	if x != nil && x.NewChatTitle != nil {
		return *x.NewChatTitle
	}
	return ""
}

func (x *Message) GetDeleteChatPhoto() bool {
	if x != nil {
		return x.DeleteChatPhoto
	}
	return false
}

func (x *Message) GetGroupChatCreated() bool {
	if x != nil {
		return x.GroupChatCreated
	}
	return false
}

func (x *Message) GetSupergroupChatCreated() bool {
	if x != nil {
		return x.SupergroupChatCreated
	}
	return false
}

func (x *Message) GetChannelChatCreated() bool {
	if x != nil {
		return x.ChannelChatCreated
	}
	return false
}

func (x *Message) GetMigrateToChatId() int64 {
	if x != nil && x.MigrateToChatId != nil {
		return *x.MigrateToChatId
	}
	return 0
}

func (x *Message) GetMigrateFromChatId() int64 {
	if x != nil && x.MigrateFromChatId != nil {
		return *x.MigrateFromChatId
	}
	return 0
}

func (x *Message) GetConnectedWebsite() string {
	if x != nil && x.ConnectedWebsite != nil {
		return *x.ConnectedWebsite
	}
	return ""
}

type User struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Id                      int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	IsBot                   bool                   `protobuf:"varint,2,opt,name=is_bot,proto3" json:"is_bot,omitempty"`
	FirstName               string                 `protobuf:"bytes,3,opt,name=first_name,proto3" json:"first_name,omitempty"`
	LastName                *string                `protobuf:"bytes,4,opt,name=last_name,proto3,oneof" json:"last_name,omitempty"`
	Username                *string                `protobuf:"bytes,5,opt,name=username,proto3,oneof" json:"username,omitempty"`
	LanguageCode            *string                `protobuf:"bytes,6,opt,name=language_code,proto3,oneof" json:"language_code,omitempty"`
	IsPremium               bool                   `protobuf:"varint,7,opt,name=is_premium,proto3" json:"is_premium,omitempty"`
	AddedToAttachmentMenu   bool                   `protobuf:"varint,8,opt,name=added_to_attachment_menu,proto3" json:"added_to_attachment_menu,omitempty"`
	CanJoinGroups           bool                   `protobuf:"varint,9,opt,name=can_join_groups,proto3" json:"can_join_groups,omitempty"`
	CanReadAllGroupMessages bool                   `protobuf:"varint,10,opt,name=can_read_all_group_messages,proto3" json:"can_read_all_group_messages,omitempty"`
	SupportsInlineQueries   bool                   `protobuf:"varint,11,opt,name=supports_inline_queries,proto3" json:"supports_inline_queries,omitempty"`
	CanConnectToBusiness    bool                   `protobuf:"varint,12,opt,name=can_connect_to_business,proto3" json:"can_connect_to_business,omitempty"`
	HasMainWebApp           bool                   `protobuf:"varint,13,opt,name=has_main_web_app,proto3" json:"has_main_web_app,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{1}
}

func (x *User) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetIsBot() bool {
	if x != nil {
		return x.IsBot
	}
	return false
}

func (x *User) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *User) GetLastName() string {
	if x != nil && x.LastName != nil {
		return *x.LastName
	}
	return ""
}

func (x *User) GetUsername() string {
	if x != nil && x.Username != nil {
		return *x.Username
	}
	return ""
}

func (x *User) GetLanguageCode() string {
	if x != nil && x.LanguageCode != nil {
		return *x.LanguageCode
	}
	return ""
}

func (x *User) GetIsPremium() bool {
	if x != nil {
		return x.IsPremium
	}
	return false
}

func (x *User) GetAddedToAttachmentMenu() bool {
	if x != nil {
		return x.AddedToAttachmentMenu
	}
	return false
}

func (x *User) GetCanJoinGroups() bool {
	if x != nil {
		return x.CanJoinGroups
	}
	return false
}

func (x *User) GetCanReadAllGroupMessages() bool {
	if x != nil {
		return x.CanReadAllGroupMessages
	}
	return false
}

func (x *User) GetSupportsInlineQueries() bool {
	if x != nil {
		return x.SupportsInlineQueries
	}
	return false
}

func (x *User) GetCanConnectToBusiness() bool {
	if x != nil {
		return x.CanConnectToBusiness
	}
	return false
}

func (x *User) GetHasMainWebApp() bool {
	if x != nil {
		return x.HasMainWebApp
	}
	return false
}

type Chat struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type            string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Title           *string                `protobuf:"bytes,3,opt,name=title,proto3,oneof" json:"title,omitempty"`
	Username        *string                `protobuf:"bytes,4,opt,name=username,proto3,oneof" json:"username,omitempty"`
	FirstName       *string                `protobuf:"bytes,5,opt,name=first_name,proto3,oneof" json:"first_name,omitempty"`
	LastName        *string                `protobuf:"bytes,6,opt,name=last_name,proto3,oneof" json:"last_name,omitempty"`
	IsForum         bool                   `protobuf:"varint,7,opt,name=is_forum,proto3" json:"is_forum,omitempty"`
	IsDirectMessage bool                   `protobuf:"varint,8,opt,name=is_direct_message,proto3" json:"is_direct_message,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Chat) Reset() {
	*x = Chat{}
	mi := &file_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chat) ProtoMessage() {}

func (x *Chat) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chat.ProtoReflect.Descriptor instead.
func (*Chat) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{2}
}

func (x *Chat) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Chat) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Chat) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *Chat) GetUsername() string {
	if x != nil && x.Username != nil {
		return *x.Username
	}
	return ""
}

func (x *Chat) GetFirstName() string {
	if x != nil && x.FirstName != nil {
		return *x.FirstName
	}
	return ""
}

func (x *Chat) GetLastName() string {
	if x != nil && x.LastName != nil {
		return *x.LastName
	}
	return ""
}

func (x *Chat) GetIsForum() bool {
	if x != nil {
		return x.IsForum
	}
	return false
}

func (x *Chat) GetIsDirectMessage() bool {
	if x != nil {
		return x.IsDirectMessage
	}
	return false
}

var File_message_proto protoreflect.FileDescriptor

const file_message_proto_rawDesc = "" +
	"\n" +
	"\rmessage.proto\x12\x12telegram.botapi.v9\x1a\x1bbuf/validate/validate.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/api/annotations.proto\"\x9c\x11\n" +
	"\aMessage\x12\x1e\n" +
	"\n" +
	"message_id\x18\x01 \x01(\x03R\n" +
	"message_id\x12,\n" +
	"\x11message_thread_id\x18\x02 \x01(\x03R\x11message_thread_id\x121\n" +
	"\x04from\x18\x04 \x01(\v2\x18.telegram.botapi.v9.UserH\x00R\x04from\x88\x01\x01\x12?\n" +
	"\vsender_chat\x18\x05 \x01(\v2\x18.telegram.botapi.v9.ChatH\x01R\vsender_chat\x88\x01\x01\x123\n" +
	"\x12sender_boost_count\x18\x06 \x01(\x03H\x02R\x12sender_boost_count\x88\x01\x01\x12O\n" +
	"\x13sender_business_bot\x18\a \x01(\v2\x18.telegram.botapi.v9.UserH\x03R\x13sender_business_bot\x88\x01\x01\x12\x12\n" +
	"\x04date\x18\b \x01(\x03R\x04date\x12;\n" +
	"\x16business_connection_id\x18\t \x01(\tH\x04R\x16business_connection_id\x88\x01\x01\x12,\n" +
	"\x04chat\x18\n" +
	" \x01(\v2\x18.telegram.botapi.v9.ChatR\x04chat\x12*\n" +
	"\x10is_topic_message\x18\f \x01(\bR\x10is_topic_message\x122\n" +
	"\x14is_automatic_forward\x18\r \x01(\bR\x14is_automatic_forward\x12L\n" +
	"\x10reply_to_message\x18\x0e \x01(\v2\x1b.telegram.botapi.v9.MessageH\x05R\x10reply_to_message\x88\x01\x01\x12C\n" +
	"\x1areply_to_checklist_task_id\x18\x12 \x01(\x03H\x06R\x1areply_to_checklist_task_id\x88\x01\x01\x127\n" +
	"\avia_bot\x18\x13 \x01(\v2\x18.telegram.botapi.v9.UserH\aR\avia_bot\x88\x01\x01\x12!\n" +
	"\tedit_date\x18\x14 \x01(\x03H\bR\tedit_date\x88\x01\x01\x124\n" +
	"\x15has_protected_content\x18\x15 \x01(\bR\x15has_protected_content\x12&\n" +
	"\x0eis_from_online\x18\x16 \x01(\bR\x0eis_from_online\x12\"\n" +
	"\fis_paid_post\x18\x17 \x01(\bR\fis_paid_post\x12+\n" +
	"\x0emedia_group_id\x18\x18 \x01(\tH\tR\x0emedia_group_id\x88\x01\x01\x12/\n" +
	"\x10author_signature\x18\x19 \x01(\tH\n" +
	"R\x10author_signature\x88\x01\x01\x12-\n" +
	"\x0fpaid_star_count\x18\x1a \x01(\x03H\vR\x0fpaid_star_count\x88\x01\x01\x12\x17\n" +
	"\x04text\x18\x1b \x01(\tH\fR\x04text\x88\x01\x01\x12!\n" +
	"\teffect_id\x18  \x01(\tH\rR\teffect_id\x88\x01\x01\x12\x1d\n" +
	"\acaption\x18+ \x01(\tH\x0eR\acaption\x88\x01\x01\x12:\n" +
	"\x18show_caption_above_media\x18- \x01(\bR\x18show_caption_above_media\x12,\n" +
	"\x11has_media_spoiler\x18. \x01(\bR\x11has_media_spoiler\x12D\n" +
	"\x10new_chat_members\x186 \x03(\v2\x18.telegram.botapi.v9.UserR\x10new_chat_members\x12I\n" +
	"\x10left_chat_member\x187 \x01(\v2\x18.telegram.botapi.v9.UserH\x0fR\x10left_chat_member\x88\x01\x01\x12+\n" +
	"\x0enew_chat_title\x188 \x01(\tH\x10R\x0enew_chat_title\x88\x01\x01\x12,\n" +
	"\x11delete_chat_photo\x18: \x01(\bR\x11delete_chat_photo\x12.\n" +
	"\x12group_chat_created\x18; \x01(\bR\x12group_chat_created\x128\n" +
	"\x17supergroup_chat_created\x18< \x01(\bR\x17supergroup_chat_created\x122\n" +
	"\x14channel_chat_created\x18= \x01(\bR\x14channel_chat_created\x123\n" +
	"\x12migrate_to_chat_id\x18? \x01(\x03H\x11R\x12migrate_to_chat_id\x88\x01\x01\x127\n" +
	"\x14migrate_from_chat_id\x18@ \x01(\x03H\x12R\x14migrate_from_chat_id\x88\x01\x01\x121\n" +
	"\x11connected_website\x18I \x01(\tH\x13R\x11connected_website\x88\x01\x01B\a\n" +
	"\x05_fromB\x0e\n" +
	"\f_sender_chatB\x15\n" +
	"\x13_sender_boost_countB\x16\n" +
	"\x14_sender_business_botB\x19\n" +
	"\x17_business_connection_idB\x13\n" +
	"\x11_reply_to_messageB\x1d\n" +
	"\x1b_reply_to_checklist_task_idB\n" +
	"\n" +
	"\b_via_botB\f\n" +
	"\n" +
	"_edit_dateB\x11\n" +
	"\x0f_media_group_idB\x13\n" +
	"\x11_author_signatureB\x12\n" +
	"\x10_paid_star_countB\a\n" +
	"\x05_textB\f\n" +
	"\n" +
	"_effect_idB\n" +
	"\n" +
	"\b_captionB\x13\n" +
	"\x11_left_chat_memberB\x11\n" +
	"\x0f_new_chat_titleB\x15\n" +
	"\x13_migrate_to_chat_idB\x17\n" +
	"\x15_migrate_from_chat_idB\x14\n" +
	"\x12_connected_website\"\xd2\x04\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06is_bot\x18\x02 \x01(\bR\x06is_bot\x12\x1e\n" +
	"\n" +
	"first_name\x18\x03 \x01(\tR\n" +
	"first_name\x12!\n" +
	"\tlast_name\x18\x04 \x01(\tH\x00R\tlast_name\x88\x01\x01\x12\x1f\n" +
	"\busername\x18\x05 \x01(\tH\x01R\busername\x88\x01\x01\x12)\n" +
	"\rlanguage_code\x18\x06 \x01(\tH\x02R\rlanguage_code\x88\x01\x01\x12\x1e\n" +
	"\n" +
	"is_premium\x18\a \x01(\bR\n" +
	"is_premium\x12:\n" +
	"\x18added_to_attachment_menu\x18\b \x01(\bR\x18added_to_attachment_menu\x12(\n" +
	"\x0fcan_join_groups\x18\t \x01(\bR\x0fcan_join_groups\x12@\n" +
	"\x1bcan_read_all_group_messages\x18\n" +
	" \x01(\bR\x1bcan_read_all_group_messages\x128\n" +
	"\x17supports_inline_queries\x18\v \x01(\bR\x17supports_inline_queries\x128\n" +
	"\x17can_connect_to_business\x18\f \x01(\bR\x17can_connect_to_business\x12*\n" +
	"\x10has_main_web_app\x18\r \x01(\bR\x10has_main_web_appB\f\n" +
	"\n" +
	"_last_nameB\v\n" +
	"\t_usernameB\x10\n" +
	"\x0e_language_code\"\xac\x02\n" +
	"\x04Chat\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x19\n" +
	"\x05title\x18\x03 \x01(\tH\x00R\x05title\x88\x01\x01\x12\x1f\n" +
	"\busername\x18\x04 \x01(\tH\x01R\busername\x88\x01\x01\x12#\n" +
	"\n" +
	"first_name\x18\x05 \x01(\tH\x02R\n" +
	"first_name\x88\x01\x01\x12!\n" +
	"\tlast_name\x18\x06 \x01(\tH\x03R\tlast_name\x88\x01\x01\x12\x1a\n" +
	"\bis_forum\x18\a \x01(\bR\bis_forum\x12,\n" +
	"\x11is_direct_message\x18\b \x01(\bR\x11is_direct_messageB\b\n" +
	"\x06_titleB\v\n" +
	"\t_usernameB\r\n" +
	"\v_first_nameB\f\n" +
	"\n" +
	"_last_nameBTZRgithub.com/quenbyako/cynosure/contrib/telegram-proto/pkg/telegram/botapi/v9;botapib\x06proto3"

var (
	file_message_proto_rawDescOnce sync.Once
	file_message_proto_rawDescData []byte
)

func file_message_proto_rawDescGZIP() []byte {
	file_message_proto_rawDescOnce.Do(func() {
		file_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_message_proto_rawDesc), len(file_message_proto_rawDesc)))
	})
	return file_message_proto_rawDescData
}

var file_message_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_message_proto_goTypes = []any{
	(*Message)(nil), // 0: telegram.botapi.v9.Message
	(*User)(nil),    // 1: telegram.botapi.v9.User
	(*Chat)(nil),    // 2: telegram.botapi.v9.Chat
}
var file_message_proto_depIdxs = []int32{
	1, // 0: telegram.botapi.v9.Message.from:type_name -> telegram.botapi.v9.User
	2, // 1: telegram.botapi.v9.Message.sender_chat:type_name -> telegram.botapi.v9.Chat
	1, // 2: telegram.botapi.v9.Message.sender_business_bot:type_name -> telegram.botapi.v9.User
	2, // 3: telegram.botapi.v9.Message.chat:type_name -> telegram.botapi.v9.Chat
	0, // 4: telegram.botapi.v9.Message.reply_to_message:type_name -> telegram.botapi.v9.Message
	1, // 5: telegram.botapi.v9.Message.via_bot:type_name -> telegram.botapi.v9.User
	1, // 6: telegram.botapi.v9.Message.new_chat_members:type_name -> telegram.botapi.v9.User
	1, // 7: telegram.botapi.v9.Message.left_chat_member:type_name -> telegram.botapi.v9.User
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_message_proto_init() }
func file_message_proto_init() {
	if File_message_proto != nil {
		return
	}
	file_message_proto_msgTypes[0].OneofWrappers = []any{}
	file_message_proto_msgTypes[1].OneofWrappers = []any{}
	file_message_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_message_proto_rawDesc), len(file_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_proto_goTypes,
		DependencyIndexes: file_message_proto_depIdxs,
		MessageInfos:      file_message_proto_msgTypes,
	}.Build()
	File_message_proto = out.File
	file_message_proto_goTypes = nil
	file_message_proto_depIdxs = nil
}
