// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: webhook_service.proto

package botapi

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Update struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	UpdateId int64                  `protobuf:"varint,1,opt,name=update_id,proto3" json:"update_id,omitempty"`
	// Types that are valid to be assigned to Update:
	//
	//	*Update_Message
	Update        isUpdate_Update `protobuf_oneof:"update"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Update) Reset() {
	*x = Update{}
	mi := &file_webhook_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Update) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Update) ProtoMessage() {}

func (x *Update) ProtoReflect() protoreflect.Message {
	mi := &file_webhook_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Update.ProtoReflect.Descriptor instead.
func (*Update) Descriptor() ([]byte, []int) {
	return file_webhook_service_proto_rawDescGZIP(), []int{0}
}

func (x *Update) GetUpdateId() int64 {
	if x != nil {
		return x.UpdateId
	}
	return 0
}

func (x *Update) GetUpdate() isUpdate_Update {
	if x != nil {
		return x.Update
	}
	return nil
}

func (x *Update) GetMessage() *Message {
	if x != nil {
		if x, ok := x.Update.(*Update_Message); ok {
			return x.Message
		}
	}
	return nil
}

type isUpdate_Update interface {
	isUpdate_Update()
}

type Update_Message struct {
	Message *Message `protobuf:"bytes,2,opt,name=message,proto3,oneof"`
}

func (*Update_Message) isUpdate_Update() {}

var File_webhook_service_proto protoreflect.FileDescriptor

const file_webhook_service_proto_rawDesc = "" +
	"\n" +
	"\x15webhook_service.proto\x12\x12telegram.botapi.v9\x1a\x1bbuf/validate/validate.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/api/annotations.proto\x1a\rmessage.proto\"i\n" +
	"\x06Update\x12\x1c\n" +
	"\tupdate_id\x18\x01 \x01(\x03R\tupdate_id\x127\n" +
	"\amessage\x18\x02 \x01(\v2\x1b.telegram.botapi.v9.MessageH\x00R\amessageB\b\n" +
	"\x06update2`\n" +
	"\x0eWebhookService\x12N\n" +
	"\n" +
	"SendUpdate\x12\x1a.telegram.botapi.v9.Update\x1a\x16.google.protobuf.Empty\"\f\x82\xd3\xe4\x93\x02\x06:\x01*\"\x01/BTZRgithub.com/quenbyako/cynosure/contrib/telegram-proto/pkg/telegram/botapi/v9;botapib\x06proto3"

var (
	file_webhook_service_proto_rawDescOnce sync.Once
	file_webhook_service_proto_rawDescData []byte
)

func file_webhook_service_proto_rawDescGZIP() []byte {
	file_webhook_service_proto_rawDescOnce.Do(func() {
		file_webhook_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_webhook_service_proto_rawDesc), len(file_webhook_service_proto_rawDesc)))
	})
	return file_webhook_service_proto_rawDescData
}

var file_webhook_service_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_webhook_service_proto_goTypes = []any{
	(*Update)(nil),        // 0: telegram.botapi.v9.Update
	(*Message)(nil),       // 1: telegram.botapi.v9.Message
	(*emptypb.Empty)(nil), // 2: google.protobuf.Empty
}
var file_webhook_service_proto_depIdxs = []int32{
	1, // 0: telegram.botapi.v9.Update.message:type_name -> telegram.botapi.v9.Message
	0, // 1: telegram.botapi.v9.WebhookService.SendUpdate:input_type -> telegram.botapi.v9.Update
	2, // 2: telegram.botapi.v9.WebhookService.SendUpdate:output_type -> google.protobuf.Empty
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_webhook_service_proto_init() }
func file_webhook_service_proto_init() {
	if File_webhook_service_proto != nil {
		return
	}
	file_message_proto_init()
	file_webhook_service_proto_msgTypes[0].OneofWrappers = []any{
		(*Update_Message)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_webhook_service_proto_rawDesc), len(file_webhook_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_webhook_service_proto_goTypes,
		DependencyIndexes: file_webhook_service_proto_depIdxs,
		MessageInfos:      file_webhook_service_proto_msgTypes,
	}.Build()
	File_webhook_service_proto = out.File
	file_webhook_service_proto_goTypes = nil
	file_webhook_service_proto_depIdxs = nil
}
