// Code generated by ogen, DO NOT EDIT.

package httpapi

import (
	"context"
	"net/url"
	"strings"

	"github.com/go-faster/errors"

	"github.com/ogen-go/ogen/conv"
	ht "github.com/ogen-go/ogen/http"
	"github.com/ogen-go/ogen/uri"
)

func trimTrailingSlashes(u *url.URL) {
	u.Path = strings.TrimRight(u.Path, "/")
	u.RawPath = strings.TrimRight(u.RawPath, "/")
}

// Invoker invokes operations described by OpenAPI v3 specification.
type Invoker interface {
	// GetAgentCard invokes GetAgentCard operation.
	//
	// This endpoint provides the agent card information for A2A agents.
	// It is used to display the client information in the agent card format.
	//
	// GET /.well-known/agent-card.json
	GetAgentCard(ctx context.Context, params GetAgentCardParams) (GetAgentCardRes, error)
	// OAuthCallbackGet invokes GET /oauth/callback operation.
	//
	// This endpoint receives the authorization code and state from the OAuth2
	// provider after a user successfully authenticates. The application should
	// validate the state and then use the code to request an access token from
	// the provider's token endpoint.
	//
	// GET /oauth/callback
	OAuthCallbackGet(ctx context.Context, params OAuthCallbackGetParams) (OAuthCallbackGetRes, error)
}

// Client implements OAS client.
type Client struct {
	serverURL *url.URL
	baseClient
}

var _ Handler = struct {
	*Client
}{}

// NewClient initializes new Client defined by OAS.
func NewClient(serverURL string, opts ...ClientOption) (*Client, error) {
	u, err := url.Parse(serverURL)
	if err != nil {
		return nil, err
	}
	trimTrailingSlashes(u)

	c, err := newClientConfig(opts...).baseClient()
	if err != nil {
		return nil, err
	}
	return &Client{
		serverURL:  u,
		baseClient: c,
	}, nil
}

type serverURLKey struct{}

// WithServerURL sets context key to override server URL.
func WithServerURL(ctx context.Context, u *url.URL) context.Context {
	return context.WithValue(ctx, serverURLKey{}, u)
}

func (c *Client) requestURL(ctx context.Context) *url.URL {
	u, ok := ctx.Value(serverURLKey{}).(*url.URL)
	if !ok {
		return c.serverURL
	}
	return u
}

// GetAgentCard invokes GetAgentCard operation.
//
// This endpoint provides the agent card information for A2A agents.
// It is used to display the client information in the agent card format.
//
// GET /.well-known/agent-card.json
func (c *Client) GetAgentCard(ctx context.Context, params GetAgentCardParams) (GetAgentCardRes, error) {
	res, err := c.sendGetAgentCard(ctx, params)
	return res, err
}

func (c *Client) sendGetAgentCard(ctx context.Context, params GetAgentCardParams) (res GetAgentCardRes, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/.well-known/agent-card.json"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	h := uri.NewHeaderEncoder(r.Header)
	{
		cfg := uri.HeaderParameterEncodingConfig{
			Name:    "Host",
			Explode: false,
		}
		if err := h.EncodeParam(cfg, func(e uri.Encoder) error {
			if val, ok := params.Host.Get(); ok {
				return e.EncodeValue(conv.StringToString(val))
			}
			return nil
		}); err != nil {
			return res, errors.Wrap(err, "encode header")
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	result, err := decodeGetAgentCardResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// OAuthCallbackGet invokes GET /oauth/callback operation.
//
// This endpoint receives the authorization code and state from the OAuth2
// provider after a user successfully authenticates. The application should
// validate the state and then use the code to request an access token from
// the provider's token endpoint.
//
// GET /oauth/callback
func (c *Client) OAuthCallbackGet(ctx context.Context, params OAuthCallbackGetParams) (OAuthCallbackGetRes, error) {
	res, err := c.sendOAuthCallbackGet(ctx, params)
	return res, err
}

func (c *Client) sendOAuthCallbackGet(ctx context.Context, params OAuthCallbackGetParams) (res OAuthCallbackGetRes, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/oauth/callback"
	uri.AddPathParts(u, pathParts[:]...)

	q := uri.NewQueryEncoder()
	{
		// Encode "code" parameter.
		cfg := uri.QueryParameterEncodingConfig{
			Name:    "code",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
			return e.EncodeValue(conv.StringToString(params.Code))
		}); err != nil {
			return res, errors.Wrap(err, "encode query")
		}
	}
	{
		// Encode "state" parameter.
		cfg := uri.QueryParameterEncodingConfig{
			Name:    "state",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
			if val, ok := params.State.Get(); ok {
				return e.EncodeValue(conv.StringToString(val))
			}
			return nil
		}); err != nil {
			return res, errors.Wrap(err, "encode query")
		}
	}
	u.RawQuery = q.Values().Encode()

	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	result, err := decodeOAuthCallbackGetResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}
