// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/goforj/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cynosure

import (
	"context"
	"github.com/quenbyako/cynosure/internal/domains/cynosure/ports"
)

// Injectors from wire.go:

func buildApp(ctx context.Context, config *appParams) (*App, error) {
	adapter, err := newSQLAdapter(ctx, config)
	if err != nil {
		return nil, err
	}
	threadStorage := ports.NewThreadStorage(adapter)
	geminiModel, err := newGeminiModel(ctx, config)
	if err != nil {
		return nil, err
	}
	chatModel := ports.NewChatModel(geminiModel)
	handler := newOAuthHandler(config)
	oAuthHandler := ports.NewOAuthHandler(handler)
	serverStorage := ports.NewServerStorage(adapter)
	accountStorage := ports.NewAccountStorage(adapter)
	mcpHandler := newMCPHandler(config, oAuthHandler, serverStorage, accountStorage)
	toolClient := ports.NewToolClient(mcpHandler)
	toolSemanticIndex := ports.NewToolSemanticIndex(geminiModel)
	toolStorage := ports.NewToolStorage(adapter)
	agentStorage := ports.NewAgentStorage(adapter)
	cynosureLogger := newLogCallbacks(config)
	service := newChatUsecase(config, threadStorage, chatModel, toolClient, toolSemanticIndex, toolStorage, serverStorage, accountStorage, agentStorage, cynosureLogger)
	userStorage := ports.NewUserStorage(adapter)
	usecase := newAccountsUsecase(config, serverStorage, oAuthHandler, accountStorage, toolStorage, toolSemanticIndex, toolClient, userStorage)
	serversService := newServersUsecase(config, serverStorage, oAuthHandler)
	app, err := connectDependencies(config, service, usecase, serversService)
	if err != nil {
		return nil, err
	}
	return app, nil
}
