// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/goforj/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cynosure

import (
	"context"
	"github.com/goforj/wire"
	"github.com/quenbyako/core/contrib/runtime"
	"github.com/quenbyako/cynosure/internal/adapters/gemini"
	"github.com/quenbyako/cynosure/internal/adapters/inmemory"
	"github.com/quenbyako/cynosure/internal/adapters/mcp"
	"github.com/quenbyako/cynosure/internal/adapters/oauth"
	"github.com/quenbyako/cynosure/internal/adapters/ory"
	"github.com/quenbyako/cynosure/internal/adapters/sql"
	"github.com/quenbyako/cynosure/internal/controllers/telegram"
	"github.com/quenbyako/cynosure/internal/domains/cynosure/ports"
	"github.com/quenbyako/cynosure/internal/domains/cynosure/ports/chatmodel"
	"github.com/quenbyako/cynosure/internal/domains/cynosure/ports/identitymanager"
	"github.com/quenbyako/cynosure/internal/domains/cynosure/ports/oauthhandler"
	"github.com/quenbyako/cynosure/internal/domains/cynosure/ports/ratelimiter"
	"github.com/quenbyako/cynosure/internal/domains/cynosure/ports/toolclient"
	"github.com/quenbyako/cynosure/internal/logs"
)

// Injectors from wire.go:

func buildApp(ctx context.Context, config *appParams) (*App, error) {
	rateLimiter := newRateLimiter(config)
	adapter, err := newSQLAdapter(ctx, config)
	if err != nil {
		return nil, err
	}
	accountStorage := ports.NewAccountStorage(adapter)
	serverStorage := ports.NewServerStorage(adapter)
	handler := newOAuthHandler(config)
	portWrapped := oauthhandler.New(handler)
	refreshConstructor := newOauthRefresher(accountStorage, serverStorage, portWrapped)
	toolStorage := ports.NewToolStorage(adapter)
	baseLogger := newLogger(config)
	geminiModel, err := newGeminiModel(ctx, config, baseLogger)
	if err != nil {
		return nil, err
	}
	toolSemanticIndex := ports.NewToolSemanticIndex(geminiModel)
	mcpHandler, err := newMCPHandler(ctx, config, refreshConstructor)
	if err != nil {
		return nil, err
	}
	toolclientPortWrapped := toolclient.New(mcpHandler)
	adapter2, err := newOryClient(ctx, config)
	if err != nil {
		return nil, err
	}
	identitymanagerPortWrapped := identitymanager.New(adapter2)
	usecase, err := newAccountsUsecase(config, serverStorage, portWrapped, accountStorage, toolStorage, toolSemanticIndex, toolclientPortWrapped, identitymanagerPortWrapped)
	if err != nil {
		return nil, err
	}
	cynosureAdminControllerWireBind := bindAdminController(config, usecase)
	cynosureOauthControllerWireBind := bindOAuthController(config, usecase)
	threadStorageWrapped := ports.NewThreadStorage(adapter)
	chatmodelPortWrapped := chatmodel.New(geminiModel)
	agentStorage := ports.NewAgentStorage(adapter)
	ratelimiterPortWrapped := ratelimiter.New(rateLimiter)
	usecase2, err := newChatUsecase(config, threadStorageWrapped, chatmodelPortWrapped, toolclientPortWrapped, toolSemanticIndex, toolStorage, serverStorage, accountStorage, agentStorage, ratelimiterPortWrapped)
	if err != nil {
		return nil, err
	}
	usecase3, err := newUsersUsecase(config, identitymanagerPortWrapped, agentStorage, accountStorage, serverStorage, toolStorage, toolclientPortWrapped, toolSemanticIndex)
	if err != nil {
		return nil, err
	}
	cynosureTelegramControllerWireBind, err := bindTelegramController(ctx, config, baseLogger, usecase2, usecase3)
	if err != nil {
		return nil, err
	}
	cynosureMcpControllerWireBind, err := bindMCPController(config, usecase)
	if err != nil {
		return nil, err
	}
	app, err := connectDependencies(config, rateLimiter, refreshConstructor, usecase, cynosureAdminControllerWireBind, cynosureOauthControllerWireBind, cynosureTelegramControllerWireBind, cynosureMcpControllerWireBind, mcpHandler)
	if err != nil {
		return nil, err
	}
	return app, nil
}

// wire.go:

var loggerConstructor = wire.NewSet(
	newLogger, wire.Bind(new(gemini.LogCallbacks), new(*logs.BaseLogger)), wire.Bind(new(telegram.LogCallbacks), new(*logs.BaseLogger)), wire.Bind(new(runtime.LogCallbacks), new(*logs.BaseLogger)),
)

var (
	sqlAdapter         = wire.NewSet(newSQLAdapter, wire.Bind(new(ports.AgentStorageFactory), new(*sql.Adapter)), wire.Bind(new(ports.AccountStorageFactory), new(*sql.Adapter)), wire.Bind(new(ports.ServerStorageFactory), new(*sql.Adapter)), wire.Bind(new(ports.ThreadStorageFactory), new(*sql.Adapter)), wire.Bind(new(ports.ToolStorageFactory), new(*sql.Adapter)))
	geminiAdapter      = wire.NewSet(newGeminiModel, wire.Bind(new(chatmodel.PortFactory), new(*gemini.GeminiModel)), wire.Bind(new(ports.ToolSemanticIndexFactory), new(*gemini.GeminiModel)))
	oauthAdapter       = wire.NewSet(newOAuthHandler, wire.Bind(new(oauthhandler.Factory), new(*oauth.Handler)))
	mcpAdapter         = wire.NewSet(newMCPHandler, wire.Bind(new(toolclient.PortFactory), new(*mcp.Handler)))
	oauthRefresher     = wire.NewSet(newOauthRefresher)
	oryAdapter         = wire.NewSet(newOryClient, wire.Bind(new(identitymanager.PortFactory), new(*ory.Adapter)))
	ratelimiterAdapter = wire.NewSet(newRateLimiter, wire.Bind(new(ratelimiter.PortFactory), new(*inmemory.RateLimiter)))
)

var (
	chatUsecase     = wire.NewSet(newChatUsecase)
	accountsUsecase = wire.NewSet(newAccountsUsecase)
	usersUsecase    = wire.NewSet(newUsersUsecase)
)

var controllersSet = wire.NewSet(
	bindAdminController,
	bindOAuthController,
	bindTelegramController,
	bindMCPController,
)
