// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cynosure

import (
	"context"
	"github.com/quenbyako/cynosure/internal/adapters/tool-handler"
	"github.com/quenbyako/cynosure/internal/domains/cynosure/ports"
)

// Injectors from wire.go:

func buildApp(ctx context.Context, config *appParams) (*App, error) {
	zepStorage := newZepStorage(ctx, config)
	storageRepository := ports.NewStorageRepository(zepStorage)
	geminiModel, err := newGeminiModel(ctx, config)
	if err != nil {
		return nil, err
	}
	chatModel := ports.NewChatModel(geminiModel)
	handler := newOAuthHandler(config)
	oAuthHandler := ports.NewOAuthHandler(handler)
	file := newFileAdapter(config)
	serverStorage := ports.NewServerStorage(file)
	accountStorage := ports.NewAccountStorage(file)
	primitiveHandler := primitive.NewHandler(oAuthHandler, serverStorage, accountStorage)
	toolManager := ports.NewToolManager(primitiveHandler)
	modelSettingsStorage := ports.NewModelSettingsStorage(file)
	cynosureLogger := newLogCallbacks(config)
	service := newChatUsecase(config, storageRepository, chatModel, toolManager, serverStorage, accountStorage, modelSettingsStorage, cynosureLogger)
	accountsService := newAccountsUsecase(config, serverStorage, oAuthHandler, toolManager)
	serversService := newServersUsecase(config, serverStorage, oAuthHandler)
	app, err := newApp(config, service, accountsService, serversService)
	if err != nil {
		return nil, err
	}
	return app, nil
}
